### ISSUE TITLE
Update Question!

### ISSUE THREAD

**Issue by Centernews** [davidfig/pixi-viewport#100]
After an update the plugin in the @types index.d.ts, when I run with angular 6. I got an error message like this:
_### ERROR in node_modules/pixi-viewport/@types/index.d.ts(189,34): error TS2694: Namespace 'Viewport' has no exported member 'Viewport'.
node_modules/pixi-viewport/@types/index.d.ts(189,45): error TS1093: Type annotation cannot appear on a constructor declaration.
node_modules/pixi-viewport/@types/index.d.ts(257,45): error TS2694: Namespace 'Viewport' has no exported member 'Plugin'.

Very hope can get your help, thank you.

**Comment by davidfig** [comment]
Try 3.11.2. I updated the definition file. Hopefully it removes the error.

**Comment by Centernews** [comment]
It working now! Thanks!!!!
