### ISSUE TITLE
Wrong typings

### ISSUE THREAD

**Issue by kaflake** [davidfig/pixi-viewport#101]
The typscript typingsfile shows update() as a methode for Viewport.
https://github.com/davidfig/pixi-viewport/blob/23aa0c32dc3cd62e6c16b7ba254719b492455940/%40types/index.d.ts#L237

But correct shoulld be update(ellapsed)
https://github.com/davidfig/pixi-viewport/blob/23aa0c32dc3cd62e6c16b7ba254719b492455940/src/viewport.js#L121

**Comment by davidfig** [comment]
Thanks. v3.13.1 fixes this issue.
