### ISSUE TITLE
Documentation new Viewport is missleading - app.renderer.interaction is undefined

### ISSUE THREAD

**Issue by mszkb** [davidfig/pixi-viewport#104]
The README.md new Viewport example is old.
app.renderer.interaction is null. Like in https://davidfig.github.io/pixi-viewport/ it should be app.renderer.plugins.interaction so the wheel() is working as intended.

**Comment by mszkb** [comment]
I fixed the documentation. But the compiling is up to you, because we have different time zones and my jsdoc might override every file :)

**Comment by davidfig** [comment]
Thanks! I just compiled and published with the change as v3.15.1.
