### ISSUE TITLE
Fixed size of viewport

### ISSUE THREAD

**Issue by renatonolo** [davidfig/pixi-viewport#106]
Hello.

I'm trying to create a viewport with fixed sizes (800 width x 544 height) and I'm adding a large child inside this viewport.

How can I do to fix the viewport size independent of his child size?

**Comment by davidfig** [comment]
Two options: 

1. set the pixi.js canvas to the required size; or
2. add a mask to the viewport with the required size and placement

For #2, you can also look at pixi-scrollbox, which is a pixi-viewport with the mask (and scrollbars)

**Comment by renatonolo** [comment]
Hello man.

First thank you for reply.

I'm trying to use the second option, creating a mask with PIXI.Graphics() and putting this mask into my container (container.mask = mask) but when i put it on my container, the container not appear. If I set container.mask to null, the container work again normally.

=X

**Comment by davidfig** [comment]
Glad it worked. Let me know if you have any other issues!
