### ISSUE TITLE
Mouse edges docs misspell

### ISSUE THREAD

**Issue by Roen00** [davidfig/pixi-viewport#109]
https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#mouseEdges

top | number |   | optionalalternatively, set top distance (leave unset for no top scroll)
-- | -- | -- | --
bottom | number |   | optionalalternatively, set bottom distance (leave unset for no top scroll)
left | number |   | optionalalternatively, set left distance (leave unset for no top scroll)
right | number |   | optionalalternatively, set right distance (leave unset for no top scroll)

The description should have the corresponding name instead of "top"

**Comment by davidfig** [comment]
Thanks! I updated the docs with the correct reference.
