### ISSUE TITLE
Line doesn't get zoomed

### ISSUE THREAD

**Issue by krnbatta** [davidfig/pixi-viewport#110]
I tried using this library. On my canvas, I have rectangles and line connecting different rectangles. The rectangles get zoomed in and out alright. But, the line doesn't get affected at all. It stays the same.

**Comment by krnbatta** [comment]
<img width="781" alt="screenshot 2019-01-27 at 10 26 09 am" src="https://user-images.githubusercontent.com/8068341/51796792-96731b00-221e-11e9-854c-8cb54b6469b1.png">
<img width="783" alt="screenshot 2019-01-27 at 10 28 12 am" src="https://user-images.githubusercontent.com/8068341/51796793-96731b00-221e-11e9-8e15-3b2c8eb55f85.png">
<img width="783" alt="screenshot 2019-01-27 at 10 28 19 am" src="https://user-images.githubusercontent.com/8068341/51796794-96731b00-221e-11e9-8c8b-bb7eab0daad9.png">

**Comment by davidfig** [comment]
What code are you using to draw the white line?

**Comment by krnbatta** [comment]
```
  let line = new PIXI.Graphics();
  line.lineStyle(1, config.lineColor);
  node.linePoints.forEach((point, index) => {
      line.moveTo(point.x, point.y);
    }
    else{
      line.lineTo(point.x, point.y);
    }
  });

```

**Comment by krnbatta** [comment]
Shall I create a polygon by drawing the last edge as transparent to the starting point?

**Comment by krnbatta** [comment]
Sorry, my bad!
I needed to addChild to the viewport. i was adding to stage directly.
