### ISSUE TITLE
Avoid zoom out beyond screen size

### ISSUE THREAD

**Issue by krnbatta** [davidfig/pixi-viewport#111]
Hi 
I am using pixi-viewport as mentioned in the boilerplate code on your tutorial page. I am not able to stop the zooming out beyond the screen size.
My requirement is zooming in up to 3x and zooming out only till the normal size(i.e. not diminishing to a point)
Is it possible to do this?

**Comment by davidfig** [comment]
Surely. Just use the clampZoom:
```js
viewport.clampZoom(minWidth, minHeight, maxWidth, maxHeight);
```
and set minWidth and minHeight to the actual size, and maxWidth and maxHeight to the actual size multiplied by 3.

**Comment by krnbatta** [comment]
It is not working

**Comment by krnbatta** [comment]
This is my code:
```
          this.app = new PIXI.Application({
              width: width,
              height: height,
              view: this.canvas,
              transparent: true
          });
          this.renderer = this.app.renderer;
          this.viewport = new Viewport({
              screenWidth: width,
              screenHeight: height,
              worldWidth: width,
              worldHeight: height,
              interaction: this.renderer.plugins.interaction
          });
          this.stage = this.app.stage;
          this.stage.addChild(this.viewport);
          this.viewport.drag().pinch().wheel().decelerate().clampZoom(width, height, width*2, height*2);
          this.renderer.render(this.stage);

```

**Comment by krnbatta** [comment]
Also, during expansion and contraction, the dimensions of certain shapes are changed automatically.
<img width="782" alt="screenshot 2019-01-30 at 3 02 30 am" src="https://user-images.githubusercontent.com/8068341/51941832-8e43f700-243b-11e9-9505-8754267a003a.png">

**Comment by krnbatta** [comment]
In the above image, some cells of the grid are expanded extra whereas all are of equal length.

**Comment by davidfig** [comment]
Oops, wrong parameters:
```js
viewport.clampZoom({ minWidth: width, maxWidth: width * 3 });
```

**Comment by krnbatta** [comment]
The minWidth option is not working. Max width option is working. 
Also, the pinch event propagates from inside to outside and vice versa. Please help me with this also. :)
Thanks for writing this library. It saved me a lot of time.

**Comment by davidfig** [comment]
Hmm...I just retested the minWidth parameter and it seems to work: see the demo at https://davidfig.github.io/pixi-viewport/ and (1) check clamp-zoom, (2) uncheck bounce, and (3) optionally set minHeight and maxHeight to 0, to see how it works. 

What do you mean that the pinch event propagates from inside to outside? Do you have more than one viewport set on the same area?

**Comment by krnbatta** [comment]
No, I don't have more than one view.
<img width="1280" alt="screenshot 2019-01-31 at 10 42 28 am" src="https://user-images.githubusercontent.com/8068341/52031982-ffbb9c80-2544-11e9-8495-fcc8a708802f.png">
<img width="1280" alt="screenshot 2019-01-31 at 10 42 45 am" src="https://user-images.githubusercontent.com/8068341/52031984-00543300-2545-11e9-80ef-9a3524187437.png">

The monitor has canvas inside it. When I pinch inside the monitor, the whole page zooms in and out. Similarly, when I pinch outside the monitor(say on the tablet on the right), the canvas zooms in and out then as well. 
Also, you can see in the image that certain cells in the grid are of uneven shape. This happens after zoom in/zoom out.
Also, as you can see that the canvas is zoomed in a lot while I set minWidth and minHeight to be width and height respectively.

**Comment by davidfig** [comment]
Oh. I think you're zooming the actual page and not the viewport. Use this in your index.html to stop the zooming:
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```
The viewport does not control the page zooming, only within the canvas element. See if this helps.

**Comment by davidfig** [comment]
Can you set up a jsfiddle with demo code showing the problem? The code above seems to work fine for me.

**Comment by davidfig** [comment]
Thanks for the codepen.

When you pinch the mobile phone image, what you're doing is pinching the web browser. This has nothing to do with pixi-viewport since pixi-viewport does not receive input events outside of the viewport's screen size. To stop that pinching you'll have to catch the touch events on that part of the screen and call event.preventDefault() (see this answer: https://stackoverflow.com/a/37712966/1955997).

**Comment by krnbatta** [comment]
Hi
But the viewport is zooming out as well. I don't want it to.
I want viewport to not zoom out beyond canvas size and zoom in to 2x. And it should not be dragged beyond the canvas position. 
Can you please help me with this.

**Comment by davidfig** [comment]
The viewport changes zoom because the entire page is changing zoom. To stop the zoom behavior of the page, you'll have to catch the touchstart event:
```js
document.body.addEventListener('touchstart', e => e.preventDefault(), { passive: false })
```
Hopefully this helps.

**Comment by krnbatta** [comment]
I am afraid it is not helping

**Comment by davidfig** [comment]
Here's a fork with the added code: https://codepen.io/davidfig/pen/rPYGRJ

You can no longer pinch outside the viewport.

**Comment by krnbatta** [comment]
The codepen is zooming out and not zooming in. And also dragging beyond canvas size.(https://github.com/davidfig/pixi-viewport/issues/111#issuecomment-461204094)
Also, the codepen was not pinching outside viewport even before we added 'touchstart' code.

**Comment by krnbatta** [comment]
Can you please check the following links:
https://github.com/krnbatta/pixi-viewport-test => Here, I haven't added anything(meta/touchstart) to control pinch. But, the viewport is the only thing that is zooming.

This is original project hosted on Github: https://krnbatta.github.io/
The project requires uploading the map file(on top): https://github.com/krnbatta/krnbatta.github.io/blob/master/CSC2F.map

This behaves weirdly. The code for viewport is present at Controller.js (if you inspect in the source)
