### ISSUE TITLE
Namespace 'PIXI.AnimatedSprite' has no exported member 'textures'.

### ISSUE THREAD

**Issue by Skuriles** [davidfig/pixi-viewport#113]
Hello, 
I'm using pixi with typescript, Pixi V5rc.

But when I try to use the typeDef of Pixi I get this error:

Namespace 'PIXI.AnimatedSprite' has no exported member 'textures'.
But from the API I can't find that this should be wrong or that there is a method like "setTextures" or something.

Background: 
I'm trying to switch textures from a AnimatedSprite. 
Or would it be better to pack all textures to the sprite from the beginning and only switch animation index for the textures? But I didn't found to to this as well...

Thanks

**Comment by davidfig** [comment]
You should probably ask this in pixi.js issue page. These are the issues is for pixi-viewport.

**Comment by Skuriles** [comment]
Oh sorry.. too many tabs open in browser
