### ISSUE TITLE
Animating Zoom / Move

### ISSUE THREAD

**Issue by mrdoinel** [davidfig/pixi-viewport#114]
Sorry for the noob question here :
I just discovered this awesome repo and I am wondering how to animate a zoom between to 2 states (while staying centered) :

```
// take the available space
viewport.fit(true);

// to a defined value of zoom
viewport.zoomPercent(0.25, true);
```

Should I use a tween library and iterate until reaching the end value or is there internal way of doing this ?

I basically have the same questions about moving into the viewport using viewport.moveCenter(x,y)

**Comment by davidfig** [comment]
Have you tried snapZoom? Here's how I'd change states:

```js
viewport.snapZoom({
   width: newWidth, 
   time: timeInMS, 
   removeOnComplete: true, 
   forceStart: true 
});
```
viewport.snap() provides similar functionality to move the camera.

**Comment by mrdoinel** [comment]
Thank you this is what I was looking for!

I am having issue understanding how do you set values for the zoom.
For example, I am trying to achieve something really simple.
I want to have a viewport with an image that is centered and covering the whole zone and then zooming at the center of the image using snapZoom.

```
      // width and height of my image
      this.WIDTH = 5000;
      this.HEIGHT = 5000;

      // create viewport
      this.viewport = new Viewport({
          screenWidth: window.innerWidth,
          screenHeight: window.innerHeight,
          worldWidth: this.WIDTH,
          worldHeight: this.HEIGHT,
          interaction: this.app.renderer.plugins.interaction
      });

      this.app.renderer.autoResize = true;
      this.app.renderer.resize(window.innerWidth, window.innerHeight);
      this.viewport.resize(window.innerWidth, window.innerHeight, this.WIDTH, this.HEIGHT);

      // add the viewport to the stage
      this.app.stage.addChild(this.viewport);

let spriteTexture = new PIXI.Sprite(
          PIXI.loader.resources['/dist/images/world.jpg'].texture
);

this.sprite = this.viewport.addChild(spriteTexture);
this.sprite.width = this.WIDTH;
this.sprite.height = this.HEIGHT;
this.sprite.position.set(-(this.WIDTH/2), -(this.HEIGHT/2));

// Zoom in
this.viewport.snapZoom({
    width: this.WIDTH / 10,
    time: 1000,
    forceStart: true,
});
```

The newWidth is the size in pixels of the portion of the world you want to see ?
Because the smaller the value the bigger the zoom ?
I am not sure how to set the value for the zoom.
Thank you for this library!

**Comment by davidfig** [comment]
The width/height is a bit confusing. Think of it as the number of pixels you want to see on the screen. So if you want a 100x100 box to fit on the screen you would set width=100 (which zooms it all the way in), but if you want it take only 10% of the screen, then you would set width=1000. 

Does that make sense?

**Comment by mrdoinel** [comment]
Yes it make sense.

At the end I ended up doing it manually (without your library) because I had an issue with the snap method to move when setting the app to bounce on the edge.
Everything was working fine but when I was reaching the side of the world, I could not move back to the center.

**Comment by davidfig** [comment]
Ugh. I hate it when libraries don't work properly :) Glad everything worked out in the end.
