### ISSUE TITLE
mouse edges doesn't work with latest pixi

### ISSUE THREAD

**Issue by jrowny** [davidfig/pixi-viewport#115]
I'm testing mouseEdges with Pixi V4 and it looks like the mouse handler bails because `e.data.identifier  !== 'MOUSE'`, when I logged the code I see that e.data.identifier is `1`, not a a string. I also see that the official PIxi docs note that this is a number, not a string in InteractionData. Perhaps test to see if it's MOUSE or 1 to maintain backwards compatibility?

**Comment by davidfig** [comment]
Thanks for the report. I added the suggested change in v3.17.1. Let me know if that fixes it.

**Comment by jrowny** [comment]
works beautifully now! thanks so much for the quick fix! A feature that would be great for my use case would be a way to configure mouseEdges to allow a mouse button, that way I can have it work while I'm "dragging" an element.

**Comment by davidfig** [comment]
A nice little morning project. I added options.allowButtons to mouseEdges. If set to true then it doesn't cancel the mouseEdges plugin when the left mouse button is pressed. 

Change allowButtons to true to see it in the demo: https://davidfig.github.io/pixi-viewport/mouse-edges/
