### ISSUE TITLE
Drag not possible with right mouse button

### ISSUE THREAD

**Issue by MRVDH** [davidfig/pixi-viewport#116]
I would like to have the possibility to drag the viewport with the right mouse button instead of the left button. Could you implement this?

**Comment by davidfig** [comment]
This could probably work. You would need to tie into the "contextmenu" event. (Here's a good site I found: http://www.html5gamedevs.com/topic/25254-how-do-do-right-click-on-a-container/ that provides details on how to do that with pixi.)

This doesn't seem like a general enough need to add it to the main code, but you can create a new plugin using the src/drag.js as a model, and then add it to the viewport using the userPlugin() method. It shouldn't wouldn't take many changes. The big one is to replace the handleDown code with a handler for the "contextmenu" event. This would trigger the down (although you would have to figure out how the mouseup code would work.) The rest of the code should work almost as is. 

Happy to take a look at your code if you get stuck. Good luck!

**Comment by MRVDH** [comment]
Thank you! I will look at it after the weekend and possibly create a pull request for a "rightMouseDrag" plugin if that's okay.

**Comment by davidfig** [comment]
Sure. That would be great.

**Comment by artnas** [comment]
Hey. I don't know what's the status of this issue, but a way to set keys for all operations would be a great addition.

**Comment by davidfig** [comment]
What do you mean by setting keys for all operations? How would that work?

**Comment by artnas** [comment]
Being able to bind dragging to right mouse button or middle mouse button instead of always using the left mouse button is an important setting, there are many games/tools which use left mouse button for other actions.

I think it's the only one - I've read through the API and didn't find any other operations which would benefit from a way to set their keys (for example zoom only makes sense if it uses the mouse wheel).

**Comment by davidfig** [comment]
Okay. Let me take a crack at it and see what I can come up with.

**Comment by davidfig** [comment]
Okay, check out v3.22.0. I added options.mouseButtons to viewport.drag(). Change it to 'right' to only enable dragging with right button. Let me know if you have any problems.

**Comment by davidfig** [comment]
Closing this since no response.
