### ISSUE TITLE
Cannot read property 'shared' of undefined

### ISSUE THREAD

**Issue by Cirych** [davidfig/pixi-viewport#117]
Hi and thank you for your library!

Unfortunately, there is an error in new version:
"pixi-viewport": "^3.18.0",

viewport.js:107 Uncaught TypeError: Cannot read property 'shared' of undefined
    at new Viewport (viewport.js:107)
    at customDisplayObject (ViewPortNativeScroll.tsx:11)

It seems, like the `PIXI.Ticker` is undefined in some cases, so there is an unhandled exception here:

```
if (!options.noTicker) {
            _this.ticker = options.ticker || PIXI.Ticker.shared || PIXI.ticker.shared;
```

Temporarily fixed with `new Viewport({ticker: PIXI.ticker.shared})`

**Comment by davidfig** [comment]
Oops. I need to check that PIXI.Ticker exists before testing it for pixi v5. Fixed in v3.18.1.
