### ISSUE TITLE
Mac scroll gesture acceleration is odd

### ISSUE THREAD

**Issue by wavebeem** [davidfig/pixi-viewport#119]
I noticed that the default zoom handler works great with mouse wheels, but using a Mac touchpad scroll gesture (two finger swipe up/down), the zooming behavior seems a bit laggy or unusual compared to my expectation.

In my own work, I copied the math behind d3-zoom's algorithm, which feels great: https://bl.ocks.org/mbostock/6123708

I'm currently using a custom plugin with a wheel event that combines the best of your wheel plugin and d3's math (nice plugin architecture, btw).

The key portions seem to be a bit of math around the WheelEvent object:

- Convert wheel event to a number: https://github.com/d3/d3-zoom/blob/master/src/zoom.js#L33-L35
- Multiply the current scale by `2^n` (where `n` is the number above)

I'd be happy to help with a PR for it, but I wanted to see first if this is something you'd be interested in at all. I think the current touchpad behavior is a bit odd on Mac, but I also don't have a Windows touchpad to compare with right now, so I could be missing something.

**Comment by davidfig** [comment]
Yes, always happy to accept improvements. I’ve been meaning to take a look at this for a while.
