### ISSUE TITLE
typings and global PIXI variable undefined

### ISSUE THREAD

**Issue by steffennilsen** [davidfig/pixi-viewport#120]
Using pixi 5.0.0 rc 2 and packaging with webpack I get these issues

```
ERROR in node_modules/pixi-viewport/@types/index.d.ts(176,18): error TS2694: Namespace 'PIXI' has no exported member 'PointLike'.
node_modules/pixi-viewport/@types/index.d.ts(178,17): error TS2694: Namespace 'PIXI' has no exported member 'PointLike'.
node_modules/pixi-viewport/@types/index.d.ts(223,16): error TS2694: Namespace 'PIXI' has no exported member 'PointLike'.
node_modules/pixi-viewport/@types/index.d.ts(224,16): error TS2694: Namespace 'PIXI' has no exported member 'PointLike'.
```

After looking trough the pixi 5.0 api it seems like this class i no longer exposed, but according to the typings file `PIXI.Point` is a derivative class and should work fine as a replacement.

```
viewport.js:1542 Uncaught ReferenceError: PIXI is not defined
    at Object../node_modules/pixi-viewport/dist/viewport.js (viewport.js:1542)
```

This one I'm unsure how to solve, it works fine if I run it a small test by just loading scripts directly from the cdn, but fails from my webpack setup

**Comment by davidfig** [comment]
I added an import for PIXI to the types file (and the viewport.js file) in v3.20.0. pixi.js changed the way they export PIXI in v5. This works on my local typescript testbed, but I'm no typescript expert. Let me know if this helps or breaks something else.

**Comment by steffennilsen** [comment]
Almost there, after pulling I still had to change the `PIXI.PointLike` to `PIXI.Point` and it worked

**Comment by davidfig** [comment]
Try 3.21.0. I changed over all the PIXI.PointLike to PIXI.Point. They removed this type in v5 😞

**Comment by steffennilsen** [comment]
Works perfectly now 👍
