### ISSUE TITLE
"PIXI is not defined" error when dragging

### ISSUE THREAD

**Issue by davkyrr** [davidfig/pixi-viewport#122]
I get this error when dragging :

> viewport.js:391 Uncaught ReferenceError: PIXI is not defined
>     at Drag.move (drag.js:103)
>     at Viewport.move (viewport.js:400)
>     at Viewport.emit (index.js:129)
>     at InteractionManager.dispatchEvent (interaction.es.js:1469)
>     at InteractionManager.processPointerMove (interaction.es.js:2036)
>     at InteractionManager.processInteractive (interaction.es.js:1657)
>     at InteractionManager.processInteractive (interaction.es.js:1597)
>     at InteractionManager.onPointerMove (interaction.es.js:1994)

I'm using the latest pixi.js version with react v16

Thanks!

**Comment by davidfig** [comment]
Try the new version: v3.21.1.

**Comment by mheppner** [comment]
That version fixes the issue for me, thanks!

**Comment by davkyrr** [comment]
Yep! Also fixed here thanks @davidfig!
