### ISSUE TITLE
Viewport options.screenWidth/screenHeight not actually defaulted

### ISSUE THREAD

**Issue by chrahunt** [davidfig/pixi-viewport#123]
Per the [docs](https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#Viewport), `screenWidth` and `screenHeight` should be defaulted to `window.innerWidth` and `window.innerHeight` on `Viewport` construction. This appears to only happen in `Viewport.resize()`.

In my case `Viewport.follow()` wasn't working because these were `undefined`. As a workaround they can be provided explicitly in the options or `resize()` may be called before actually doing anything.

**Comment by davidfig** [comment]
Good catch. I fixed it in v3.21.2. Thanks!
