### ISSUE TITLE
[Feature Request] Add option to only allow dragging with right or left mouse button

### ISSUE THREAD

**Issue by chrisella** [davidfig/pixi-viewport#126]
I'd be happy to take a look at this when I get a chance, if it turns out it isn't already implemented and I'm just missing it.
For our use we would ideally be able to only dedicate 1 button to dragging the viewport, so the other button can be used for clicking and moving objects around within the stage.

This may already be supported / catered for and I've missed if, if so please let me know and ditch this request ;)

**Comment by davidfig** [comment]
I added this feature recently upon request. Ugh. The documentation wasn't properly updated. It is now. Check out: https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#drag

Example:
```js
viewport.drag({ mouseButtons: 'right' })
```

It's a relatively new feature so let me know if you have issues.

**Comment by chrisella** [comment]
My appologies, discovered that you've already added this with the mouseButtons prop on the drag options

https://github.com/davidfig/pixi-viewport/issues/116#issuecomment-478402613

**Comment by chrisella** [comment]
Thanks, noticed that at the same time ;) 
I think the thing that threw me is that in 3.23 the types doesn't reflect that, so I wasn't getting any intellisense for it

**Comment by davidfig** [comment]
I also updated the index.d.ts in v3.23.2 with this option. Thanks for catching the missing documentation :)
