### ISSUE TITLE
Locking the viewport to a specific area

### ISSUE THREAD

**Issue by DanForstinger** [davidfig/pixi-viewport#127]
Hey there!
This has been a very useful library. Thanks for making it!
I am rendering a tiled worldmap, and wondering what the best approach is to encapsulate the viewport to within a certain bounds. In this example, i'd like the viewport to only ever show what is on the map and stop scrolling once it hits an edge.

![Capture](https://user-images.githubusercontent.com/10439718/56844602-dcbd3200-6880-11e9-9f3d-abe3ebd37194.PNG)

Is this currently supported by this tool? If not, any advice on approach so I can contribute a PR would be appreciated :)

**Comment by DanForstinger** [comment]
I figured it out using the clamp functions on the viewport. Closing, sorry to bother !

**Comment by Redmega** [comment]
@DanForstinger Can you share how you did it, if you still have that code? It would help others facing the same issue

**Comment by davidfig** [comment]
Checkout this clamp plugin: https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#clamp

This is the simplest use case. It will clamp the viewport to the world coordinates:
```js
const viewport = new Viewport()
viewport.drag().clamp({ direction: all })
```

**Comment by Redmega** [comment]
Thanks @davidfig. I was asking in reference to #180, thought it might be relevant.
