### ISSUE TITLE
Help: When dragging the viewport, clicking position is no longer valid

### ISSUE THREAD

**Issue by ganzf** [davidfig/pixi-viewport#128]
Hello,

I'm using the drag() plugin with pixi-viewport.
When the viewport is initialized and has never been dragged, the value for the event 'mousedown' match my cursor position. Therefore if I draw a sprite at the given position (event.target.last) it works.
However, when i drag the viewport, this value is no longer matching my cursor position, and the sprite is not drawn where my cursor is, but somewhere else on the canvas.

Is the value i'm using the wrong one ? Do i need to convert it to screen mode ? 

Thank you very much for you help :)

**Comment by ganzf** [comment]
Oups, i should have read your live example code and seen that creating object was done with world coordinates and not screen coordinates. Sorry. 

Maybe delete the issue or keep it open for other people.

Have a nice day :)

**Comment by ganzf** [comment]
Ok i'm sorry but I just stumbled upon another related issue.
Since there is no "released" or "mouseup" event that gives me access to data.world or data.screen, how can I detect mouse world position on mouseup event ?

Thanks !

**Comment by davidfig** [comment]
Listen for the 'drag-end' event. It provides { screen, world } coordinates. The code looks like this:
```js
viewport
   .drag()
   .on('drag-end', (screen, word) => console.log(screen, world))
```
Here are the docs: https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#event:drag-end

**Comment by ganzf** [comment]
Hello, 

This event fires when the viewport drag ends, which makes sense. However, i'm simply looking for a mouseup event in the viewport, on the left or right click, even if the viewport cannot be dragged.

```
        this.view.on('drag-end', (screen, world) => {
            console.log('Drag End at ', screen, world);
            this.menu.openAt(world);
        });
```

Should I add an event listener to the container ?

**Comment by davidfig** [comment]
Use 'pointerup' event on the viewport and use event.data.global with viewport.toLocal(). I haven't tested it but it should get you close to what you're looking for.
