### ISSUE TITLE
Scroll zoom still occurs through over-layed elements

### ISSUE THREAD

**Issue by chrisella** [davidfig/pixi-viewport#130]
I have a PIXI canvas that takes up the whole page which has a viewport on it and everything is working great. We're looking at adding an overlay chat window on top of the canvas in the bottom corner which is just a absolute positioned Div with bits inside it, but am having issues where trying to scroll the chat (which is just a div with overflow: scroll) it causes the map behind it to scroll.

Because the scroll is just the native div overflow scroll, I can't stopPropogation in the chat overlay itself, so am hoping there is a way to stop this behaviour in the viewport.

I've already experimented with the divWheel property with no success.

If you need any more details or want me to try and suggestions I'm more than happy to help.

**Comment by chrisella** [comment]
I've tested the concept of what I believe is happening in a codepen.
I believe the Viewport code hooks up with addEventListener('wheel',...) to the divWheel element which is mimicked by the red background div here then infront is a sibling element positioned absolutely over it which is natively scrollable. In this demo however it all works as I'd expect, the scroll of the text in the overflow:scroll div works without triggering the scroll handler on the item behind.
https://codepen.io/anon/pen/JqPVxK?editors=1011#0

**Comment by chrisella** [comment]
For reference also, this is what it looks like actually in our real scenario that's causing problems:
![image](https://user-images.githubusercontent.com/1069324/57182600-d6d6da80-6e98-11e9-88d9-6f951d50338c.png)

**Comment by chrisella** [comment]
I discovered the problem in the end, due to a timing issue in React, the divWheel was undefined and it looks like the events are attached to the body in that case. Changing bits up and making sure the divWheel is never undefined has solved this for me.

**Comment by Lundbyit** [comment]
> I discovered the problem in the end, due to a timing issue in React, the divWheel was undefined and it looks like the events are attached to the body in that case. Changing bits up and making sure the divWheel is never undefined has solved this for me.

Hi Chrisella!

I got the same problem. But I can't figure out how to fix it. Can you point me in the right direction?

Regards

**Comment by davidfig** [comment]
Did you try to set the divWheel to your PIXI.renderer.view? You set it when you create the viewport:
```js
new Viewport({ divWheel: renderer.view })
```

**Comment by Lundbyit** [comment]
Thanks for getting back to me davidfig.

It worked.

Thanks!

**Comment by Lundbyit** [comment]
Thanks for getting back to me davidfig.

It worked.

Thanks!
