### ISSUE TITLE
How to make a scrollbox based on this lib?

### ISSUE THREAD

**Issue by abellee** [davidfig/pixi-viewport#132]
I'm using TypeScript, but the pixi-scrollbox not support.
so I wanna do it myself based on this lib,
and can you tell me how to do it?
just scroll vertically that's all I need.
Thanks in advanced!

**Comment by abellee** [comment]
I have found the solution with `drag({direction: "y"})`,
but how can I set the scroll range of the viewport?
just like the scrollbox, I need to stop the scrolling when the y of the view is larger than 0.

**Comment by abellee** [comment]
finally, I figure it out.
just set the `drag({direction: "y"})` and set the `worldWidth` to the `screenWidth` and the `worldHeight` to the real height of the content

**Comment by davidfig** [comment]
You can also try pixi-scrollbox which is based on this library. It has a built in scrollbar and masking.

**Comment by abellee** [comment]
@davidfig I'm so grad to use it if it can support TypeScript.
