### ISSUE TITLE
How to use pixi-viewport with a custom bundle of pixi.js

### ISSUE THREAD

**Issue by federicovezzoli** [davidfig/pixi-viewport#133]
To make pixi.js a little more lightweight I'm using this tool: https://pixijs.io/customize/ to create a custom bundle with only the packages I need.

But when I'm using it with pixi-viewport:
`const Viewport = require('pixi-viewport');`
It tells me that pixi viewport cannot find pixi.

Anyone can help?
thanks

**Comment by davidfig** [comment]
How are you including pixi-viewport? The viewport looks for a window.PIXI element if you're using the pregenerated pixi-viewport.min.js file. 

You may also want to look into parcel, rollup, or webpack if you're looking to prune your dependencies. It's easier than repackaging libraries.

**Comment by federicovezzoli** [comment]
I'm including pixi-viewport with npm.

I'm using it within a nuxt app.

Can't find a way to make it work easily.

**Comment by davidfig** [comment]
You may want to add pixi.js through npm as well then. You could use the version in bundle/pixi-viewport.min.js, but since it includes it's own pixi.js build, it defeats your purpose of pruning your external libraries.

**Comment by federicovezzoli** [comment]
Yes that's what I'm avoiding, to import all pixi. Using the this tool ( https://pixijs.io/customize/) I can import with npm only the packages I need, but then pixi-viewport fails to see pixi.

I'll stay with the full pixi package for now. thanks.

**Comment by davidfig** [comment]
I released v4.0.0-beta.0. I switched the project over to rollup, which allows me to create various types of releases, including ones without pixi.js packaged. The latest build is on npm and I added it to github releases at https://github.com/davidfig/pixi-viewport/releases/tag/4.0.0-beta.0

Hopefully this helps!
