### ISSUE TITLE
update github release

### ISSUE THREAD

**Issue by HubertD** [davidfig/pixi-viewport#134]
it would be great if there were more recent releases (latest is 3.4.1) on the github page.

alternatively, some documentation on how to create such a pixi-viewport.js (not including pixi.js itself) would be awesome.

as someone who isn't into this whole packaging stuff, i already spent hours on trying to build a current pixi-viewport plugin. as for now, I give up and just use 3.4.1

**Comment by davidfig** [comment]
Sorry about that. I'm not great at updating the github releases. The latest version is always in the bundle/ directory. I'll try to find a way to automate it when I publish.

**Comment by HubertD** [comment]
No need to feel sorry, thank you for your excellent work!

The files in bundle/ though are 1.4MB uncompressed, including the whole pixi.js.

Your releases, however, were exactly what I need, just pixi-viewport, compatible with different versions of pixi.js. And I did not find out how to create these.

**Comment by FD-** [comment]
It wouldn't be an issue if there were build instructions in the readme. I'm not familiar with Typescript, and even some Google research didn't tell me how to make sense of that @types folder. Your library is great, but I'd appreciate it if a recent release build existed.

**Comment by davidfig** [comment]
Thanks for the feedback. I've been working on a next version that does a better job packaging (I switched to rollup from browserify). A beta version should be ready soon. The v5 release of pixi.js broke how the library worked in its standalone form. Hopefully this new version will work for both v4 and v5.

In the meantime, the current version works fine installed with npm or yarn and bundled up. That's how I use it.

**Comment by davidfig** [comment]
I released v4.0.0-beta.0. I switched the project over to rollup, which allows me to create various types of releases, including ones without pixi.js packaged. The latest build is on npm and I added it to github releases at https://github.com/davidfig/pixi-viewport/releases/tag/4.0.0-beta.0

Hopefully this helps!

**Comment by MRVDH** [comment]
Using 4.0.0-beta.0 and PIXI 5.0.4 I can't use `new PIXI.extras.Viewport` because I get a `TypeError: new PIXI.extras.Viewport is not a constructor`. How do I call the constructor? I also tried `new Viewport` and `new PIXI.Viewport` but they all give the 'not a constructor' error.

**Comment by davidfig** [comment]
Try new Viewport()

**Comment by MRVDH** [comment]
Doesn't work, you can experiment in the playground link
