### ISSUE TITLE
Follow and Zoom brokes the size of the map and target disappears

### ISSUE THREAD

**Issue by DinoMah** [davidfig/pixi-viewport#135]
When I zoom at a percent and use follow to a target it disappears from the stage and bounds are not well calculated making the map bigger than it should be and the map showing as it is.

**Comment by davidfig** [comment]
Please provide code showing the problem. I need the viewport initialization options, and what plugins you're using.

**Comment by DinoMah** [comment]
`
var viewport = new PIXI.extras.Viewport({
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    worldWidth: 608,
    worldHeight: 608,
    interaction: app.renderer.plugins.interaction //I don't know if I need it for my purpose
});
//I add childs to the viewport and then follow the target
viewport.addChild(playerSprite);
viewport.follow(playerSprite);
viewport.zoomPercent(4);
`
