### ISSUE TITLE
Cannot add property extras, object is not extensible

### ISSUE THREAD

**Issue by dontwork** [davidfig/pixi-viewport#138]
on this line:
`PIXI.extras = { Viewport: Viewport };`

i get this error:
`Uncaught TypeError: Cannot add property extras, object is not extensible`

no further stacktrace and my code is straight from the docs. Im using latest version of pixi and viewport

**Comment by dontwork** [comment]
I wonder if its connect to this snippet from the pixi.js source

```
    /**
     * This namespace has been removed. All classes previous nested
     * under this namespace have been moved to the top-level `PIXI` object.
     * @namespace PIXI.extras
     * @deprecated since 5.0.0
     */
    PIXI.extras = {};
```

**Comment by davidfig** [comment]
I've been trying to find the best way to bridge between pixi.js v4 and v5. I obviously have not hit on it yet. I'll try to update it with a better method.
