### ISSUE TITLE
Typescript definitions not in node_modules

### ISSUE THREAD

**Issue by Cooke** [davidfig/pixi-viewport#139]
Thanks for cool plugin. The typings seems to be missing in the node modules.

**Comment by davidfig** [comment]
Which version? The types seem to be declared properly in package.json:

```"types": "@types/index.d.ts",```

**Comment by Cooke** [comment]
@davidfig last version. The files are not present on my disk after yarn install.

**Comment by davidfig** [comment]
v4.0.0-beta.1 should fix the problem.

I moved from .npmignore to files in package.json and forgot to include the @types directory.
