### ISSUE TITLE
graphicsData.shape.points for a Polygon is incorrect with rotation

### ISSUE THREAD

**Issue by MRVDH** [davidfig/pixi-viewport#141]
I expect the points list to be updated to the actual new points when rotation is added, rather than displaying the original coordinates.

https://www.pixiplayground.com/#/edit/Z84EH8JbUCNh0ZOpVJIEK

- **`pixi.js` version**: _4.8.7_
- **`pixi-viewport.js` version**: 4.0.0-beta.0
- **Browser & Version**: _Brave 0.65.120 (Chromium: 75.0.3770.90)_
- **OS & Version**: _Windows 10_

**Comment by davidfig** [comment]
This should be in pixi.js issues

**Comment by MRVDH** [comment]
I see now, sorry! :)
