### ISSUE TITLE
Cannot call Viewport constructor in pixi 5

### ISSUE THREAD

**Issue by MRVDH** [davidfig/pixi-viewport#142]
Uncaught TypeError: PIXI.extras.Viewport is not a constructor

https://www.pixiplayground.com/#/edit/47~W4JKeToE8KP34Z6YeP

- **`pixi.js` version**: _5.0.4_
- **`pixi-viewport.js` version**: 4.0.0-beta.0
- **Browser & Version**: _Brave 0.65.120 (Chromium: 75.0.3770.90)_
- **OS & Version**: _Windows 10_

**Comment by davidfig** [comment]
The new build system doesn't export a default. Try: 
```
new Viewport.Viewport()
```

**Comment by MRVDH** [comment]
Works, thanks!
ps. Should be updated in the docs right?

**Comment by MRVDH** [comment]
Now I'm getting a `viewport.pausePlugin is not a function`. I execute this on a click.

**Comment by davidfig** [comment]
I'm updating the documentation now. Plugins have moved to their own object. Use:
```js
viewport.plugins.pause('drag')
```

I should have the new docs and migration guide up soon.
