### ISSUE TITLE
how to use the SnapZoomOptionsoptions

### ISSUE THREAD

**Issue by jjhesk** [davidfig/pixi-viewport#148]
I have read to the location https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#snapZoom

what is the detail for this `SnapZoomOptionsoptions`?

**Comment by davidfig** [comment]
fixed the link. Should work now: https://davidfig.github.io/pixi-viewport/jsdoc/global.html#SnapZoomOptions
