### ISSUE TITLE
Multiple viewports in same region respond to mousewheel, even if hidden

### ISSUE THREAD

**Issue by connorjclark** [davidfig/pixi-viewport#150]
I have a tabbed container component that shows only the current selected tab. Each tab has a Scrollbar / Viewport. Even when just one viewport is visible, all viewports are moved.

https://github.com/davidfig/pixi-viewport/blob/d4a2ea9fa5fc90e54e1b8098eb0fb90de947123c/src/input-manager.js#L205

At first glance, I couldn't find anything in the PIXI api to check "is this display object visible". `.visible` doesn't work. If you had a reference to the root stage, you could walk up the parents and see that the root is the stage... I don't have any better ideas.

![bugreport](https://user-images.githubusercontent.com/4071474/61179931-53391880-a5c2-11e9-9111-403bf4069174.gif)

Only one of these viewports are rendered at any one time - you can verify that in the code below.

Usage: https://github.com/connorjclark/gridia-2019-wip/blob/master/src/client/modules/admin-module.ts#L91

**Comment by davidfig** [comment]
For now, pause the hidden viewports. Pixi.js does not provide a wheel event so it doesn't currently check the visible setting unlike the other pixi events. I'll make the change when I get back to my computer.

**Comment by connorjclark** [comment]
> For now, pause the hidden viewports.

Confirming that this works well, thanks!

**Comment by davidfig** [comment]
Hmm...I checked the wheel code and it looks like the wheel should be deactivated when the viewport.visible=false. Can you check if this is not working as expected? Here's the wheel code:

```js
    handleWheel(event)
    {
        if (this.viewport.pause || !this.viewport.worldVisible)
        {
            return
        }
...
```

**Comment by connorjclark** [comment]
AFAIK, `visible = true` does not mean that the display object is actually visible on the screen, or even in the render tree. See:

![image](https://user-images.githubusercontent.com/4071474/61190811-0eab8c80-a657-11e9-8025-151855156a44.png)

**Comment by davidfig** [comment]
Ah. pixi.js is not smart. It will render everything regardless if it covered up by other objects or even way off the visible screen. You need to manually set visible=false on your non-visible containers when they're covered up. The viewports will automatically pause itself and no events will happen. Hope that makes sense.

**Comment by connorjclark** [comment]
Yup - I feel like PIXI.js's scope wouldn't entertain fixing this, and there's nothing to be done from this side of things, so feel free to close this issue. The workaround of manually setting visibility / pausing is good enough for me.

Thanks for the nice component :)

**Comment by davidfig** [comment]
Surely. pixi.js has had this conversation a bunch. It's outside their scope to deal with culling since it's very project specific. (I agree with this, as I've written many different culling algorithms for my various apps.) Good luck with your project!
