### ISSUE TITLE
Viewport mouseEdge distance property is based on window.innerHeight / innerWidth

### ISSUE THREAD

**Issue by nanark** [davidfig/pixi-viewport#151]
Better be based on viewport width and height.
In this case (with the 50px black header):
<img width="1394" alt="Screenshot 2019-07-20 at 08 45 58" src="https://user-images.githubusercontent.com/581768/61575371-278ac680-aacb-11e9-82b4-8e7bbc7652e7.png">

I have to add 50px to the bottom value otherwise the mouseEdge bottom detection is below the screen.

**Comment by nanark** [comment]
Also in this case, when the mouse leaves the viewport from the top, the plugin does not detect the mouseout event, scrolling keeps going.

**Comment by davidfig** [comment]
Thanks, that's a much better approach. I updated the code using the parent's world-screen size in 4.1.0.

**Comment by nanark** [comment]
Great! Thanks for this amazing lib 👍
