### ISSUE TITLE
minSpeed not working in decelerate plugin

### ISSUE THREAD

**Issue by Kikedao** [davidfig/pixi-viewport#154]
At decelerate.js 'minSpeed' is called as 'this.minSpeed' but the variable doesn't exist, so its value is undefined when the value is checked in the update() function, and therefore not working making the viewport never stop moving and therefore always dirty.

Changing 'this.minSpeed' to 'this.options.minSpeed' on line 140 and 150 should fix the problem.

**Comment by davidfig** [comment]
Yes, thanks. I missed this when I changed how options worked in plugins. Updated in v4.1.4.

**Comment by Kikedao** [comment]
I'm also using pixi-cull, and that issue was making the viewport always 'dirty' when it was moved, preventing optimization, that's how I noticed the problem.

For any future reader, I can't stress this enough how good and robust pixi-culling is too, specially in combination with pixi-viewport.

Thanks to you David, and thanks to your awesome work.
