### ISSUE TITLE
How to remain centered on followed object WITHOUT going out of bounds?

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [davidfig/pixi-viewport#158]
So I have the viewport centered on the player.  But when the player reaches the edge of the game world, the black void comes into view.  How do I stop the viewport from doing that?  I need to basically keep it centered on the player UNLESS the player is too close to the edge of the map.

**Comment by davidfig** [comment]
Use viewport.clamp() to stop the viewport from moving beyond your boundaries.

**Comment by MelerEcckmanLawler** [comment]
Thanks!
