### ISSUE TITLE
Bug at Snap Zoom plugin in last version

### ISSUE THREAD

**Issue by soylomass** [davidfig/pixi-viewport#166]
if (this.options.width > 0)
        {
            this.x_scale = this.parent._screenWidth / this.options.width;
        }
        if (this.options.height > 0)
        {
            this.y_scale = this.parent._screenHeight / this.options.height;
        }

this.parent._screenWidth and this.parent._screenHeight are always undefined, and not referenced anywhere else in the project. Removing the underscore fixes the problem.

**Comment by davidfig** [comment]
Thanks. Should be all fixed now.
