### ISSUE TITLE
SnapZoom() animated move

### ISSUE THREAD

**Issue by lovrev** [davidfig/pixi-viewport#169]
Hi,
is it possible to have a smooth move when calling snapZoom()?
Right now it jumps straight to the center and does a smooth zoom. Is is possible to somehow make the move smooth? 

I call snapZoom with the following options:
```
      center: new Pixi.Point(someX, someY),
      height: someValue,
      removeOnComplete: true,
      removeOnInterrupt: true,
      time: 250,
      forceStart: true
```

Thanks a lot!

**Comment by davidfig** [comment]
have you tried it in combination with snap()? leave center as undefined in snapZoom

**Comment by lovrev** [comment]
Thank you for your response.
Emitting the center did the trick. I tried using both plugins previously but didn't try removing the center.

What would be nice though, is to have the zoom and move happen simultaneously like on Google Maps. Do you think this is achievable with the right options and usage or will I need to modify the source? 

Best regards

**Comment by davidfig** [comment]
What do you mean by simultaneous? Don't the two plugins work together and if you set the time correctly, it should end at the same time.

**Comment by lovrev** [comment]
Unfortunately not. Regardless if I call snap first or snapZoom first, it will always zoom first and then move. I have the time set to the same value in both.

```
    this.viewport
      .snap(someX, someY, {
        removeOnComplete: true,
        removeOnInterrupt: true,
        time: 2000,
      })
      .snapZoom({
        height: someValue,
        removeOnComplete: true,
        removeOnInterrupt: true,
        time: 2000,
      });
```

I have recorded a quick demo to show you the behavior:
![2019-10-29 11-13-30](https://user-images.githubusercontent.com/16166221/67758488-10e6fa80-fa3e-11e9-8daf-e925922f8375.gif)

**Comment by davidfig** [comment]
Hmm...I think it's working properly. If you watch the values (viewport.scale.x and viewport.center.x/y), you'll see that they properly change along with the requested ease. The movement looks faster at the end because it is: moving while zoomed in appears faster than moving while zoomed out because each world pixel is larger. But the values are correct. 

What effect are you trying to get? You can try to ease the movement/zoom differently so the movement happens earlier and the it looks better aesthetically.

**Comment by lovrev** [comment]
You are right. It's behaving correctly.

I've managed to get my desired effect by using `EaseInQuad` on one plugin and `EaseOutQuad` on the other. It's not 100% perfect, but it's very good! 

Thanks for your help, much appreciated!
