### ISSUE TITLE
Release 4.3.5 broke snapZoom()

### ISSUE THREAD

**Issue by mzinner** [davidfig/pixi-viewport#174]
Hi, 

thanks a ton for this essential Pixi.js library! 

When upgrading from 4.3.1 to 4.3.5/4.4.0 I noticed that the chaining of viewport.snapZoom().snap() does not result in parallel execution anymore (at least visually).

- Timing of snapZoom() seems to be totally off, the time parameter doesn't seem to be using ms anymore
- snapZoom() does not trigger the "moved" event anymore, so viewport.on('moved', () => {}) has no effect anymore.

This breaks animations that looked smooth before.

```
viewport.snapZoom({
                    width: width,
                    removeOnComplete: true,
                    removeOnInterrupt: true,
                    time: 1000
                }).snap(projectedCoords[0], projectedCoords[1], {
                    removeOnComplete: true,
                    removeOnInterrupt: true,
                    time: 1000,
                    forceStart: true
                });
```

Example:
- The original behaviour of 4.3.1:
![ScreenRecording 4 3 1](https://user-images.githubusercontent.com/37372663/69260070-8ff3cc80-0bbf-11ea-91b6-5821619034c3.gif)

- The messed up behaviour of 4.3.5/4.4.0:
![ScreenRecording 4 4 0](https://user-images.githubusercontent.com/37372663/69260071-8ff3cc80-0bbf-11ea-9f9e-bc5e2806b42d.gif)

Please advice if my code needs to be updated for 4.3.5+ or if this is simply a bug introduced in 4.3.5.

Much appreciated!

Thanks,
Mike

**Comment by davidfig** [comment]
I tracked down the issue. It relates to some code clean up relates to `plugins.reset()` that released in the last version. snapZoom will turn reset (ie, turn off) the plugin whenever center is moved (which happens every frame to keep the zoom centered). Not sure why this is called but I'm working on a fix.

**Comment by davidfig** [comment]
v4.4.1 should fix it. let me know if you have any other issues.

**Comment by mzinner** [comment]
Hi David,

amazing respond time! Yes, v4.4.1 fixes the issue. How to buy you coffee?

Thanks,
Mike
