### ISSUE TITLE
toWorld and toScreen don't work

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [davidfig/pixi-viewport#175]
`console.log(g.viewPort.toWorld(new PIXI.Point(100, 100)))` just outputs `Point (x: 100, y: 100)`

Same for `toScreen`.

I know the viewport is working because I can drag it around and zoom with the mouse wheel, so why aren't the coordination transformations working?

`
g.viewPort = new Viewport.Viewport({
          screenWidth: window.innerWidth,
          screenHeight: window.innerHeight,
          worldWidth: g.bg.width,
          worldHeight: g.bg.height,
          interaction: app.renderer.plugins.interaction
        })
`

**Comment by davidfig** [comment]
What values do you get back when you call toScreen and toWorld? Is you worldWidth/worldHeight properly set?

**Comment by MelerEcckmanLawler** [comment]
Since I posted this they seem to be working but I don't need them anymore.  Good stuff though I am still using the viewport.

**Comment by davidfig** [comment]
Yup, adding to the stage above the viewport is the way to go for UI and non-viewport stuff
