### ISSUE TITLE
Stop viewport moving after drag or scroll

### ISSUE THREAD

**Issue by SirFishy** [davidfig/pixi-viewport#181]
After dragging or zooming the viewport, it continues moving until it eventually comes to a stop. Is there a way to toggle this off? 

I'd like to have more precision with the drag / zoom so that when I stop dragging or when I stop sending scroll inputs, the viewport stops moving.

Thanks!

**Comment by embeddedt** [comment]
I never added the `decelerate` plugin to my game, and I don't see this behavior. Maybe removing the `decelerate` plugin would do what you want?

**Comment by SirFishy** [comment]
Part of my problem was using a track pad for the zoom. Using a conventional mouse, the zoom is fine.

The drag still seems to have deceleration even if I don't have the `decelerate` plugin.

https://davidfig.github.io/pixi-viewport/

The live example also seems to behave this way as well.

**Comment by embeddedt** [comment]
I tried it again and within my app, if I enable the `decelerate` plugin, I get the behavior in the demo. If I disable it, it goes back to not having any inertial effects (stops instantly when I release the mouse).

Perhaps there's something different in the way we initialize the viewport? Here's the gist of what I do in my setup code.

```js
       this.viewport = new Viewport({
            screenWidth: TileSystem.app.view.clientWidth,
            screenHeight: TileSystem.app.view.clientHeight,
            worldWidth: 1000,
            worldHeight: 1000,

            interaction: TileSystem.app.renderer.plugins.interaction // the interaction module is important for wheel to work properly when renderer.view is placed or scaled
        });
        this.viewport.zIndex = 1000;

        // add the viewport to the stage
        TileSystem.app.stage.addChild(this.viewport);
        TileSystem.app.renderer.plugins.interaction.moveWhenInside = true;
        TileSystem.rootObject = this.viewport;
```

**Comment by davidfig** [comment]
Have you tried it using a different mouse? There may be something going on in the mouse driver/OS that results in multiple events. 

There are a bunch of places where the viewport has a deceleration, including the `decelerate` plugin and the `wheel` plugin (which includes a smooth zoom effect). But those need to be explicitly turned on. The code above is not doing that. It should stop and start as soon as the events end.

Let me know if you figure it out and there's something that needs to be fixed in the viewport.

**Comment by SirFishy** [comment]
I think everything checked out. I'm not sure why, but I thought I had tried removing the `.decelerate()` call and still saw the window sliding. 

Now, when I remove the call, the viewport behaves as expected.

Either way, this seems to be user error :). Thanks @embeddedt and @davidfig for your help!
