### ISSUE TITLE
PointerMoveEvent causes TypeError

### ISSUE THREAD

**Issue by int0x81** [davidfig/pixi-viewport#184]
I have this simple code that gives me infinite amounts of errors while moving the pointer over the app. If I replace viewport by a different, new created `PIXI.DisplayObject` the app works fine.

The error message:
![callstack](https://user-images.githubusercontent.com/26823828/71262401-dd3e9780-233f-11ea-8c70-1f66e67c0909.JPG)

My code:
```
this.renderer = new PIXI.Renderer({
            width: divElement.clientWidth, 
            height: divElement.clientHeight,
            transparent: true, 
            resolution: window.devicePixelRatio, 
            autoDensity: true,
            antialias: true
});
divElement.appendChild(this.renderer.view);

this.viewport = new Viewport({
            screenWidth: window.innerWidth,
            screenHeight: window.innerHeight, 
            worldWidth: divElement.clientWidth, 
            worldHeight: divElement.clientHeight,
            divWheel: divElement,
            interaction: this.renderer.plugins.interaction
});

this.viewport
.drag({
        wheel: false
})
.wheel({
        percent: 0.1,
        smooth: 5,
});
        
this.ticker.add(() => this.renderer.render(this.viewport));
this.ticker.start();

```
I'm using:
typescript@**3.7.3**
pixi.js@**5.2.0**
pixi-viewport@**4.3.3**

**Comment by davidfig** [comment]
Have you tried upgrade pixi-viewport?

**Comment by int0x81** [comment]
the bug was not related to pixi-viewport. It was a [known bug](https://github.com/pixijs/pixi.js/issues/6171) of pixi in combination with webpack. Deleting package-lock.json and node_modules fixxed the problem.
Sorry for the inconvenience and thank you for maintaining this library :)
