### ISSUE TITLE
Error performing a snap-zoom and snap simultaneously

### ISSUE THREAD

**Issue by qwertysam** [davidfig/pixi-viewport#19]
When *snap-zoom* is running and `options.center = false` for *snap* the viewport misbehaves because it requires an Ease.to(...) object to have constantly updating inputs in order for *snap* to properly calculate the top left corner (this is because *snap-zoom* is constantly changing the scale of the viewport).

A possible but hacky solution is to "look ahead" to the final values of the *snap-zoom* plugin and use that x and y scale when calculating the targetX and targetY inputs of the Ease.to(...) object in the *snap* function.

**Comment by davidfig** [comment]
Should be fixed in latest build.
