### ISSUE TITLE
The moveCenter function don't work as expected when setting non default resolution

### ISSUE THREAD

**Issue by vimcaw** [davidfig/pixi-viewport#190]
Code Sandbox Demo: https://codesandbox.io/s/muddy-sun-mg9wn?fontsize=14&hidenavigation=1&theme=dark

There are a red box and a blue point at (0, 0) position, moreover, a button at the bottom to move to the center.

If I don't set the resolution, or set the resolution to 1, it works fine.

![image](https://user-images.githubusercontent.com/21964227/71883117-aefaed80-3170-11ea-8761-668d5cb79de5.png)

But when I set the resolution to other values (e.g. 2), it moves to a strange position.

```js
const app = new PIXI.Application({
  resizeTo: document.body,
  autoDensity: true,
  resolution: 2
});
```

![image](https://user-images.githubusercontent.com/21964227/71882684-e4eba200-316f-11ea-8b43-9d352028ac12.png)

**Comment by davidfig** [comment]
Looks like your screenWidth and screenHeight are wrong. Try changing:

```
  screenWidth: app.view.offsetWidth,
  screenHeight: app.view.offsetHeight,
```

**Comment by vimcaw** [comment]
@davidfig Yes, indeed! Thank you for helping!
