### ISSUE TITLE
Cursor movement [help]

### ISSUE THREAD

**Issue by nikitapilgrim** [davidfig/pixi-viewport#191]
Sorry, I'm only trying myself in game development using pixi.js. The question arose, how can I implement the viewport movement behind the mouse?
I tried using the method moveCorner({x, y}); this is the right strategy?
either i need to create a cursor as a pixy object and use method  .follow ?
please tell me the right way
I'm trying to implement parallax with a custom cursor where the viewport will move behind the mouse cursor

**Comment by davidfig** [comment]
`moveCenter` is usually better since it allows for different sized viewports. How are you calculating the amount of movement?

**Comment by nikitapilgrim** [comment]
if (x !== state.x || y !== state.y) {
            const lerp = easing(delta);
            const newX = state.x + (x - state.x) * lerp * delta;
            const newY = state.y += (y - state.y) * lerp * delta;
            dispatch({type: 'xy', xy: {x: newX, y: newY}});
        }

**Comment by davidfig** [comment]
And x and y are the cursor position?

**Comment by nikitapilgrim** [comment]
yes, state.x previous state

**Comment by nikitapilgrim** [comment]
x current position

**Comment by nikitapilgrim** [comment]
<img width="614" alt="Снимок экрана 2020-01-12 в 16 40 30" src="https://user-images.githubusercontent.com/49089372/72216934-535aa680-355a-11ea-9f22-e31558e1b051.png">

**Comment by davidfig** [comment]
Hmm...that should work. You can also use `viewport.follow()`. It has speed and acceleration options. You can keep calling it with the updated mouse coordinates and it'll recalculate as needed.

It uses moveCenter, so if you want to keep the cursor in the center of the screen, you'll have to offset the value you pass by the difference between the center of the screen and the cursor position on the screen. You can use `viewport.center` to get the center of world, a `viewport.toWorld(cursorX, cursorY)` to get the cursor position in world coordinates.

**Comment by nikitapilgrim** [comment]
Thank you very mutch!
