### ISSUE TITLE
How does this plugin move the "camera"?

### ISSUE THREAD

**Issue by UltraCakeBakery** [davidfig/pixi-viewport#193]
Hi,

I want to use this plugin for one of my pixi projects but i'm worried about what this plugin does to the stage.

In the documentation you add the viewport as a child to the stage.
How does it interact with pixi resulting in movement?

Did you actually make a camera that moves around in the stage?
Does it render the stage twice now?

**Comment by davidfig** [comment]
The viewport is a pixi container that through its methods allows you to change the position and scale. You add children to the viewport that are changed based on the viewport's movement. 

So if you enable drag, the corporate changes it's position based on a user drag. Similarly if you enable pinch, the viewport changes it's scale based on a user's pinch. 

There are also methods that's allow you to programmatically move the viewport or have it follow a pixi object.

**Comment by UltraCakeBakery** [comment]
Ahh okay. Thank you for explaining.

Is there any specific reason that in the documentation you add viewport as a child to the stage instead as making it the stage itself?

**Comment by davidfig** [comment]
If you use PIXI.Application, then the application.stage is automatically rendered on every frame. For that to work, you `stage.addChild(viewport)`. If you use PIXI.Renderer, then you can call `renderer.render(viewport)`. You can render any DisplayObject, including the pixi-viewport. It's rare that I don't have something (like UI) over the viewport, so I rarely render just the viewport. I usually add the viewport to a stage and then render the stage.
