### ISSUE TITLE
the sprites looks pixelated when zoom out.

### ISSUE THREAD

**Issue by LituOffi** [davidfig/pixi-viewport#194]
Hi ! Is there a way to lock the resolution or something because when i unzoom it gets very weird. 
![Sans titre2](https://user-images.githubusercontent.com/58910604/72449386-dbd68280-37b8-11ea-8846-7aee7c540e9d.png)
![Sans titre](https://user-images.githubusercontent.com/58910604/72449387-dbd68280-37b8-11ea-9e0b-65d7f6119f85.png)

**Comment by davidfig** [comment]
Did you set pixi's resolution properly?
```js
const app = new PIXI.Application({ resolution: window.devicePixelRatio })
```

**Comment by LituOffi** [comment]
Hi, i had ''resolution: 1'' and when i put ''resolution: window.devicePixelRatio'' i have the exactly same problem. 
![Sans titre](https://user-images.githubusercontent.com/58910604/72548077-41e10980-388e-11ea-9909-8416741ebe00.png)

**Comment by davidfig** [comment]
Hmm...are you sure you're zooming the viewport and not the screen? Leave full screen and check the zoom level of the browser.

**Comment by LituOffi** [comment]
no i am sure

**Comment by LituOffi** [comment]
actually no.
![mdr](https://user-images.githubusercontent.com/58910604/72637811-63abc080-3962-11ea-8405-7c8555f20313.gif)

**Comment by LituOffi** [comment]
I think it from a weird mimaping can you show me the steps to disable it?

**Comment by davidfig** [comment]
Hmm...maybe try turning antialiasing on? 

`new PIXI.Renderer({ antialias: true })`

Also, are you applying any filters?

**Comment by LituOffi** [comment]
Hi ! i found the issue, i need to unable mipmap on text. So it is not related to pixi viewport. Hvae a nice day ;).
