### ISSUE TITLE
Prevent browser page zoom on pinch

### ISSUE THREAD

**Issue by jasonsturges** [davidfig/pixi-viewport#196]
Hi, is there a known solution to prevent the browser from scaling on pinch zoom gestures?

In Chrome desktop , pinch zoom resizes the entire page despite focus on Pixi app:
![pinch](https://user-images.githubusercontent.com/1213591/73383526-1cd99700-428f-11ea-8de1-bbf9221a1ad1.gif)

Works great on mobile Safari.

**Comment by davidfig** [comment]
That is weird. I don't see that behavior. pixi is calling `event.preventDefault()` (see https://www.html5gamedevs.com/topic/27904-does-event-object-passed-on-containers-mousemovemousedowntouchstart-use-preventdefault-by-default/) by default. Did you change the `autoPreventDefault` setting in pixi?

**Comment by jasonsturges** [comment]
@davidfig Really appreciate the feedback here.

Definitely an issue with Pixi itself, and nothing to do with Pixi Viewport - thanks for the insights.

This gives me some ideas to followup.
