### ISSUE TITLE
prevent drag when drag a child component

### ISSUE THREAD

**Issue by RV1989** [davidfig/pixi-viewport#198]
my child components have drag functionality. How can I block the viewport drag when dragging a child? now both activates

**Comment by davidfig** [comment]
You need to call `event.stopPropagation` to avoid the viewport drag on the `pointerdown` event that starts your rag. That should work as pixi (I think) goes from child to parent when propagating the pointer event. 

Alternatively (but not as good), you can turn off the drag by pausing the drag plugin: `viewport.plugins.pause('drag')` when starting the drag from your child, and `viewport.plugins.resume('drag')` when done.

**Comment by fakob** [comment]
Just a clarification for noobies like me. I made the mistake of forgetting the parentheses :-)
The method to call is `event.stopPropagation()`.
