### ISSUE TITLE
Zoom/Pan Performance with 'react-pixi'

### ISSUE THREAD

**Issue by ygorlf** [davidfig/pixi-viewport#205]
Hi, I'm using the viewport with react-pixi, the zoom and pan works great, but after some time I see a drop of performance with a simple drag implementation on my component, At first without any zoom/pan the squares drag very smoothly but after zoom or pan they really fall behind the cursor move, even with the FPS at 60, there's any kind of 'cache' or something that could be done on pixi-viewport side?

demo:
https://codesandbox.io/s/small-firefly-3hdt8
https://github.com/ygorlf/pixi-stress

**Comment by davidfig** [comment]
Hmm...I haven't seen a drop in performance after running it for a while. The viewport isn't doing much except changing the position/scale of a container. The only time it stores any real data is in the decelerate plugin, but that should be cleared when you release the drag.

If the FPS is at 60, how is the viewport falling behind? Any other code running that could impact performance? Maybe something that happens every frame either in your update loop or in your input event handler?

**Comment by ygorlf** [comment]
Hi, I'm trying to wrap my head around the concepts of pixijs, when you say input event handler and update loop, it's some internal working of pixijs?

The viewport works great, my initial taught was that some work on scaling/move of the viewport is causing that, I'll try to dig deeper on the code and see if I can improve my drag code

**Comment by davidfig** [comment]
Ok, good luck. This is a good page to learn about how pixi works: https://github.com/kittykatattack/learningPixi
