### ISSUE TITLE
Click on sprite vs drag

### ISSUE THREAD

**Issue by ben4d85** [davidfig/pixi-viewport#206]
**Is there a way to stop sprites from triggering their click handler when dragging the viewport?**

I would like it so that the sprites's click handler is only activated on click, but not on drag.

Is this possible? It appears as though in your [demo](https://davidfig.github.io/pixi-viewport/), you got this working?

**Comment by davidfig** [comment]
I used the viewport `clicked` event and then searched the sprites for an overlap. 

To get it working with pixi's interaction model, you listen to pointerdown on the sprite and record the viewport (x, y) during the event. Listen to pointerup and then check if the viewport's (x, y) changed by a larger amount than a threshold to see if the sprite was clicked.

**Comment by ben4d85** [comment]
@davidfig Thank you for your reply. I have used the first approach, based on the code in your demo.

If anyone else is wondering how to achieve this, here is my approach (specific to my use-case where each sprite must only be clickable once):

**Setting up**

```
// Add the viewport to the stage
this.pixiApp.stage.addChild(this.viewport);

// Activate viewport plugins
this.viewport
    .drag()
    .decelerate()
    .clamp({ direction: 'all', })
    .on('clicked', this.viewportClickHandler);
```

**Handling clicks**

```
// When the player clicked anywhere within the viewport
viewportClickHandler = (data) => {

    // Loop through all the game objects
    gameManager.gameObjects.forEach(gameObject => {
        
        // Check if the player clicked on this game object
        // (and if it is still interactive)
        if(
            gameObject.sprite.containsPoint(data.screen) && 
            gameObject.sprite.interactive
        ) {
            
            // Call the game object's click handler
            // (this also unsets the sprite's interactive property to stop if from being clicked more than once - specific to my use case)
            gameObject.onSpritePressed();
        }
    });
}
```

**Comment by davidfig** [comment]
Hmm...anything is possible :) 

My use cases haven't really needed it, however. pixi's bounds calculations are relatively slow (and sometimes inaccurate), and until they fix that, I usually end up rolling my own bounds/interaction code. Unless someone wants to create a PR, I probably won't be adding this functionality.
