### ISSUE TITLE
How to let user scroll the page with the mousewheel while hovering the viewport?

### ISSUE THREAD

**Issue by brunoenribeiro** [davidfig/pixi-viewport#209]
Hello there,

I wish to let the user scroll the page with the mousewheel while hovering the viewport, but all I could achieve was to block dragging. The actual page scroll isn't happening.

Here's my current code:

```
// create PIXI viewport
		this.viewport = new Viewport({
			screenWidth: this.screen.screenWidth,
			screenHeight: this.screen.screenHeight,
			worldWidth: this.world.worldWidth,
			worldHeight: this.world.worldHeight,
			interaction: this.app.renderer.plugins.interaction,
		});

		this.app.stage.addChild(this.viewport);

		this.viewport
			.drag({
				wheel: false,
				mouseButtons: 'left',
			})
			.decelerate();
```
I already tried to add the following to the ViewportOptions (and all combinations of them):
- `passiveWheel: true`;
- `passiveWheel: false`;
- `stopPropagation: true`;
- `stopPropagation: false`;
- `divWheel: this.$refs.workaroundDiv` // a div I've created just to add the event.preventDefault() on scroll

Infortunately none of them solved my problem.

I'm testing on Chrome 80.0.3987.122 64-bits.

Could you please help me?

Cheers

**Comment by davidfig** [comment]
If you set `drag({ wheel: true })` the wheel should work to move the viewport.

**Comment by brunoenribeiro** [comment]
Hello @davidfig 

Thank you for the reply.
I was trying to scroll the whole page instead of dragging the viewport scene...
But I figured out what was happening. Code from another file was adding an event listener to the viewport's canvas, preventing the wheel's default behavior. It had nothing to do with the viewport's configs.

Thanks and sorry for bothering you!
