### ISSUE TITLE
 When dragging, the world protrudes from the area.  Also, if you resize the viewport after zooming, the objects on the screen will disappear.

### ISSUE THREAD

**Issue by KagiJPN** [davidfig/pixi-viewport#212]
Hi, I am Japanese and can hardly speak English. I think it is childish, but please understand. I'm sorry.

I am very interested in PixiJS v5 (WebGL) and am studying.
However, I realized that my ideal would require so many implementations that I was stuck.
And I met this wonderful library.

〇Ideal implementation
- There are square elements that are resized depending on the window size. Fit the Pixi in it.
- Unlike the displayed element, the actual size is about `8000px * 8000px`. (This is assumed to be implemented with `screenWidth` and `worldWidth`.)
- Implement zoom in and zoom out. However, it does not zoom out larger than the world size. (That is, you cannot zoom out larger than `scale 1`.)
- Also, when zooming in and dragging, it will not be out of the world. (It is assumed that this can be implemented with a `clamp`.)

I'm a beginner, so I don't know how to use viewport correctly.

I implemented it very hard with reference to past issues etc. However, it does not work as expected.
- https://github.com/davidfig/pixi-viewport/issues/56

〇Simple deliverable
https://jsfiddle.net/takeshi1234/kt5a1qdv/

Thank you.

**Comment by KagiJPN** [comment]
I modified it a little.
But it is different from the ideal.

https://jsfiddle.net/takeshi1234/kt5a1qdv/2/

**Comment by davidfig** [comment]
> There are square elements that are resized depending on the window size. Fit the Pixi in it.
This seems to be working.

> Unlike the displayed element, the actual size is about 8000px * 8000px. (This is assumed to be implemented with screenWidth and worldWidth.)
This seems to be working.

> Implement zoom in and zoom out. However, it does not zoom out larger than the world size. (That is, you cannot zoom out larger than scale 1.)
This seems to be working.

> Also, when zooming in and dragging, it will not be out of the world. (It is assumed that this can be implemented with a clamp.)
Add `.clamp({ top: 0, left: 0, right: 8000, bottom: 8000})` to your viewport creation code to keep it from dragging outside the world.

Let me know if you need anything else.

**Comment by KagiJPN** [comment]
@davidfig 
Very great this library!
https://jsfiddle.net/takeshi1234/kt5a1qdv/5/

〇 I have two questions
1, The viewport does not grow when resized.
Try running the current jsfiddle in your browser.
Larger browser sizes create margins.
When you make it smaller, you feel that it has been resized normally.

2, Does Pixi have browser scroll control?
I want to restrict browser scrolling when zooming with the mouse wheel when the mouse cursor is on the Pixi screen.
Does such a function exist in Pixi?
Do I need to implement an event listener myself and control it with `event.preventDefault ()`?

I respect you.
Thank you.

**Comment by davidfig** [comment]
> 1, The viewport does not grow when resized.

You need to manually resize the viewport during a resize event. You need to call `viewport.resize(screenWidth, screenHeight)` whenever the screen's width or height changes.

> 2, Does Pixi have browser scroll control?

If you're talking about pixi-viewport, then when `viewport.options.passiveWheel = true` (the default) then whenever you use a wheel function, it'll call `event.preventDefault()`. Wheel events are called through `viewport.drag({ wheel: true })` (this is the default for drag), or `viewport.wheel()`.

**Comment by KagiJPN** [comment]
@davidfig Thank you for your reply

1, It is implemented like this.
https://jsfiddle.net/takeshi1234/kt5a1qdv/5/
```
window.addEventListener('resize', () => {
        viewport.resize(pixi_container.clientWidth, pixi_container.clientHeight);
        viewport.fitWorld();
        console.log(pixi_container.clientWidth, pixi_container.clientHeight)
    }
    );
```
![pixi js](https://user-images.githubusercontent.com/29886891/78319011-2938e380-75a1-11ea-94fb-11edee750c21.gif)

2,
viewport.options.passiveWheel = false

If you set

viewport.js:967 Unable to preventDefault inside passive event listener invocation.

I get the above error.

Thank you.

**Comment by davidfig** [comment]
1. This pixi.application also needs to resize its renderer for it to work.

2. Oh, so you want the window (not renderer) to scroll when hovering over the viewport? Then you can't use viewport.wheel and set `viewport.drag({ wheelDrag: False })` .

**Comment by KagiJPN** [comment]
https://jsfiddle.net/takeshi1234/kt5a1qdv/9/

1.
Using  `app.renderer.autoResize = true;` to resize the renderer did not change the results.
Also, you have to execute it when you resize `viewport.fitWorld ();`, right?

```
window.addEventListener('resize', () => {
        viewport.resize(pixi_container.clientWidth, pixi_container.clientHeight);
        viewport.fitWorld();
    }
    );
```

2.
I don't want the window (not the renderer) to scroll when hovering over the viewport.
I don't want the window to scroll.


Thank you.

**Comment by KagiJPN** [comment]
@davidfig Thank you for your reply
What I am worried about is that the Canvas of the element in the html where the Pixi is displayed is still at the size of "800px * 600px" (perhaps the app's default?).

**Comment by KagiJPN** [comment]
Regarding the first question, we researched and confirmed that it works with the following source code!

Please review this code if you like!
```
window.addEventListener('resize', () => {
        viewport.resize(pixi_container.clientWidth, pixi_container.clientHeight);
        app.renderer.resize(pixi_container.clientWidth, pixi_container.clientHeight)
        viewport.fitWorld();
    }
    );
```

**Comment by davidfig** [comment]
Looks right to me.

**Comment by KagiJPN** [comment]
I appreciate it very much.

Finally, scrolling, my expected behavior can be achieved with the following source code.

```
    pixi_container.addEventListener("wheel", function (event) {
        event.preventDefault()
    }, { passive: false });
```
In other words, I do not want to scroll the browser page on the pixi screen.

However, I want to know if such an implementation is provided by pixi.

Thank you.

**Comment by davidfig** [comment]
that should be done automatically by pixi-viewport. but if it doesn't work, your code looks fine.

**Comment by KagiJPN** [comment]
I had the same assumption. However, I had a question because it was scrolled.

Here's the latest code where that happens
https://jsfiddle.net/takeshi1234/kt5a1qdv/11/

Can you see why pixi-viewport doesn't do this automatically?
Is this a mistake in my implementation?

**Comment by davidfig** [comment]
It's confusing, but if you set `viewport.options.passiveWheel: false` it'll work without your wheel event.

**Comment by KagiJPN** [comment]
`Unable to preventDefault inside passive event listener invocation.`

Maybe pixi-viewport doesn't explicitly define ` { passive: false }`?

Is that an error?

**Comment by davidfig** [comment]
It's here: https://github.com/davidfig/pixi-viewport/blob/f5a0db698af9c35a9e3789d5d3440641c6e072dd/src/input-manager.js#L45

passive needs to be false. the whole passive thing is confusing. i wish they used a different term for it.

**Comment by KagiJPN** [comment]
>passive needs to be false
I think so, too

I don't understand why I get the error 'Unable to prevent Default inside passive event listener invocation.'

Even though it is implemented like this.....
`viewport.options.passiveWheel = false`

**Comment by davidfig** [comment]
you need `viewport.options.passiveWheel = true`. That's why it's so confusing.

**Comment by KagiJPN** [comment]
I tried but it didn't work.

However, there is no problem because the code I commented can make the expected behavior.

This library is really great.

Also, thank you very much for your kind support.

Thank you.
