### ISSUE TITLE
Help to rotate from center

### ISSUE THREAD

**Issue by ColinEspinas** [davidfig/pixi-viewport#222]
I've been trying to rotate the viewport from the center to make better screen shakes by moving the pivot but it is a nightmare actually with Pixi, any idea how to implement it ?

**Comment by davidfig** [comment]
When you change the pivot, you need to also change the position by the negative amount of the pivot to avoid shifting the scene.

**Comment by ColinEspinas** [comment]
Well I've tried a lot to get this right but can't get it. 

Here is what I think was your proposition but it does not work:
```typescript 
this.viewport.pivot = this.viewport.center;
this.viewport.x -= this.viewport.pivot.x;
this.viewport.y -= this.viewport.pivot.y;
```
I've tried many things and searched about pivots in Pixi, but pivots in Pixi are really hard to understand.

**Comment by jjwallace** [comment]
pivot is just a cartesian point and has a setter `.pivot.set(300, 300);`

**Comment by ColinEspinas** [comment]
The problem was rotating the camera viewport from the center. I know how to set the pivot point.

I ended up creating my own camera system at the end. But I don't think it is good to close this issue as it is not answered and could help peoples in the future.

**Comment by davidfig** [comment]
I'd like support rotation in the viewport at some point, but I don't have the need or time for it right now. Closing issues is just to clean up what is being actively worked on. You can still search closed issues. I do often.
