### ISSUE TITLE
Hijack the event of Modal scrolling

### ISSUE THREAD

**Issue by zhouccccc** [davidfig/pixi-viewport#223]
I've created map at website, but i met one issue.
If popped up a modal above the map(pixi-viewport) and I want to scroll the modal content, and then I fount it not works, but the map zoom changed.  I guess the map could `hijack the event of Modal scrolling`
I am sure this description can let you know that. Thanks

**Comment by davidfig** [comment]
You need to stop the propagation of the event when over the modal content. Catch the event (eg, wheel or mousemove) on the modal dialog, and then call `event.stopPropagation()`

**Comment by zhouccccc** [comment]
'wheel' event works. Thanks for your solution
