### ISSUE TITLE
Scope events to PIXI canvas 

### ISSUE THREAD

**Issue by jasonsturges** [davidfig/pixi-viewport#227]
David, Hi - having troubles overcoming scoping of mouse / touch events.

In this solution, there are other html dom elements overlaid on the Pixi Viewport, such as this dialog in which scrolling is needed to navigate the list:

![scrolling](https://user-images.githubusercontent.com/1213591/81102292-0cac0600-8ed5-11ea-8bf9-e45c21189ed1.gif)

But those mouse events are captured by Pixi Viewport - for example, scrolling down in the dialog is also zooming the viewport.

Tried to capture mouse events in the dialog to stop propagation and prevent default, but I can't override the viewport.  Also, I'm not sure how to incorporate logic in the Pixi Viewport without monkey patching a private version of your source code.

Any idea what I can do here?

**Comment by jasonsturges** [comment]
In the [source code](https://davidfig.github.io/pixi-viewport/jsdoc/src_viewport.js.html) I see `WheelOptions`, but I'm not seeing anything in the documentation.

Not sure I fully understand how to leverage the plugin system - is there a way I can override the wheel plugin with my adaptation?

**Comment by xandermathews** [comment]
I haven't tested my own plans to overlay DOM elements over the rendering context, but as a random idea:

Have you tried pausing all the active plugins for the duration of the modal? (Or plausibly [hitting pause at the viewport level alone](https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#pause)?)

**Comment by jasonsturges** [comment]
Ended up creating my own plugins and assuring event targets were the intended canvas.

Would be a cool feature to consider in Pixi Viewport.

**Comment by xandermathews** [comment]
@jasonsturges would you be willing to share your solution or insights? It sounds like myself and others will run into the same problem.

**Comment by jasonsturges** [comment]
Nothing fancy, really a stopgap to fill an emergency, but I created my own plugin:

```js
this.viewport.plugins.add("wheel", new CustomWheelPlugin(this.viewport));
```

...in which, I'm just checking that the target is a canvas element:

```js
wheel(e) {
  if (this.paused) return;
  if (!(e.target instanceof HTMLCanvasElement)) return;
```

Probably revisit this later, especially in regards to multiple canvases.

@davidfig Seems like a few things in play - documentation on `WheelOptions`, ability to scope event listeners directly to the canvas, and I'm still a little fuzzy on plugin patterns for listeners.  

With React, I have some additional lifecycle complexities as these views require context and refs to be instantiated on the DOM, and handled by effects.

**Comment by davidfig** [comment]
Did you try setting `Viewport.options.divWheel` to your canvas? I set that up for the purpose of changing the 'wheel' event from `document.body` to another div. 

The remaining event handlers are provided by pixi (and are based off the canvas, I believe). I've been thinking of replacing pixi's event handlers with custom ones (pixi-viewport's older versions did this) to make everything consistent. But I haven't needed to for any of my apps. 

I don't love the `e.target` check in your wheel handler. It's a bit hacky. Let me know if the options.divWheel helps instead.

**Comment by jasonsturges** [comment]
@davidfig Thanks, that's exactly what I was looking for.  I don't see that in the documentation.

Yeah, I don't like the target check either... just a stopgap until I get some breathing room.  But I'll give this a try.  Thanks for the reply.

**Comment by davidfig** [comment]
It's in the Viewport options. I'll add a note to the wheel plugin about where to find it.

**Comment by jasonsturges** [comment]
@davidfig Oh, sorry - I do see it:
https://davidfig.github.io/pixi-viewport/jsdoc/global.html#ViewportOptions

Not sure how I missed that.

**Comment by davidfig** [comment]
It's not super obvious. I also added it to WheelOptions: https://davidfig.github.io/pixi-viewport/jsdoc/global.html#WheelOptions
