### ISSUE TITLE
Zooming on a precise point

### ISSUE THREAD

**Issue by rodighiero** [davidfig/pixi-viewport#229]
I am using pixi-vieport for drawing a network visualization, but I have a couple of problems I wrote around looking at open issues.

1) fit the visualization in the browser window (size is bigger than scale 1). I tested .fitWidth() and .setZoom() but I cannot keep the visualization centered.

2) I am implementing a zooming function to look at a note with a zoom effect. What would be the best practice in this case?

This is the network visualization: https://rodighiero.github.io/COVID-19/

Thanks for helping me.

**Comment by rodighiero** [comment]
I solved the first issue in this way:

        .setTransform(
            (window.innerWidth - viewport.worldWidth) / 2,
            (window.innerHeight - viewport.worldHeight) / 2,
            .5, .5)

But the zoom is always pending if someone can help :)

**Comment by davidfig** [comment]
For 1, you should use `viewport.fit()` (or `viewport.fitWidth()` / `fitHeight()`)

For 2, what type of zoom are you looking for? There's a simple animated zoom if you use `snapZoom({ width, height, time: 1000, center: centerPoint, ease: 'easeInOutSine', forceStart: true, removeOnComplete: true })`. For more complicated zoom animations, I recommend an animation library, like `pixi-ease` or the like.

**Comment by rodighiero** [comment]
Hi David – Thank you very much for your support.

1) It doesn't work very well as the network is expanding and at the very beginning is rather small, making the initial zoom very close. Fix zoom is fine.

2) It works at the first click (from the entire image to the zoomed point), but not at the second. If the zoom level is the same, moving from the zoomed point to another one runs without any transition. I was looking something like a bounce effect: from a zoomed point out to the entire image to zoom to the second zoomed point. I will check pixi-ease.

**Comment by davidfig** [comment]
1. if your scene is changing, then it'll be difficult to calculate the correct zoom until it finalizes. you need a way to estimate where it's going so you can find the correct scale

2. snapZoom was really designed to snap back the zoom, similar to snap. the user would zoom in and then after they release the zoom, it would snapback. for more complicated zooms, you should use an easing function or library.

cool project, btw.

**Comment by rodighiero** [comment]
Thanks for helping me, I think I still do something wrong and probably a callback is what I need to zoom out and in on the second search.

`            const position = new PIXI.Point(x, y)
            const origin = new PIXI.Point(0, 0)
            const duration = 1000

            const zoomout = () => s.pixi.snapZoom({
                width: 1000,
                height: 1000,
                time: duration,
                center: origin,
                ease: 'easeInOutSine',
                forceStart: false,
                removeOnComplete: true
            })

            const zoomin = () => s.pixi.snapZoom({
                width: 100,
                height: 100,
                time: duration,
                center: position,
                ease: 'easeInOutSine',
                forceStart: false,
                removeOnComplete: true
            })

            if (s.pixi.scale.x < 1) {
                console.log('in')
                zoomin()
            } else {
                console.log('out')
                zoomout()
                setTimeout(zoomin(), duration+100)
            }`

Thanks, btw :)

**Comment by rodighiero** [comment]
And thanks for the library, without it I would not be to make the visualization so fast :)

**Comment by rodighiero** [comment]
Still without a solution. I try to chain two animations with a callback, the first zooming out, the second zooming in. It should be a movement from the micro, to the macro, to the micro again. Any idea to solve this issue? Thanks a lot :)

```
const position = new PIXI.Point(x, y)
            const origin = new PIXI.Point(0, 0)
            const duration = 1000

            const zoomout = callback => {
                s.pixi.snapZoom({
                    width: 1000,
                    height: 1000,
                    time: duration,
                    center: origin,
                    ease: 'easeInOutSine',
                    forceStart: true,
                    removeOnComplete: true
                })
            }

            const zoomin = () => {
                s.pixi.snapZoom({
                    width: 100,
                    height: 100,
                    time: duration,
                    center: position,
                    ease: 'easeInOutSine',
                    forceStart: true,
                    removeOnComplete: true
                })
            }

            // Click

            if (s.pixi.scale.x < 1) {
                zoomin()
            } else {
                console.log('out')
            }
```

**Comment by rodighiero** [comment]
I managed to work it out. It might be not the most elegant way, but it works. Thanks for supporting me.

```
const position = new PIXI.Point(x, y)
            const origin = new PIXI.Point(0, 0)
            const duration = 1000

            const zoomin = () => {
                s.pixi.snapZoom({
                    width: 100,
                    height: 100,
                    time: duration,
                    center: position,
                    ease: 'easeInOutSine',
                    forceStart: true,
                    removeOnComplete: true
                })
            }

            const zoomout = () => {
                s.pixi.snapZoom({
                    width: 1000,
                    height: 1000,
                    time: duration,
                    center: origin,
                    ease: 'easeInOutSine',
                    forceStart: true,
                    removeOnComplete: true
                })
                setTimeout(() => {
                    s.pixi.snapZoom({
                        width: 100,
                        height: 100,
                        time: duration,
                        center: position,
                        ease: 'easeInOutSine',
                        forceStart: true,
                        removeOnComplete: true
                    })
                }, duration)

            }

            // Click

            if (s.pixi.scale.x < 1) zoomin()
            else zoomout()
```
