### ISSUE TITLE
Sort displayObject at Viewport

### ISSUE THREAD

**Issue by zhouccccc** [davidfig/pixi-viewport#232]
Any solution for sorting all displayObjects by `zIndex` which had added to viewport? Hope for your reply

**Comment by davidfig** [comment]
Doesn't pixi provide this functionality: https://pixijs.download/dev/docs/PIXI.Container.html#sortableChildren?

**Comment by zhouccccc** [comment]
Yes, I have solved this problem with another way. Thanks
