### ISSUE TITLE
How do I pan/drag using the w,a,s,d or arrow keys?

### ISSUE THREAD

**Issue by Zackasaurus** [davidfig/pixi-viewport#236]
This is a great library. I was looking through the documentation but I couldn't figure out how to implement this functionality. Would I need to use the moveCorner or moveCenter based on how long a key is pressed and incorporate easing functions or is there a simpler way to do this?

**Comment by davidfig** [comment]
Yes, that's exactly right. Use `moveCenter(viewport.center.x + deltaX, viewport.center.y + deltaY)` in your `keydown` listener. The `keydown` will continuously be called while the key is held down.

**Comment by Zackasaurus** [comment]
Okay great, thank you! Is there any plan to support this out of the box with the drag plugin?

**Comment by davidfig** [comment]
Hmm. . . I currently don't have any plans. If people need it, I could add it. It wouldn't be much work. It would probably be a separate plugin.

**Comment by ccj242** [comment]
This would be a huge help!
