### ISSUE TITLE
Animation between two points

### ISSUE THREAD

**Issue by rodighiero** [davidfig/pixi-viewport#239]
Hi again,

This is a problem correlated to the SnapZoom that I noticed once my problem was fixed.
I noticed that when I zoom from a point 0 (x0, y0) to a new point 1 (x1, y1), there is no transition. The zoom movement is smooth and works well, but the movement from point 0 to point 1 is sudden and hash. There is no animation between the two positions.

Any clues? Thanks a lot.

**Comment by davidfig** [comment]
SnapZoom only handles zoom. You'd need to use `viewport.snap` to smoothly transition between points. Make sure you set SnapZoom.options.noMove = true to ensure that snapZoom doesn't change the position. At some point I'll add an animation class to make this easier. Both snap and snapzoom were designed around the scenario of returning the viewport to a certain zoom or point.

**Comment by rodighiero** [comment]
Hi David,

I implemented it, but the result is not perfect. Sometimes it happens a kind of glitch and the snap always arrives later even if the timing seems correct to me. It's the same (URL)[https://rodighiero.github.io/COVID-19/] if you can look at it.




'''
           const duration = 3000

            const zoomin = () => {
                s.pixi.snap(x, y, {
                    time: duration,
                    ease: 'easeOutSine',
                    removeOnComplete: true,
                })
                s.pixi.snapZoom({
                    width: 100,
                    time: duration,
                    ease: 'easeInSine',
                    removeOnComplete: true,
                    noMove: true,
                })
            }

            const zoomout = () => {
                s.pixi.snap(x, y, {
                    time: duration * 2,
                    ease: 'easeOutSine',
                    removeOnComplete: true,
                })
                s.pixi.snapZoom({
                    width: 1000,
                    time: duration,
                    ease: 'easeOutSine',
                    removeOnComplete: true,
                    noMove: true,
                })
                setTimeout(() => {
                    s.pixi.snapZoom({
                        width: 100,
                        time: duration,
                        ease: 'easeInSine',
                        removeOnComplete: true,
                        noMove: true,
                    })
                }, duration)
```

**Comment by davidfig** [comment]
your eases should be the same or the timing will be off

**Comment by rodighiero** [comment]
Just tested the zoom in. Unfortunately, it's not that: snap always ends later and there is a glitch as the two functions conflict, even with the same easing.

**Comment by davidfig** [comment]
Hmm...maybe it has something to do when they're called? Can you make a jsfiddle so I can play with it?

**Comment by rodighiero** [comment]
I checked, but I do not know exactly how to import pixi 5.0 and pixi-view. Do you have an example? As an alternative, the installation from GitHub is simple (npm i + npm run start + localhost:8080 + search.js is the file to modify) 

https://github.com/rodighiero/COVID-19.

**Comment by davidfig** [comment]
Nice. I installed it. how do you zoom in/out? 

BTW: try to stay away from pixi.text if possible. it slows down the app. use bitmaptext instead unless you are displaying lots of languages.

**Comment by rodighiero** [comment]
Great! ^_^

1) About the structure: Zooming is related to the search function, so it's the _search.js_ file.

2) About the interaction: type a string in the research field at the top right and select a name.

3) About the code: on selection, you see the block of code starting at **line 60** (probably you see an old version as I did not commit last tests).

Cool, I will take a look at bitmaptext on google.

Thanks for helping me!

**Comment by rodighiero** [comment]
In the meanwhile, I implemented the bitmap text — that's much better! I love the video game world, much better than the HTML5 :)

**Comment by rodighiero** [comment]
Hi Davis, did you find a solution?

**Comment by davidfig** [comment]
I did spend about an hour trying to get it to work (sorry, I should have responded earlier). I tried it manually as well with an easing library. The difficulty is the zoom out and then the zoom back in. There's some sort of conflict with the timing during the multiple zooms. There's not an issue with a single zoom. I couldn't wrap my brain around it, though. The center should not be affected by the zoom, but for some reason it is. 

It would take me a few more hours to figure out a solution, and regrettably I don't have the time. Happy to assist you with pointers if you get close or ideas, though.

Good luck!

**Comment by rodighiero** [comment]
Thanks for your reply and your time, don't worry about the delay.

In my humble opinion, it's odd to combine two easings. It should be the sole one managing coordinates and the zoom level. I think that easings are not meant to be merged; that's all.

I don't know if this might help, but d3 has a [zoom module](https://github.com/d3/d3-zoom) working in this way. Perhaps it is worth a look.

I am also available to fund someone who wants to help us with a small amount of money. Do you know someone that might help?

**Comment by davidfig** [comment]
You're probably right. There's likely an f(x) you can find that zooms out and then back in while changing the x, y coordinates properly. It's outside my area of expertise, though. If you can find a generic solution, I'd be happy to add it as a plugin for pixi-viewport.

**Comment by rodighiero** [comment]
If it might be useful, I've found the transition function of d3.js, which use three parameters (x, y, scale):

[https://github.com/d3/d3-zoom/blob/master/src/transform.js](https://github.com/d3/d3-zoom/blob/master/src/transform.js)

**Comment by davidfig** [comment]
Good news. In v4.13.0, I added an animate plugin that properly moves and zooms the viewport. Try it and let me know if you have any feedback. The documentation is here: https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#animate

I think this should help in the experience you were trying to achieve.

More details if you're interested: in snapZoom, I eased the scale factor. The problem with doing that is scale is not linear since it's multiplied, so a change in scale of 1 -> 2 is much bigger than 4 -> 5. That ended up creating a wonky experience. Instead of easing the scale, I eased the screenWidth/HeightInWorldPixels value, which is the value used in fit<Width/Height>.

**Comment by rodighiero** [comment]
Hi David,

Thank you very much, it works incredibly well!

I created one function to zoom in, and one function to zoom out and in when you have already zoomed. You can see the animation working here https://rodighiero.github.io/DH2020/ and the code from line 80 at https://github.com/rodighiero/DH2020/blob/master/src/elements/search.js

I experience just a minor issue with the animation. I change the alpha channels of layers during the interaction, but the event listener for zooming doesn't work in animation. Is it possible to activate a listener also during the animation? This is the code I use to change the alpha channel when I zoom:

```
// Transparency on zoom

    const links = 1
    const contours = d3.scaleLinear().domain([zoomMin, 2]).range([1, 0])
    const couples = d3.scaleLinear().domain([zoomMin, 2]).range([1, 0])
    const nodes = 1
    const triplets = d3.scaleLinear().domain([zoomMin, 2]).range([0, 1])

    viewport.on('zoomed', e => {
        const scale = e.viewport.lastViewport.scaleX
        e.viewport.children[0].alpha = links
        e.viewport.children[1].alpha = contours(scale)
        e.viewport.children[2].alpha = couples(scale)
        e.viewport.children[3].alpha = nodes
        e.viewport.children[4].alpha = triplets(scale)
    })
```

**Comment by davidfig** [comment]
Cool! Check out v4.13.1. It emits `moved` and `zoomed` during `animate.update()`.

**Comment by rodighiero** [comment]
It's just perfect now! Thanks a lot, I needed this function for the next project. I keep you updated!
