### ISSUE TITLE
Mousewheel not working with pixi 5.3

### ISSUE THREAD

**Issue by spassvogel** [davidfig/pixi-viewport#243]
After updating to pixi  5.3 I'm getting errors when using the mouse wheel

```
Uncaught TypeError: can't access property "parentElement", this.interactionDOMElement is null
    mapPositionToPoint InteractionManager.ts:1143
    getPointerPosition input-manager.js:191
    handleWheel input-manager.js:213
    wheelFunction input-manager.js:44
    addListeners input-manager.js:45
    InputManager input-manager.js:24
    Viewport viewport.js:143
```

Happens on Firefox and Chrome

**Comment by spassvogel** [comment]
What could be relevant is that I'm using @inlet/react-pixi. The way I'm constructing the Viewport is like this

```
    const viewport = new PixiViewport({
      interaction: props.app.renderer.plugins.interaction,
    });
```

Where `props.app` is the PIXI.Application instance.

**Comment by davidfig** [comment]
Hmmm...I just tried pixi v5.3 and the mouse wheel event doesn't throw an error on my demo project. Can you check what DOM element is missing a parent? Viewport uses pixi's interaction manager to ensure the mouse is hovering over the viewport before activating the wheel event.

**Comment by spassvogel** [comment]
Might be I'm doing something non-standard. Still, it's odd that it started to crash after updating pixi. Will try to set up an isolated test environment soon.

**Comment by linrz** [comment]
I met the same error by using @inlet/react-pixi. If you have some solutions to solve it, please tell me by the way. 😊 @spassvogel

**Comment by spassvogel** [comment]
Hmm I can't reproduce it yet in my test setup.

**Comment by spassvogel** [comment]
So, what I've learned is when I *dont* specify the `interaction` property, it works. 
@davidfig can you confirm? Is this property optional?

**Comment by davidfig** [comment]
The property is optional but without it, the wheel event will be called across the entire browser window instead of just the pixi canvas. It was originally included to solve for that issue.

**Comment by spassvogel** [comment]
Hmm, but this too is still working for you in pixi 5.3?

**Comment by davidfig** [comment]
Yes. I ran the demo with 5.3 and i didn't have any problems. Can you create a jsfiddle project that demonstrates the problem?

**Comment by kalbert312** [comment]
Faced the same issue. Found the culprit:

in `@inlet/react-pixi`:
```
...
  updateSize = () => {
    const { width, height, options } = this.props

    if (!options?.resolution) {
      this.app.renderer.resolution = window.devicePixelRatio
      this.resetInteractionManager()
    }

    this.app.renderer.resize(width, height)
  }
...
  resetInteractionManager() {
    this.app.renderer.plugins.interaction.destroy()
    this.app.renderer.plugins.interaction = new InteractionManager(this.app.renderer)
  }
...
```

If you pass a custom options prop to the `<Stage>` component without `resolution` this will get executed (I'm not sure if no options are passed what it will default to, which could possibly explain it not being reproducible?). If this gets executed after the viewport is instantiated, the reference will be the old destroyed one (with `this.interactionDOMElement = null`). Based on my debugging, my viewport wrapped in a react-pixi custom component gets instantiated first then this reset thing happens right away.

Workaround:
`<Stage options={{ resolution: window.devicePixelRatio }}>`

**Comment by spassvogel** [comment]
Very nice. Will you inform @inlet?

**Comment by inlet** [comment]
Just checking in this issue.. 

🤔  if something (a plugin, or something else) relies on the interaction manager it will probably break. The reason why I manually reset the interaction manager is because the interaction manager is tightly bound to the resolution and renderer. Changing the size or resolution at runtime, resulting in wrong mouse events.

However maybe I can find a way to maintain the same ref of the interaction manager and update it internals so this will not break.

Thanks for letting me know!

**Comment by inlet** [comment]
@spassvogel I just pushed a patch, instead of re-instantiating the Interaction Manager, it now updates the `resolution`. Can you give it a spin and tell me if the issues is fixed?

https://github.com/inlet/react-pixi/releases/tag/v5.0.4

**Comment by spassvogel** [comment]
Yup that worked. Thx!
