### ISSUE TITLE
Emit "update" event

### ISSUE THREAD

**Issue by SukantPal** [davidfig/pixi-viewport#245]
It would be cool if `update` emits an event - so that users can re-render their app "if the viewport is dirty".

**Comment by davidfig** [comment]
I use the `viewport.dirty` flag to determine when the viewport has changed and needs to rerender. If you think it's helpful, I could add the dirty flag results to the `frame-end` event, which is called at the end of the `viewport.update` frame.

**Comment by SukantPal** [comment]
Never mind. I accidentally ignored the `frame-end` event because it was inside an if-statement.
