### ISSUE TITLE
Typings do not have scaled member

### ISSUE THREAD

**Issue by prKassad** [davidfig/pixi-viewport#248]
Hi! In typescript definition is missing `Viewport#scaled` member.

https://github.com/davidfig/pixi-viewport/blob/9cdb1dbd2d1f6baf1d87b1a4de94e33f7f8fc783/src/viewport.js#L645
https://github.com/davidfig/pixi-viewport/blob/9cdb1dbd2d1f6baf1d87b1a4de94e33f7f8fc783/src/viewport.js#L641

**Comment by davidfig** [comment]
Thanks. Added in 4.12.1.
