### ISSUE TITLE
Wheel({center: worldEdge }) edge case

### ISSUE THREAD

**Issue by hassanshaikley** [davidfig/pixi-viewport#25]
If you have wheel on center, and your object is at 0px (and the edge of the world is at 0px). Then zooming in zooms you into 0px, as opposed to screenwidth/2. 

I would love to submit a PR to accomplish them but I may need some guidance.

**Comment by hassanshaikley** [comment]
I realized this is fixed with an update however I am getting a flicker.

**Comment by hassanshaikley** [comment]
It was some issues with my world height.

Ok this library is absolutely gorgeous. 

Thank you

**Comment by hassanshaikley** [comment]
Ok but I just noticed a click causes a flicker when you are zoomed out too much. Whatever too much means...

**Comment by hassanshaikley** [comment]
I disabled bounce and it has stopped.

**Comment by davidfig** [comment]
Bounce is undefined in some circumstances, especially when near the edge or the screen is too large. Use the underflow setting to control what happens in some edge cases.

**Comment by hassanshaikley** [comment]
Ahh. Thank you, David
