### ISSUE TITLE
ViewportJS seems to absorb all scroll events, even when it shouldn't.

### ISSUE THREAD

**Issue by Andrew1431** [davidfig/pixi-viewport#255]
Pseudocode:

```typescript

  const stopScroll = useCallback((e: any) => { e.preventDefault(); e.stopPropagation(); }, []);
...
        <GameBoard />
        <Grid style={{ flexGrow: 1 }} onScroll={stopScroll}>
          {is_fullscreen && (
            <Grid.Column width="12">
              <Scrollbars autoHide style={{ height: '100%' }}>
                <PlayerChoosePlanetMovement owned fullscreen />
              </Scrollbars>
            </Grid.Column>
          )}
...
```

I have HTML overlaying my PIXI canvas / app. 

When I scroll on the HTML I can't seem to get the game board to stop scrolling in / out. GameBoard is my PIXIjs application using the viewport.

Any tips on how to stop scrolling while my mouse is scrolling on the <PlayerChoosePlanetMovement /> component?

**Comment by Andrew1431** [comment]
Hey @davidfig thanks for the help, it was definitely all the zIndex hacks I was doing. The issue is resolved for me after properly laying out my UI instead of all the hacks I had.

**Comment by Andrew1431** [comment]
Hey I'm trying to make a jsfiddle but I've never actually used it before. I managed to get `pixi.js` installed from the CDN, but am not seeing `pixi-viewport` in the CDN searcher. 

How do I get one set up?

**Comment by davidfig** [comment]
Use this: https://cdn.jsdelivr.net/npm/pixi-viewport@4.13.2/dist/viewport.min.js
