### ISSUE TITLE
Animation when using zoomPercent()

### ISSUE THREAD

**Issue by sandyricardo** [davidfig/pixi-viewport#26]
Hai David thank you for your work.
Is there a way to make zoom become an animation instead of direct zoom? 
For example when i use : zoomPercent(2,2)

**Comment by davidfig** [comment]
Have you tried viewport.snapZoom()? Basic usage:

viewport.snapZoom({ width: newWidth (or height: newHeight), time: 1000, removeOnComplete: true, interrupt: false })

Full options are in the docs. It doesn't use a percent, but it would be easy to add that if it would be helpful.

**Comment by sandyricardo** [comment]
Works perfectly David, Thank you so much. 
Really appreciate your work and help
