### ISSUE TITLE
Missing property in BounceOptions

### ISSUE THREAD

**Issue by rkrasky** [davidfig/pixi-viewport#264]
First of all, thank you very much for the great work. In BounceOptions interface of the typescript declaration, the "bounceBox" property is missing. Also the "underflow" property is not optional, but it should be.

**Comment by uahic** [comment]
I just noticed the same issues; David is not using typescript and thus not aware of breaking changes so we have to fix that. I might have a look this evening

**Comment by uahic** [comment]
PR created ( https://github.com/davidfig/pixi-viewport/pull/273 )

**Comment by davidfig** [comment]
Thanks for the PR and fixes! I published it as 4.18.1
