### ISSUE TITLE
PIXI.Renderer compatibility

### ISSUE THREAD

**Issue by xtreh** [davidfig/pixi-viewport#267]
When me use app.renderer.render(my_stage) for rendering my stage ( Or just create PIXI.Renderer object and render viewport directly ) viewport .drag() and .pinch() plugins didn't working, but .wheel() works properly.

example:
https://jsfiddle.net/b3kst6j0/

**Comment by davidfig** [comment]
The two render calls are what's causing the problem. (Although I'm not sure why that is.) If you comment out the graphics `render()` call, then it works fine. 

It's better to create a stage with children = [viewport, graphics], and render only that stage. Then it should work fine.

**Comment by xtreh** [comment]
> The two render calls are what's causing the problem. (Although I'm not sure why that is.) If you comment out the graphics `render()` call, then it works fine.
> 
> It's better to create a stage with children = [viewport, graphics], and render only that stage. Then it should work fine.

thanks, yes. I started using your solution.

**Comment by xtreh** [comment]
why if me .destroy stage after renderer.reder(stage) the problem appears again?
