### ISSUE TITLE
Test more-pixi branch

### ISSUE THREAD

**Issue by davidfig** [davidfig/pixi-viewport#27]
I did some refactoring over the last few days and I wanted feedback/testing before merging with master. The changes are in the more-pixi branch.

There is one breaking change, and a bunch of under-the-hood changes:

1. Viewport is now a child of PIXI.Container. This means you no longer pass a container, but viewport is the container. This cleaned up some of the code. (I originally had it separate to avoid a peer dependency, but decided this was more robust.)

2. I removed the yy-loop and yy-input dependencies and now fully rely on PIXI.ticker and PIXI.interaction for all looping and interaction. This means viewport no longer ships with its own start/stop functionality. This had the added benefit of a significant perf improvement. Not sure if yy-loop was the culprit (I spent many hours trying to figure out what was going on). Either way, this is cleaner and more in line with a true PIXI library.

3. hitArea makes a return to set the hit area for the viewport. The hitArea defaults to the passed world size. You can also statically change it by setting options/viewport.forceHitArea

**Comment by qwertysam** [comment]
The countDownPointers() function in the Viewport doesn't count the left mouse button properly. It appears that `pointers[key].leftDown` only returns true on the tick *after* it's needed for things like the drag plugin.

**Comment by davidfig** [comment]
I noticed that too. I tried to put in a fix in the latest push, but I might not have solved it yet.

**Comment by davidfig** [comment]
In fact, there is definitely some wonkiness in the countPointersDown() function. PIXI doesn't provide that functionality and I needed to hack it. I'm also tracking a problem with pinch where it still thinks there are two fingers touching when one is up.

**Comment by qwertysam** [comment]
If PIXI doesn't provide it, then doing something hacky with the underlying pointer event from `event.data.originalEvent` would be a good approach.

**Comment by davidfig** [comment]
I'm using this.trackedPointers, which is PIXI's list of pointers. The problem is that PIXI handles the mouse pointer differently than touch. So sometimes you have a mouse pointer in the list even when it's not active. That throws off the count. (At least that's my working theory.)

**Comment by davidfig** [comment]
Thanks for your help! I just merged and released the more-pixi branch into master. Let me know if you see any additional issues.
