### ISSUE TITLE
Weird behavior of sprites when combining with Tinker

### ISSUE THREAD

**Issue by SpraylnlPray** [davidfig/pixi-viewport#270]
Hey there, first of all thanks for creating this library!

I have a question about using this library in combination with tinker. I'm using tinker to make objects easily draggable. After integrating the viewport library I can still drag the sprites, but in addition to dragging the sprites I also drag the canvas itself, resulting in weird movement of the sprites.

Is there a setting I might be missing?
This is my code:

index.html
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Hello Pixi</title>
</head>
<body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.1.3/pixi.min.js"></script>
  <script src="tink.js"></script>
  <script src="viewport.js"></script>
  <script src="main.js"></script>
</body>
</html>
```

main.js
```
// Aliases
let Application = PIXI.Application,
  loader = PIXI.loader,
  resources = PIXI.loader.resources,
  Sprite = PIXI.Sprite,
  TextureCache = PIXI.utils.TextureCache,
  Container = PIXI.Container,
  Graphics = PIXI.Graphics;

let app = new Application({
  worldWidth: 512,
  worldHeight: 512,
  antialias: true,
  transparent: false,
  resolution: 1,
});
document.body.appendChild(app.view);

let t = new Tink(PIXI, app.renderer.view);
const viewport = new Viewport.Viewport({
  screenWidth: window.innerWidth,
  screenHeight: window.innerHeight,
  worldWidth: 512,
  worldHeight: 512,

  interaction: app.renderer.plugins.interaction,
});
app.stage.addChild(viewport);
viewport.pinch().drag().wheel().decelerate();

loader
  .add('bunnyImage', 'images/bunny.png')
  .add('catImage', 'images/cat.png');

let bunny, state;
function setup() {
  // single sprite
  bunny = new Sprite(TextureCache['bunnyImage']);

  bunny.position.set(120, 120);
  bunny.vx = 0;
  bunny.vy = 0;

  t.makeDraggable(bunny);

  viewport.addChild(bunny);

  let tiger2 = new Sprite(TextureCache['tigerImage']);
  tiger2.position.set(20, 20);
  bunny.addChild(tiger2);

  state = play;
  app.ticker.add((delta) => gameLoop(delta));


function gameLoop(delta) {
  t.update();
  state(delta);
}

function play(delta) {
}
```

I'm using version 4.17.1 from https://github.com/davidfig/pixi-viewport/releases/

Any help or resource I could check out would be great!

**Comment by davidfig** [comment]
it looks like Tink's input model is conflicting with the viewport. My guess is that Tink is not calling `event.stopPropagation()` after it receives an input event. If you add that after the `event.preventDefault()` in the Tink code, that may help. I

f you're still having trouble after that change, I'm happy to take a look at a jsfiddle or something similar to debug it.

Good luck!

**Comment by SpraylnlPray** [comment]
I added `event.stopPropagation()` where I think it'd be necessary, the behavior stays the same. I uploaded all the code I have here:
https://github.com/SpraylnlPray/PixiTinkViewport
All files are included. Thanks for you help david

**Comment by davidfig** [comment]
Ah, I had it backwards. The viewport is what's controlling the input events, not Tink. I tried a few hacks to see if I could get them to work together, but I didn't have any luck. 

To use it with the viewport, you'll likely have to rewrite Tink so it uses pixi's interaction model instead of creating additional input events off the keyboard. 

Drag and drop is easier than you think since pixi provides sprite.containsPoint(), which handles collision detection for you. Then you just need to change the sprite's position with the cursor, and release it on the pointerup event. The only trick is that you need to save and then add back the delta between where on the sprite the cursor clicked and it's (0, 0) position (otherwise it'll jerk on the initial drag).  

Good luck!

**Comment by SpraylnlPray** [comment]
I'll give it a try, thanks david!

**Comment by SpraylnlPray** [comment]
Yes I got it! There's a perfect example for how to do dragging in the PixiJS examples (https://pixijs.io/examples/#/interaction/dragging.js) - I simply didn't look there as I knew Tinker would take care of it. Sorry for bothering, thanks again for this library David!

**Comment by SpraylnlPray** [comment]
Do you have any tips on integrating with Pixi-React?

**Comment by davidfig** [comment]
I don't usually use pixi-react, but there are a number of comments related to react scattered throughout the issues list. Search on closed issues for the discussions.
