### ISSUE TITLE
Question: drag-end values

### ISSUE THREAD

**Issue by mtwzim** [davidfig/pixi-viewport#277]
I am developing an application using the pixi-viewport, the intention is to know when the world is no longer visible on the screen because the user dragged it.But the returns provided by the drag-end do not seem to make much sense, is there any way to know if the world is no longer visible because it has been dragged too far?

**Comment by davidfig** [comment]
The drag event returns where the user touched the screen. That's not what you're looking for.

Instead, on your drag-end event handler, check the viewport's coordinates and compare it to your world. The easiest way is checking your world's bounds against `viewport.left`, `viewport.top`, `viewport.right`, and `viewport.bottom`. These are in world coordinates. So, for example, if your world's right-most coordinate (eg, `world.x + world.width`) is `< viewport.left`, then you know your world is off the screen to the left.

**Comment by mtwzim** [comment]
So, thank you, that's right :)
