### ISSUE TITLE
Turn off zoom x or y axis.

### ISSUE THREAD

**Issue by AStaroverov** [davidfig/pixi-viewport#281]
Hi! How can i turn off zoom one of axis on wheel and keep have ability change zoom programatically?

**Comment by davidfig** [comment]
There's currently not a way to do it. You'd have to add an option to the `wheel` plugin to allow x, y, or all. You can develop a user plugin, or submit a PR with the code. It should be only a few lines of code.

**Comment by AStaroverov** [comment]
Yeap. I have done exactly as u say. Pretty easy.
