### ISSUE TITLE
Zoom without changing scale of all children

### ISSUE THREAD

**Issue by NiloDrumond** [davidfig/pixi-viewport#285]
What I need is the following:

A map that can drag and zoom with markers, but the markers need to stay at the same size. Of course, the markers need also to move to the relative position to the map if the user drags or zoom. How can I achieve that?

ps: I'm using react-pixi, but I don't thing this will change much.

**Comment by davidfig** [comment]
The easiest way is to listen to the `zoomed` event, and then iterate through all the markers to individually change their scale to take into account the new viewport zoom. I forget the right math, but it's something like multiplying the scale by 1/viewport.scale.x (or the inverse?).

**Comment by NiloDrumond** [comment]
> The easiest way is to listen to the `zoomed` event, and then iterate through all the markers to individually change their scale to take into account the new viewport zoom. I forget the right math, but it's something like multiplying the scale by 1/viewport.scale.x (or the inverse?).

Thanks! I was thinking about something like that, but I was trying to use addEventListener() instead of on().
