### ISSUE TITLE
Pixi.js v.6.0 cannot add viewport as child

### ISSUE THREAD

**Issue by uberubert** [davidfig/pixi-viewport#287]
Hi, just tested version 6 of pixi.js. class Viewport no longer matches the signature required by addChild.
This is on Viewport v.4.21.0

Here is some of the error show by Visual Studio Code when trying feed a Viewport as a parameter to addChild()

```
Argument of type 'Viewport' is not assignable to parameter of type 'DisplayObject'.
  The types returned by 'listeners(...)' are incompatible between these types.
    Type 'Function[]' is not assignable to type 'ListenerFn[]'.
      Type 'Function' is not assignable to type 'ListenerFn'.
        Type 'Function' provides no match for the signature '(...args: any[]): void'
```

**Comment by davidfig** [comment]
Hmm...I just tried it with the demo, and it seems to work outside of a deprecation warning. How are you importing viewport?

**Comment by davidfig** [comment]
Ok, I think I fixed typescript compatibility w/pixi v6 in pixi-viewport v4.21.1. Please try it out and let me know if I missed anything.

**Comment by uberubert** [comment]
Now that's some quick feedback, thank you!

The addChild error disappeared when testing with 4.21.1.

Please note: I see now I have some more issues going on in my project that are unrelated to pixi-viewport (errors related to paths, aliases etc). I may have to fix all errors before I can confirm 100% if it worked or not (or if it was even broken in the first place).

**Comment by uberubert** [comment]
I'm closing this issue since it works perfectly now.

I'll add more info later if I can find the time to investigate and reproduce the issue, but for now I suspect I was the cause; Probably messed around too much with the webpack.config, especially the resolve.alias section and possibly messed with the values in resolve.extensions (now set to `extensions: ['.ts', '.tsx', '.js']`).
