### ISSUE TITLE
get pointer position

### ISSUE THREAD

**Issue by nrgapple** [davidfig/pixi-viewport#288]
Create a function to get the pointers current position in the world. null if not in the world

**Comment by davidfig** [comment]
The easiest way to accomplish this is to listen to the canvas mousemove event. It will only fire if over the canvas. You then use viewport.toWorld() to convert them into world coordinates.

**Comment by nrgapple** [comment]
For reference I got the mouse world position at any given moment:

```js
export const app = new PIXI.Application()
.
.
.
const pos = app.renderer.plugins.interaction.mouse.global;
const worldPoint = viewport.toWorld(pos.x, pos.y);
```
