### ISSUE TITLE
Broken behaviour on touch device when one finger is removed while outside the viewport (on the browser ui)

### ISSUE THREAD

**Issue by dontwork** [davidfig/pixi-viewport#291]
Hi

I am seeing some odd behaviour where if I have pinch enabled for zooming and 2 finger dragging... if I do a pinch but I move one finger out of the viewport on my iPhone and over the top of the address bar in safari and I then remove that finger and then the other one and then try and use the app odd things happen.

In this broken state I can see that it is firing 'zoomed' events while only being dragged with one finger. I can also see it firing 'moved' events while being dragged on with one finger.

Before the breaking action of removing a finger while not within the viewport, everything works perfectly

**Comment by dontwork** [comment]
This was caused by me having a hitArea set on my stage... I don't think I needed it and I don't know if this is still an issue for Pixi-viewport. I think it probably still is as it doesn't seem like Pixi-viewport behaves appropriately when touch events move outside the hitArea

**Comment by davidfig** [comment]
Hmm...so it fires both zoomed and moved events when your finger leaves the canvas? That's a bit weird. I've not looked into this case. If it's something you want to explore and make a recommendation on how to handle, I can look into it. It may be the case that the proper events are not firing (to which there isn't much we can do), but it also may be that they are and we're not handling them well. 

Let me know what you find and happy to accept a PR if you can figure how where it's going wrong.

**Comment by dontwork** [comment]
Yeah I'm not sure... It seemed to me that if you removed a finger while it was outside the hitarea during a pinch that pixi-viewport gets stuck in that mode. I say that because once it 'breaks' it fires events while dragging one finger that should only fire when dragging 2. My removal of the hitarea has completely fixed it and I didn't seem to need it, I had just copied it from another project. I will close the issue for now, there is a record here if anyone else runs into it and I will look into finding the cause in the future.
