### ISSUE TITLE
Viewport.on declaration incorrectly typed

### ISSUE THREAD

**Issue by SukantPal** [davidfig/pixi-viewport#292]
https://github.com/davidfig/pixi-viewport/blob/b525b0eee3a490d01fabeed95dcb2767e64dafe4/%40types/index.d.ts#L297

The first argument of `on` should of type `string` not `PIXI.InteractionEvent`.

**Comment by davidfig** [comment]
Thanks. Updated in 4.21.1.

**Comment by SukantPal** [comment]
Wow, that's fast!
