### ISSUE TITLE
dynamic loading of the tilemap 

### ISSUE THREAD

**Issue by nik0145** [davidfig/pixi-viewport#294]
I am using @pixi/tilemap and want drag my map within the borders with `clamp()`. 
can i somehow rotate the viewport? 
I am trying to solve the problem of dynamically loading a map for my project, maybe there are other ways  ?
![image](https://user-images.githubusercontent.com/23018061/112988546-a6734600-916c-11eb-81b1-a0db6b07e146.png)

**Comment by nik0145** [comment]
Okay, i'll try it.
Can you tell me how to implement dynamic map loading ?
How do i get the end of the map event ?

**Comment by nik0145** [comment]
`rotate` was not suitable for solving the problem

**Comment by davidfig** [comment]
It looks like you have a 2.5d view. I don't think rotate will work with that type of view. What are you trying to do?

**Comment by nik0145** [comment]
I want to restrict viewing if the camera is out of the map.

**Comment by davidfig** [comment]
Did you try `viewport.clamp({ direction: 'all' })`?

**Comment by nik0145** [comment]
Sorry that i didn't answer for so long.
I changed a type of the map for staggered instead of diamond.
![image](https://user-images.githubusercontent.com/23018061/115251771-844d6200-a133-11eb-8570-12a40373de04.png)
I want to get piece of the map dynamically when i move to  borders edge  of the existing map.
What event i should use to solve this problem ?
![image](https://user-images.githubusercontent.com/23018061/115250741-8a8f0e80-a132-11eb-8534-96bc5c75b12b.png)

**Comment by davidfig** [comment]
You should listen to the moved event. You will then need to loop through the visible screen to see what tiles are missing. I did something similar in my pixi-cull project (https://github.com/davidfig/pixi-cull), although your use case is different. I think there are some examples in the @pixi/tilemap project of your use case.

**Comment by nik0145** [comment]
Ok thanks i will try
