### ISSUE TITLE
toWorld and toScreen methods return wrong result

### ISSUE THREAD

**Issue by 1b0x** [davidfig/pixi-viewport#297]
Hello,
Every time when I call toScreen or toWorld methods, they return Point (x: 0, y: 0)

This is how I initialize the Viewport:
```ts
this.viewport = new Viewport({
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    worldWidth: 2750,
    worldHeight: 2510,
    interaction: this.renderer.plugins.interaction
});

this.stage.addChild(this.viewport as any);
```

Also, I'm resizing the viewport and stage
```ts
this.viewport.resize(width, height, 2750, 2510);
this.renderer.resize(width, height);
this.stage.scale.set(scale);
```

Then, when I add a new sprite to the Viewport and call toScreen method, it returns Point (x: 0, y: 0)
```ts
this.viewport.addChild(this.splashScreen);
console.log(this.viewport.toScreen(0, 0)); // Point (x: 0, y: 0)
```

By the way, it works when I call it in setTimeout/setInterval functions.
```ts
setTimeout(() => console.log(this.viewport.toScreen(0, 0)), 500); // It works and returns correct result
```

**Comment by davidfig** [comment]
That is strange. Are you initializing anything else between when you first check the position and after the setTimeout? What are you expecting as the right answer?

**Comment by 1b0x** [comment]
The right answer must be `Point {x: -328.375, y: -707.4350000000002}`.
Firstly I'm initializing PIXI Application then I initialize Viewport and then Vue.js.
When the Vue.js application is created/mounted I'm appending renderer.view to the DOM (is this the problem?)

And then I'm checking for the position using toScreen method and it returns Point (x: 0, y: 0)

And no, I'm not initializing anything else between position checking and after the setTimeout

**Comment by davidfig** [comment]
Have you tried initializing vue first and then pixi and viewport? I'm not familiar with vue, but it's worth a try to see if that's what's causing.

**Comment by 1b0x** [comment]
Issue is fixed! It is my bad!
Thank you @davidfig
