### ISSUE TITLE
Give world an offset

### ISSUE THREAD

**Issue by paulhobbel** [davidfig/pixi-viewport#298]
Is there any easy way to give the world of the viewport an offset. I am using pixi-viewport for a minimap, our map however does not start at 0,0 at the left-top. Would there be any way to give the world an offset?

Easiest way would be if I could specify the top left corner coordinates

**Comment by davidfig** [comment]
sure: `viewport.moveCorner(x, y)`

**Comment by paulhobbel** [comment]
The issue is that negative values are not working, however we solved it by using an inner container that translates from the game coordinates. Thanks anyhow.
