### ISSUE TITLE
How to give children a relative zoom

### ISSUE THREAD

**Issue by paulhobbel** [davidfig/pixi-viewport#299]
What would be the best way to give children of the viewport a zoom level relative to the screen instead of the world.

As an example this is how it works right now:
![aiQS51EEwy](https://user-images.githubusercontent.com/20015650/114621388-ebd75d80-9cac-11eb-98ff-22ff8e8e9355.gif)

And this is how I want it to work:
![cw9RTOUo0m](https://user-images.githubusercontent.com/20015650/114622043-c4cd5b80-9cad-11eb-954a-74eb0989809f.gif)

**Comment by davidfig** [comment]
Listen to the zoomed event and set the children's scale to 1/viewport.scale.x.

**Comment by paulhobbel** [comment]
Thanks that worked!
