### ISSUE TITLE
Bug with drag smoothing

### ISSUE THREAD

**Issue by qwertysam** [davidfig/pixi-viewport#3]
When you drag and release, the viewport is designed to have an effect where it gradually comes to a stop depending on the velocity of which you released it.

I found that after zooming in and out, the effect quickens and seemingly "teleports" the viewport to the end position rather than gradually coming to a stop there.

Here's a video that shows what I mean
https://youtu.be/JqgNEMeLg4Y

This is the code that I'm currently using to invoke the zoom
```
const maxHeight = 1000;
const minHeight = 100;
const zoomRate = 40 / 100;

function updateMouse(dx, dy, dz, ev) {
    var currentHeight = viewport.bottom - viewport.top;
    var newHeight = currentHeight + (zoomRate * dy);
    viewport.fitHeight(Math.min(Math.max(newHeight, minHeight), maxHeight));
    viewport.update();
}
require('mouse-wheel')(updateMouse, true);
```
And here's how I instantiate the viewport
```
var options = {
    screenWidth: w * 2,
    screenHeight: h,
    worldWidth: w,
    worldHeight: h,
};

var viewport = new Viewport(game.stage, options);

viewport
    .drag()
    .hitArea()
    .decelerate()
    .start();
```
Thanks!

**Comment by davidfig** [comment]
Hmm...I just released to npm a new build that fixed a problem with the bounce/clamp on the bottom-right of the viewport. 

Looking at your video, I don't think your bug was related to this fix, however. Not sure why the decelerate breaks when you zoom using fitHeight. Do you mind trying pinch() to see if that works with your setup?

I've been meaning to add a plugin for mouse-wheel zooming. I'll try to write it when I get home tonight (don't have a wheeled mouse here).

**Comment by qwertysam** [comment]
I've tried using `pinch()` as well, and experienced the same results. (However on mobile it's a different story, I've got some crazy transformations going on there when i pinch. I'll try to get a video later)

It would be fantastic if you could implement mouse-wheel zooming, I would certainly appreciate it!

**Comment by davidfig** [comment]
I added a .wheel() plugin for version 0.7.1 in npm. Let me know if you have any problems. 

Your original code looked okay to me, so there may be another lurking bug we haven't found yet. Open another issue related to the crazy transformations :)

Thanks for working this through with me. Still trying to get to version 1.0.

**Comment by qwertysam** [comment]
Updated plugin version to 0.7.1, using `wheel()`, and the bug no longer persists. Thank you!
