### ISSUE TITLE
Uncaught TypeError: PIXI.Application is not a constructor

### ISSUE THREAD

**Issue by ichabodphage** [davidfig/pixi-viewport#302]
i tried using the generic pixi.viewport installation (just importing it using an HTML file) and i got the error "Uncaught TypeError: PIXI.Application is not a constructor"

`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>sideScrolling test</title>
  <link href="style.css" rel="stylesheet" type="text/css" />
  
</head>

<body>
  <script src="./dependencies/pixi.js"></script>
  <script src="./dependencies/viewport.js"></script>
  <script type= "module" src="./app.js"></script>
  
</body>

</html>`

here is the HTML i use to link everything together, did i do something wrong?

**Comment by MajesticMullet** [comment]
Hey, did you manage to fix this? I'm having the same issue.

**Comment by Valent-p** [comment]
It has been several years, should we assume this is no longer an issue?
