### ISSUE TITLE
Demo/example of how to deal with two viewports for a minimap ?

### ISSUE THREAD

**Issue by fraxken** [davidfig/pixi-viewport#305]
Hello 👋 

I'm working for the first time with PIXI.js to make a game for the ludum dare this week-end. I'm working with this package for the main viewport (it work well).

However i was wondering if i could instanciate a second instance of viewport to create a minimap. I tried a lot of different code but without success (i feel like this is possible but not sure what i'm doing wrong).

The code where i deal with the viewport: https://github.com/fraxken/pixi-experimental/blob/main/assets/scripts/ECS/engine.class.js (most of the work is done in the constructor and _initStage()). 

If you have any tips or maybe working example i will glady take.

Thanks you for the time.

**Comment by davidfig** [comment]
You can create the minimap using a second viewport. You'll need to mask it so it doesn't run past the edges. See pixi-scrollbox (https://github.com/davidfig/pixi-scrollbox) for an example of a masked viewport. I've received reports of bugs relating to a viewport on top of another viewport for the wheel events. But otherwise it should work with the right options.

**Comment by fraxken** [comment]
I'v not played that much with mask yet (but this seem to be a thing to master).

I made a branch with a beginning of class by looking at what you'r doing in pixi-scrollbar: https://github.com/fraxken/pixi-experimental/commit/7c34ae07413e394f0ecf4dca1d8d537115855626

And this: https://github.com/fraxken/pixi-experimental/commit/4a45beeea4e084cbdaa1fdc7c3f60ab42776f0a5

But i feel my minimap never show if my main viewport is here 🤔.

**Comment by davidfig** [comment]
What do you mean by "never show if my main viewport is here"? They both should render if included in the scene. You will need to duplicate the scene objects in the minimap (you can't reuse objects between containers). Let me know if you run into other issues.
