### ISSUE TITLE
Can't select any HTML or input if Viewport is created

### ISSUE THREAD

**Issue by temirlanzhangazy** [davidfig/pixi-viewport#306]
I am using Vue 3 and the last versions of Pixi+Viewport, now faced a strange problem. If I call
`new Viewport` in code, I won't be able to select anything, I just can't select text, can't write in input etc.
`user-select` is OK, **CSS is OK**. The problem appears when using **Viewport**!

**Comment by temirlanzhangazy** [comment]
I can type in any input, also select any text on my Vue 3 application. But after this:
```
let viewport = new Viewport({
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    worldWidth: room.w,
    worldHeight: room.h,
    interaction: app.renderer.plugins.interaction,
    disableOnContextMenu: false
})
```

Every element becomes disabled and impossible to select. There are no `user-select: none;`, I even tried `user-select: all !important;`, but has no result.

**Comment by temirlanzhangazy** [comment]
Same in vanilla JS, you just can't type anything in that input
<img width="815" alt="Снимок экрана 2021-04-24 в 17 30 16" src="https://user-images.githubusercontent.com/61193731/115958867-bf300b00-a522-11eb-85dd-5fc2409397c4.png">

**Comment by davidfig** [comment]
Is the canvas covering the html elements? Viewport sets interactive=true, which tells pixi to capture events that happen over the canvas.

**Comment by temirlanzhangazy** [comment]
I need some Interface like inputs to be editable and to be on top of the canvas, how can I achieve that? I tried z-index, but it doesn't change anything.

**Comment by davidfig** [comment]
If the html element is appended after the canvas then it should get the event first unless you change the canvas's z-index. Check that something else is not interfering with the events.

**Comment by temirlanzhangazy** [comment]
Even if I don't append the app.view, even if the canvas does not exist, after creating a new Viewport I can't select or type in any element.

**Comment by davidfig** [comment]
Ok, that is just strange. The only non-PIXI event listener that pixi-viewport uses is 'wheel'. I'm not sure how the viewport is blocking other events. Did you check your DOM to see what is capturing the event?

**Comment by temirlanzhangazy** [comment]
I found out that deleting `new Viewport` causes errors that block the mouseDown function. mouseDown event had an e.preventDefault function... My bad. Thanks.
