### ISSUE TITLE
canvas getImageData get error data after zoom

### ISSUE THREAD

**Issue by kitety** [davidfig/pixi-viewport#317]
Hello, I got a problem with getImageData after zoom. I am asking for help.
Before, I use this code to judge my point-click is on the line.
```js
// x,y is the point position for canvas。
const extract = app.renderer.plugins.extract;

const canvas = extract.canvas(appViewport);

const context = canvas.getContext('2d');

const data = context.getImageData(x, y, 1, 1).data;

return rgbaIsOnLine(data);
```
With the zoom-value is 1，it is perfect （no zoom）。
But when I zoomed other values ，it cannot work well。

**Comment by kitety** [comment]
I got it.

**Comment by zszq** [comment]
> Hello, I got a problem with getImageData after zoom. I am asking for help.
> Before, I use this code to judge my point-click is on the line.
> 
> ```js
> // x,y is the point position for canvas。
> const extract = app.renderer.plugins.extract;
> 
> const canvas = extract.canvas(appViewport);
> 
> const context = canvas.getContext('2d');
> 
> const data = context.getImageData(x, y, 1, 1).data;
> 
> return rgbaIsOnLine(data);
> ```
> 
> With the zoom-value is 1，it is perfect （no zoom）。
> But when I zoomed other values ，it cannot work well。

How did you deal with this problem?
