### ISSUE TITLE
Demos issue

### ISSUE THREAD

**Issue by joaopedromatos** [davidfig/pixi-viewport#318]
Hi,

First of all great work :)

I'm trying out the live demos and the two demos with standalone CDN are reporting an error "Uncaught SyntaxError: Unexpected token '<<'"

It looks like the file https://davidfig.github.io/pixi-viewport/viewport.js is not correctly merged.

Thanks for your great work.

**Comment by davidfig** [comment]
Thanks for the catch. Those were using old files. I updated the github page: https://davidfig.github.io/pixi-viewport/builds/standalone/. Regrettably, the v4 demo does not work anymore since the latest viewport builds no longer support pixi v4. I removed the reference.
