### ISSUE TITLE
Incorrect behaviour after changing PIXI resolution

### ISSUE THREAD

**Issue by nazywamsiepawel** [davidfig/pixi-viewport#326]
Hi,

I instantiate pixi-viewport as follows:

```typescript
this.viewport = new Viewport({
    screenWidth: window.innerWidth,
    screenHeight: window.innerHeight,
    worldWidth: 1000,
    worldHeight: 1000,
    noTicker: false,
    interaction: this.app.renderer.plugins.interaction,
});
```

```typescript
 this.viewport
    .pinch()

    .wheel({ smooth: 3 })
    .clampZoom({
      minWidth: 300,
      minHeight: 300,
      maxWidth: 8000,
      maxHeight: 8000,
    })
    .drag()
    .decelerate();
```

I allow my users to change resolution of the game to accommodate for older computers:
```typescript
this.app.renderer.resolution = props.resolution;
```

Unfortunately, if I change the resolution during the game play it seems to have an adverse effect on the viewport's interaction. Zooming in/out happens with a wrong offset and completely stops working when I set the resolution to 2. Dragging also becomes very erratic. 

Question is - when changing the resolution, is there anything specific I need to update separately in the viewport as well?

Thank you!

**Comment by nazywamsiepawel** [comment]
Please excuse a void issue - this has been fixed by adding:

`this.app.renderer.plugins.interaction.resolution = props.resolution;`

PIXI's interaction manager needs to updated separately.

**Comment by axmad22** [comment]
yes I had same issue at startup with pixi Application config property **resolution: devicePixelRatio**

``` js
super({
      width: width,
      height: height,
      preserveDrawingBuffer: false,
      transparent: true,
      autoDensity: true,
      antialias: true,
      autoStart: true,
      resolution: devicePixelRatio,
      clearBeforeRender: true
    });
```

had to setup viewport with dividing by  devicePixelRatio;

``` js
 this.viewport = new Viewport({
      screenWidth: (app.view.width / devicePixelRatio),
      screenHeight: (app.view.height / devicePixelRatio),
      worldWidth: docWidth,
      worldHeight: docHeight,
      ticker: PIXI.Ticker.shared,
      interaction: this.renderer.plugins.interaction
    });
```
