### ISSUE TITLE
No longer working with latest PIXI.js (6.1.2)

### ISSUE THREAD

**Issue by jurex** [davidfig/pixi-viewport#333]
Error when building, angular 12, pixi.js 6.1.2, pixi-viewport 4.32.0: 

```
Error: node_modules/pixi-viewport/index.d.ts:4:15 - error TS2459: Module '"@pixi/interaction"' declares 'IHitArea' locally, but it is not exported.

4 import type { IHitArea } from '@pixi/interaction';
                ~~~~~~~~

  node_modules/@pixi/interaction/index.d.ts:18:19
    18 declare interface IHitArea {
                         ~~~~~~~~
    'IHitArea' is declared here.
```

It looks like `@pixi/interaction` doesn't export `IHitArea` type anymore.

**Comment by dvail** [comment]
More context if it helps those more familiar: it looks like `@pixi/interaction` dropped the export of `IHitArea` with [this PR](https://github.com/pixijs/pixijs/pull/7213). The breaking change first happens in PIXI v6.1.0. https://github.com/pixijs/pixijs/blob/v6.1.0/packages/interaction/src/interactiveTarget.ts

**Comment by davidfig** [comment]
Is this still happening? I'm not getting this error on building. Anyone else seeing any problems with drag with newest build?

**Comment by mcdenhoed** [comment]
PIXI 6.2 has been released, which has eliminated this issue.

**Comment by jurex** [comment]
It's working again with PIXI 6.2, thanks everyone
