### ISSUE TITLE
snap and snapZoom

### ISSUE THREAD

**Issue by devexus** [davidfig/pixi-viewport#338]
I want to fit viewport to the sprite height and also center it to sprite width/2.
I tried to use scale method and it works but right now I don't know how to center it correctly. 

```javascript
    const width_scale = this.app.view.width / sprite.width;
    const height_scale = this.app.view.height / sprite.height;

    const scale = Math.min(width_scale, height_scale);
    
    this.viewport.scale.set(scale);
```

How can I use snap and snapZoom to get result like on the second screen?

black: canvas
green: sprite

<img width="609" alt="first" src="https://user-images.githubusercontent.com/47736308/132772772-87e38eda-91c1-478a-bc23-1f8e19e0176a.png">

<img width="533" alt="second" src="https://user-images.githubusercontent.com/47736308/132772757-64e8ee11-4b74-46aa-8582-e044fd995b18.png">

**Comment by davidfig** [comment]
Use something like `viewport.center(sprite.x / 2 + sprite.width / 2, sprite.y / 2 + sprite.height / 2)` (assuming the sprite.anchor = 0). You can also use the viewport.fit() command if you don't want to calculate the scale yourself.

Snap and SnapZoom work with the above center value and scale or size values.

**Comment by devexus** [comment]
Thank you for your reply but I still don't get it how to use snap and snapZoom to fit viewport to the sprite. Could you show me how to do it on the playground? I did an example.
https://codepen.io/devexus/pen/yLXMrEv

**Comment by davidfig** [comment]
Use this code:
```js
let app = new PIXI.Application({
  width: 1000,
  height: 500,
  transparent: false,
  antiailising: true,
  view: document.querySelector("#canvas")
});

...

viewport.snap(cat.x + cat.width / 2, cat.y + cat.height / 2)
viewport.snapZoom({ height: cat.height })
```

You need to set the renderer to the same as the viewport's screen size (or vice-versa) for it to work properly.

**Comment by devexus** [comment]
Thank you very much :)
