### ISSUE TITLE
Mouse click detection

### ISSUE THREAD

**Issue by devexus** [davidfig/pixi-viewport#344]
Hello, how can I get an information about which mouse button has been clicked?
I tried to use "mousedown" listener but i get button: -1 for left click and middle click.

![image](https://user-images.githubusercontent.com/47736308/134805372-e21cddbc-d854-4235-b5f9-1f5720cf5ce2.png)

**Comment by davidfig** [comment]
Look at data.originalEvent

**Comment by devexus** [comment]
![image](https://user-images.githubusercontent.com/47736308/134808746-744f628a-efa5-40c1-bcf0-21c0ba34d6ae.png)
There is button: -1 too :/

**Comment by devexus** [comment]
There is "which" property in originalEvent
