### ISSUE TITLE
Typescript viewport event handler does not exist

### ISSUE THREAD

**Issue by Rekkyn** [davidfig/pixi-viewport#345]
Hello, I'm trying to add an event handler to a viewport like so
```const viewport = new Viewport().on("clicked", () => {});```
But I'm getting the Typescript error `Property 'on' does not exist on type 'Viewport'.`

Is this method missing from the Viewport's Typescript definition? Thanks!

**Comment by davidfig** [comment]
It shouldn't be. You can take a look at the index.d.ts file.

**Comment by FrankiePo** [comment]
It seems you've imported wrong viewport

**Comment by Rekkyn** [comment]
I'm not seeing any `on()` functions in the index.d.ts file.

I'm importing it like `import { Viewport } from "pixi-viewport";` and everything else is working ok so I think I have the right import. If I cast the viewport as `any` and use the `on()` method it works ok, so it seems to be just a missing type.

**Comment by Rekkyn** [comment]
Turns out the problem was not having `"esModuleInterop": true` in my tsconfig.json file. Adding that fixed the type error.

**Comment by kitety** [comment]
I get the same problem

**Comment by matthewbordas** [comment]
I just pulled the latest version `4.34.1` and am still seeing this error. I also have `"esModuleInterop": true` in my tsconfig, but that didn't help

**Comment by davidfig** [comment]
That's weird. Viewport extends PIXI.Container which has on() defined.

**Comment by matthewbordas** [comment]
Can you point me to the line where it's defined? I'm not seeing it in [display/Container.ts](https://github.com/pixijs/pixijs/blob/dev/packages/display/src/Container.ts) (assuming that's the correct interface).

**Comment by davidfig** [comment]
https://github.com/pixijs/pixijs/blob/dev/packages/display/src/DisplayObject.ts

**Comment by matthewbordas** [comment]
Ahh ok so the project was on an older version. It's now fixed after upgrading from `v5.3.3` -> `v6.2.0`. Thanks so much for the help!
