### ISSUE TITLE
Viewport hitArea is affected by viewport transforms

### ISSUE THREAD

**Issue by qwertysam** [davidfig/pixi-viewport#35]
When the viewport is moved or dragged, the underlying hitArea for firing events moves with it.

E.g. I have a viewport with a box drawn with the top-left corner at 0, 0. Currently, I can click anywhere and the mouse click will fire the desired events.
![1](https://i.imgur.com/AQBZyHd.png)
Then I drag my viewport to the top and to the left...
![2](https://i.imgur.com/3nqXzla.png)
Now I can only trigger events by clicking this area (highlighted in blue)
![3](https://i.imgur.com/ys4r5C3.png)
  
# In addition to this
scaling of the viewport has the same effect. Zooming out makes the hitArea smaller on the user's screen and zooming in makes it larger

**Comment by davidfig** [comment]
Now I remember why I originally disliked PIXI.interactive. The way to fix this may be to add a default option to keep hitArea covering the entire screen. I'm already recalculating hitArea on every move, so this won't cost anything.
