### ISSUE TITLE
Weird clamping behavior

### ISSUE THREAD

**Issue by Arch-Storm** [davidfig/pixi-viewport#351]
When setting clamp() and clampZoom(), the canvas seems to jump between the two. Here is a simple example of what i mean: [https://codesandbox.io/s/purple-resonance-1nchg?file=/src/index.js](https://codesandbox.io/s/purple-resonance-1nchg?file=/src/index.js)

When zooming in, you can pan the viewport outsides the canvas, but as soon as the zoom is < 1, it clamps the pan to the center and panning is no longer possible. I don't know if this is supposed to happen considering the arguments set, but it still feels very weird.

I would expect the viewport to still be draggable if zoomed out, or to have it snap in at least smoothly.

**Comment by davidfig** [comment]
Try playing with options.underflow to see if that helps.
