### ISSUE TITLE
PIXI.GRAPHICS containsPoint broken after dragging/zooming 

### ISSUE THREAD

**Issue by peili** [davidfig/pixi-viewport#353]
**containsPoint** doesn't work reliable after dragging/zooming viewport.
https://pixijs.download/dev/docs/PIXI.Graphics.html#containsPoint

**Comment by davidfig** [comment]
That's weird. It should work fine as viewport only changes pixi's normal transforms. If you can show a sample project that shows this bug, I can take a look.

**Comment by peili** [comment]
@davidfig 
Looks like applyInverse is causing the issue. Because calling .graphics._geometry.containsPoint() directly works reliable.

`this.worldTransform.applyInverse(point, Graphics._TEMP_POINT);`

https://github.com/pixijs/pixijs/blob/79f5a950de0fbabc07ee0a931c04b99d4c9fcc41/packages/graphics/src/Graphics.ts#L1106

**Comment by davidfig** [comment]
Where are you getting the point from? It should be the event coordinates, not the world coordinates.

**Comment by peili** [comment]
> Where are you getting the point from? It should be the event coordinates, not the world coordinates.

That was causing the issue. Thank you for pointing that out.
