### ISSUE TITLE
Mouse interactions outside world

### ISSUE THREAD

**Issue by mariom91** [davidfig/pixi-viewport#354]
Hi,

We have a problem with dragging. The initial rendering works perfectly. The viewport and everything within (in this case the grid) is shown and interactable.

![image](https://user-images.githubusercontent.com/4806303/141822952-2d7fb593-3dc6-4feb-a921-d82b72c29907.png)
Interaction with PIXI.Graphics objects and the viewport dragging work perfectly. However, if you mouse drag the viewport, as shown in the screenshot above, you can't interact with anything outside the area of the world.

![image](https://user-images.githubusercontent.com/4806303/141822698-877a8e30-571d-4001-bd8b-677a3f3bcfcd.png)
After dragging any interaction doesn't work anymore.  E.g. the dragging feature of this library as well as the pixi events (like mousedown etc.) won't work anymore in the marked area. Objects are still being rendered, just not interactable.

We already compared our stuff to your example (https://davidfig.github.io/pixi-viewport/). In the example our use-case works perfectly. We tried to implement it nearly identical, with a few deviations because we use Angular, but unfortunately we had no success.

Do you have any ideas or suggestions how to fix this? Thanks for any help.

Best regards,
Mario

**Comment by davidfig** [comment]
Hmm...the dragging and interactions should still work even in the area outside your world (as long as it's on pixi's canvas). Does `application.stage.on('mousedown', () => console.log('hi'))` work outside of the viewport?

**Comment by mariom91** [comment]
Thanks for the fast answer. I just tried it and no, its actually not working outside the viewport. Clicking in the marked area of the second screenshot does not trigger the mousedown event. 

This is the code i tried it with:
![image](https://user-images.githubusercontent.com/4806303/142018713-aabbf371-7c84-42bf-a1a0-29e286207d68.png)

**Comment by davidfig** [comment]
Set `stage.interactive = true` and then try.

**Comment by mariom91** [comment]
Okay, i found the issue:

![image](https://user-images.githubusercontent.com/4806303/142020122-199b5af8-6207-4438-94b8-ba33969a7097.png)

A colleague disabled the ticker and this is the reason why it doesn't work. Everything works fine when i remove this line. I'm going to ask him why he did that, but we can figure that out.

Thank you for your help and the nice work!
