### ISSUE TITLE
Blurry text?

### ISSUE THREAD

**Issue by SlimEconomy** [davidfig/pixi-viewport#358]
I used pixi-viewport in the hope that the zooming would be sharp. Now I am facing the problem of blurry text and other elements when zooming in. Is the best solution to just redraw everything on every zoom? When I redraw the entire scene on a zoom, there is just that delay where u can't see a picture for a split second. This really is not user friendly.

**Comment by davidfig** [comment]
Yes, you'll need to rescale the text when zooming to avoid blurry text. Pixi is a raster renderer, not a vector renderer. If you use something like SVG then this is handled for you.

Do something like this:

`viewport.on('zoomed', () => rescaleText())`

Depending on how you're rendering your text, you can also render it at a higher resolution and then scale it down to avoid having to rescale it too often.

**Comment by SlimEconomy** [comment]
Do you know a solution to that delay that happens when you remove all children and add them back to the stage? The drawing disappears for a split second since this process is not instant. I tried to scale the picture with a lower resolution while I remove and all the children to the stage but that didn't work out. There was still the drawing going missing for a split second

**Comment by SlimEconomy** [comment]
> Yes, you'll need to rescale the text when zooming to avoid blurry text. Pixi is a raster renderer, not a vector renderer. If you use something like SVG then this is handled for you.
> 
> Do something like this:
> 
> `viewport.on('zoomed', () => rescaleText())`
> 
> Depending on how you're rendering your text, you can also render it at a higher resolution and then scale it down to avoid having to rescale it too often.

Do you know a solution to that delay that happens when you remove all children and add them back to the stage? The drawing disappears for a split second since this process is not instant. I tried to scale the picture with a lower resolution while I remove and add all the children to the stage but that didn't work out. There was still the drawing going missing for a split second

**Comment by davidfig** [comment]
You are drawing too slowly and hitting a frame refresh while drawings (this happen when requestAnimationFrame triggers and pixi renders before you complete your redraw). I'm not sure how your scaling your text, but if you have a lot of text and you use pixi.text, you'll have performance issues since pixi.text creates textures using canvas. Try using pixi.bitmaptext instead.

**Comment by SlimEconomy** [comment]
> You are drawing too slowly and hitting a frame refresh while drawings (this happen when requestAnimationFrame triggers and pixi renders before you complete your redraw). I'm not sure how your scaling your text, but if you have a lot of text and you use pixi.text, you'll have performance issues since pixi.text creates textures using canvas. Try using pixi.bitmaptext instead.

Using your "zoomed-end" event really helped me achieving what I was trying to achieve. The image is still scaled but updated with the rerendered drawing afterwards. The image doesn't disappear and that's awesome. Can you maybe tell me how you guys implemented the "zoomed-end" event? Like on what actual event does it rely on?

**Comment by davidfig** [comment]
You can look at the source code at https://github.com/davidfig/pixi-viewport. zoomed-end is tied into the interactions controller. It waits until after you finish interacting with the viewport and then triggers the event.

**Comment by SlimEconomy** [comment]
> You can look at the source code at https://github.com/davidfig/pixi-viewport. zoomed-end is tied into the interactions controller. It waits until after you finish interacting with the viewport and then triggers the event.

I am struggling with an issue the whole day and I don't know how to overcome it.
What I am doing right now is redrawing the whole stage inside the "zoomed-end" event which works fine. But the problem is since I redraw all elements with the factor given to me by the library (viewport.scaled), it shifts the elements to the right and bottom of the viewport. So my idea was to just readjust the viewport, so that it looks like nothing was redrawn in the background, like nothing even changed besides the library scaling the image. 
What I tried is moving the viewport by the difference:
```
viewport.removeChildren();
redraw(); //everything scaled by viewport.scaled
viewport.x += viewport.x * viewport.scaled- viewport.x;
viewport.y += viewport.y * viewport.scaled- viewport.y;
```
But this still moves the viewport where it should not be.

**Comment by davidfig** [comment]
You don't want to scale everything on redraw. You want to render the text at a higher resolution and scale the text down so it's the same size and same position as the original text.

**Comment by SlimEconomy** [comment]
> You don't want to scale everything on redraw. You want to render the text at a higher resolution and scale the text down so it's the same size and same position as the original text.

That was my bad, I didn't mean scaling as in using the scale function from pixi. I meant multiplying every x and y coordinate of every element to simulate a zoom. Thus they have a better resolution than using the built in scale from pixi

**Comment by davidfig** [comment]
You're recreating the transforms by manually scaling everything. It's possible, but you'll have to figure out the maths. My suggestion would be to rely on pixi's transforms instead of manually transforming, and to fix the text, create a larger text object and scale it down by 1 / newScale. You'll improve the resolution without having the manually handle transforms. For example, if you try to rotate anything, your manually scaling will not work properly.

**Comment by SlimEconomy** [comment]
> You're recreating the transforms by manually scaling everything. It's possible, but you'll have to figure out the maths. My suggestion would be to rely on pixi's transforms instead of manually transforming, and to fix the text, create a larger text object and scale it down by 1 / newScale. You'll improve the resolution without having the manually handle transforms. For example, if you try to rotate anything, your manually scaling will not work properly.

It's not only about text in my case. Lines also become thicker when scaled and I don't want that either.

**Comment by davidfig** [comment]
You can change lineWidth on graphics when zoomed as well. But if you prefer to do it manually, then the math is more complicated. I can't off the top of my head provide it, though.

**Comment by SlimEconomy** [comment]
> You can change lineWidth on graphics when zoomed as well. But if you prefer to do it manually, then the math is more complicated. I can't off the top of my head provide it, though.

Alright, thank you

**Comment by phschaad** [comment]
For anyone else with this issue, you can set the `resolution` for PIXI `Text` elements. It works really well to just set the resolution to the current scale. So for any given text `myText`, you can simply do the following:

```
viewport.on('zoomed', () => {
    myText.resolution = viewport.scaled;
});
```

**Comment by SlimEconomy** [comment]
> You can change lineWidth on graphics when zoomed as well. But if you prefer to do it manually, then the math is more complicated. I can't off the top of my head provide it, though.

Sadly I can't get the lineWidth under 1 when zoomed in. Is the correct way of changing the lineWidth of a graphic by calling lineStyle() on it again?

> For anyone else with this issue, you can set the `resolution` for PIXI `Text` elements. It works really well to just set the resolution to the current scale. So for any given text `myText`, you can simply do the following:
> 
> ```
> viewport.on('zoomed', () => {
>     myText.resolution = viewport.scaled;
> });
> ```
> 
> For performance reasons I would clamp the resolution to something like a maximum of 30, beyond this zoom level you're not going to notice a difference anyway.

I did that but the text is jumping a bit when I am adjusting the resolution to the scalefactor. Any ideas?

**Comment by caramelCookie** [comment]
I post this message here, because I feel that it is in line with the previous discussion. I'm also using the viewport and I'm having issues with sharpness/bluriness on svg.

I have containers that contains sprite based on svg texture. 
If I understand correctly I need to refresh the svg thanks to the 'zoomed-end' event.

So : 
1) remove all sprites from viewport wich delete the containers 
this.viewport.on('zoomed-end', (e) => {
      this.viewport.removeChildren();
     // TODO re-add the children but with a better resolution
      addChildren()
    });

2) put back the sprites on the containers by changing the resolution ...
addChildern() {
...
const sprite = PIXI.Sprite.from(<svg-src>, {resolution: this.viewport.scaled});
...
}

I have tried the code above but it doesn't change anything to the sharpness of the svg images.
Any help would be appreciated
