### ISSUE TITLE
Mouse tracking 

### ISSUE THREAD

**Issue by kevinz917** [davidfig/pixi-viewport#360]
I'm trying to track the exact position of the mouse relative to the item that's been dragged under the viewport. I know that this provides the coordinates of your mouse after the drag:

```
viewport
   .drag()
   .on('drag-end', (screen, word) => console.log(screen, world))
```

 but how can I calculate the mouse position when it hovers over at all times? Thank you

**Comment by davidfig** [comment]
You can listen to the pointermove function on the viewport (https://pixijs.download/release/docs/PIXI.Container.html#pointermove)

**Comment by kevinz917** [comment]
> 

Thank you! The API returns ```originalEvent``` which gives me data on the global state. Is there a way to output the "local" coordinate relative to how much the viewport has been dragged? I need that coordinate to correctly highlight the tile sprite I'm hovering over. Thank you.

**Comment by davidfig** [comment]
Use the `e.data.global` as the coordinate for any conversion, eg, `viewport.toWorld(e.data.global)`

**Comment by kevinz917** [comment]
> Use the `e.data.global` as the coordinate for any conversion, eg, `viewport.toWorld(e.data.global)`

Got it, thank you! that worked. Was also wondering if you have any tips on optimizing for performance in cases involving mouse movement. In my example I have a ParticleContainer containing 10,000 tiled objects for the background of the map, and by tracking mouse position I want to highlight a specific one.

**Comment by davidfig** [comment]
I would stay away from pixi's interaction library (I have found it rather slow). Couple thoughts off the top of my head:

1. set a dirty flag and only do the check once a frame (mousemove can trigger more than once per frame)
2. make sure you're not calling sprite.width/height as it will perform calculations; instead save the boundingBox to a local variable
3. intersections checks for a point in a box for 10,000 is doable from a performance perspective
4. but if performance is still not great then you can use a spatial hash to break up the objects. This will significantly decrease the number of intersect checks as you'll only have to check a subset for the intersection

Then you just need to track the last highlighted object and turn the highlight off and the new highlight on (if there's an intersection).

Good luck!

**Comment by kevinz917** [comment]
> I would stay away from pixi's interaction library (I have found it rather slow). Couple thoughts off the top of my head:
> 
> 1. set a dirty flag and only do the check once a frame (mousemove can trigger more than once per frame)
> 2. make sure you're not calling sprite.width/height as it will perform calculations; instead save the boundingBox to a local variable
> 3. intersections checks for a point in a box for 10,000 is doable from a performance perspective
> 4. but if performance is still not great then you can use a spatial hash to break up the objects. This will significantly decrease the number of intersect checks as you'll only have to check a subset for the intersection
> 
> Then you just need to track the last highlighted object and turn the highlight off and the new highlight on (if there's an intersection).
> 
> Good luck!

Thank you! it worked.
