### ISSUE TITLE
How can i add grid at the viewport

### ISSUE THREAD

**Issue by zhuxindaba** [davidfig/pixi-viewport#363]
![image](https://user-images.githubusercontent.com/17308154/148010231-7265a090-e144-43c7-a28c-aece51d198b7.png)

Could i implement above scene across pixi-viewport?

**Comment by spassvogel** [comment]
That's something you would do in pixi. Maybe start here: https://www.pixijselementals.com/#graphics

**Comment by zhuxindaba** [comment]
I wonder if pixi-viewport can support this feature through option configuration?

**Comment by davidfig** [comment]
There's no built in support for grids. It's relatively easy to implement. Listen in on the "zoomed" or "moved" instruction, and draw vertical and horizontal lines. You can use the viewport.getVisibleBounds() to get the start and end of the line, and do the math for where to start the lines.

**Comment by jasonsturges** [comment]
@zhuxindaba I created something similar - pixi graph paper:

![pixi-graph-paper](https://user-images.githubusercontent.com/1213591/109711264-4a64d400-7b64-11eb-97bd-5472bd9f6453.gif)

- GitHub: https://github.com/jasonsturges/pixi-graphpaper
- Code Sandbox: https://codesandbox.io/s/pixi-graph-paper-xn2rm

NPM module if you want to try it out.

**Comment by davidfig** [comment]
Super cool!
