### ISSUE TITLE
documentation on resize() is missing args

### ISSUE THREAD

**Issue by bencresty** [davidfig/pixi-viewport#370]
Minor thing, but can prevent confusion with others: According to the documentation the resize() method doesn't have arguments, but there are four arguments in the code.

https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html#resize

**Comment by davidfig** [comment]
Thanks! The docs should be updated now.

**Comment by bencresty** [comment]
@davidfig thanks!
