### ISSUE TITLE
moveCenter() missing in docs

### ISSUE THREAD

**Issue by bencresty** [davidfig/pixi-viewport#371]
The `moveCenter()` method is missing in the docs at https://davidfig.github.io/pixi-viewport/jsdoc/Viewport.html , eventhough the method can be found in the code which is used to create the docs. Looks like the jsdoc is missing on that method.

**Comment by davidfig** [comment]
Thanks. There were a few functions missing from the docs after the typescript conversion. They should be fixed now.

**Comment by bencresty** [comment]
Thanks for the quick action!
