### ISSUE TITLE
zoomPercent() doesn't trigger zoomed event

### ISSUE THREAD

**Issue by bencresty** [davidfig/pixi-viewport#375]
As title; when setting a zoom with `zoomPercent()` the `zoomed` event (and the `zoomed-end` event) is not triggered. This is causing logic that needs to counter-scale or update something with the viewport scaling missing the event to update itself.

[edit] When doing more testing I see that there is a difference between hitting the method once and keep on triggering the method during an animation. When triggering the method once it works and the zoom events get triggered, but when doing it from within an animation (see code below) it doesn't trigger events. Obviously also when triggered from an animation events should be triggered. Not sure why that's not the case right now. 

This is the code that doesn't trigger the events. It's used to animate zoom while holding a button.

``` javascript
const delta = 0.01;

this._tween = gsap.to({}, {
    duration: 1,
    repeat: -1,
    onUpdate: () => {
        this.vp.zoomPercent(delta, true);
    },
});
```

pixi-viewport: 4.34.4

**Comment by davidfig** [comment]
If i remember correctly, events are not fired if you directly manipulate the viewport. The events are only fired after a user initiated event (like drag). You'll need to add a `viewport.emit('zoomed-end')` after your zoomPercent call if you need the event handled.

**Comment by bencresty** [comment]
Thanks for your response. 

> If i remember correctly, events are not fired if you directly manipulate the viewport. 

That doesn't seem to be the case tho; it IS triggering the zoom event when calling `zoomPercent()` just on, let's say, a button click. But it is NOT triggering for some weird reason when `zoomPercent()` is being called within an animation loop/update (see above gsap example). That doesn't make any sense to me.

Of course I know how to work around this in our code to fix this issue, but that's obviously not the way to go. Especially because it will then fire twice the event when this issue is fixed in a later version of the viewport.

**Comment by davidfig** [comment]
Ah! Do you have clampZoom set? There is a clamp call in zoomPercent that will emit if clamp is used. Otherwise it doesn't clamp. That's a bug and as it shouldn't emit from a programmatic change. I probably won't have time to fix it but happy to accept a PR. Probably just need to add a `noEmit: boolean` option to the `clampZoom.clamp()` function.

**Comment by bencresty** [comment]
Thanks again @davidfig . I'm indeed using `clampZoom` to set a minimum scale, but when removing ALL 'plugins' on the viewport  (including the `clampZoom()`) there's still no `zoomed` or `zoomed-end` event being triggered during the animation.
So guess it's not the `clampZoom()`-'bug' you described. Unfortunetely. Or the bug you described goes further than `clampZoom()` alone?

**Comment by davidfig** [comment]
I'm not sure why your animation system would stop the event from triggering. Again, I still don't think the event should trigger as it is a programmatic change and not a user-initiated event. But there's definitely some misses on covering all cases with that approach. You'd have to trace the code in your animation loop to see the difference in why the event is not being emitted.

**Comment by bencresty** [comment]
@davidfig you are clearly not reading my posts. Also you must be the first one I ever meet working with pixiJs that doesn't know Greensock Gsap This is not 'my' animation system, it's a well proven animation system used by a huge number of developers all over the world for lots of years.

Also I wrote a few times now that the method DOES fire, but only when triggered once under a button. Not when triggered from within an animation. 

It's pretty difficult to communicate to some one that doesn't even read my posts. I give up.

**Comment by bencresty** [comment]
Wow, so this is how you handle people mentioning bugs, right?

First act like you don't get it and frustrate the issue mentioner who tries to explain the issue again and again, eventhough it was already clear in the opening post and I kept taking the time to explain again and again.

And then just close the issue, while the bug is still there? Only because I pinpoint what's happening here?

Very mature and professional to act like an issue isn't there.
