### ISSUE TITLE
Display issue when zoom too small

### ISSUE THREAD

**Issue by zhouccccc** [davidfig/pixi-viewport#377]
Hi David，I met one problem about displaying. the following two pic is the detail:

![image](https://user-images.githubusercontent.com/25141787/155933932-6b8a6a7d-b074-47cf-a18f-8cc03f908356.png)
![image](https://user-images.githubusercontent.com/25141787/155934023-c2632449-6078-41ee-a30a-ccd2c5ba7155.png)

The first is normal, but if keep zooming out，some sprite  will not visible as you seen. I guess  it could be "width is less than 1 px"
Can this be fixed?

**Comment by davidfig** [comment]
Did you check out https://github.com/pixijs/graphics-smooth? I just found it and it might help. There's a discussion here: https://github.com/pixijs/pixijs/issues/7511

**Comment by zhouccccc** [comment]
Thanks for your reply. I will try it tomorrow！：）



发自我的iPhone


------------------ Original ------------------
From: David Figatner ***@***.***&gt;
Date: Mon,Feb 28,2022 8:14 PM
To: davidfig/pixi-viewport ***@***.***&gt;
Cc: zhouccccc ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [davidfig/pixi-viewport] Display issue when zoom too small (Issue #377)





 
Did you check out https://github.com/pixijs/graphics-smooth? I just found it and it might help. There's a discussion here: pixijs/pixijs#7511
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhouccccc** [comment]
> Did you check out https://github.com/pixijs/graphics-smooth? I just found it and it might help. There's a discussion here: [pixijs/pixijs#7511](https://github.com/pixijs/pixijs/issues/7511)

I didn't know this lib before. I try it just now and it can resolve my problem perfectly.
Nice pixi-viewport! Nice graphics-smooth!
