### ISSUE TITLE
Not working with new `cullable` property from `PIXI 6.3.0`.

### ISSUE THREAD

**Issue by Ayfri** [davidfig/pixi-viewport#381]
Hi, for a project, I have a big viewport with a lot of sprites inside, and I have activated the `zooming` plugin. All the sprite have `sprite.culling = true` but if I zoom in/out, I have the same performances, like it was doing nothing.

**Comment by davidfig** [comment]
Try it with normal sprites. It may be that tilemap isn't supported by cullable?

**Comment by kurtwaldowski-echelon** [comment]
@Ayfri Any updates on this?

**Comment by Ayfri** [comment]
Mh yes it seems that it is `pixi-tilemap`, I tested by replacing my renderer using `pixi-tilemap` to using `SimplePlane` with culling on and I see differences when zooming in & out.
