### ISSUE TITLE
Unable to add Viewport to Stage (TS Type Definition)

### ISSUE THREAD

**Issue by ktwrd** [davidfig/pixi-viewport#383]
When trying to add PIXI Viewport to an applications stage when using typescript. It seems like it's very similar to the error in [#348](https://github.com/davidfig/pixi-viewport/issues/348) which is
```
src/engine.ts:124:41 - error TS2345: Argument of type 'Viewport' is not assignable to parameter of type 'DisplayObject'.
  Property '_maskRefCount' is missing in type 'Viewport' but required in type 'DisplayObject'.

124         this.Application.stage.addChild(this.Viewport)
```

The dependencies used are;
```json
"dependencies": {
    "events": "^3.3.0",
    "pixi-viewport": "^4.34.4",
    "pixi.js": "^6.2.2"
},
"devDependencies": {
    "@types/events": "^3.0.0",
    "@types/offscreencanvas": "^2019.6.4",
    "typescript": "^4.6.4"
}
```

The code can be found at [eplengine/tree/pixi-viewport](https://github.com/ktwrd/EPLEngine/blob/pixi-viewport/src/engine.ts#L124).

**Comment by kurtwaldowski-echelon** [comment]
@ktwrd Did you get this resolved?

**Comment by JeffBaumgardt** [comment]
May I ask what target version of pixi.js is the current release (4.35.0)? I am also getting this error and I'm trying to trackdown all the correct dependencies.

Currently I have
```json
{
  "dependencies":
    "@pixi/filter-adjustment": "^4.2.0",
    "@pixi/filter-glow": "^4.2.0",
    "@pixi/filter-multi-color-replace": "^4.2.0",
    "pixi-viewport": "^4.35.0",
    "pixi.js": "^6.5.1",
}
```

**Comment by ktwrd** [comment]
@kurtwaldowski-echelon Sorry for the late response, yes this did fix the problem. Thank you very much!! <3
