### ISSUE TITLE
Zooming while dragging send viewport off far from origin

### ISSUE THREAD

**Issue by harrycollin** [davidfig/pixi-viewport#384]
I noticed a strange behaviour that happens while zooming and dragging simultaneously using the middle mouse button. The viewport seems to suddenly fly away towards the world origin (0, 0).  

I'm activating plugins in this order: 
`
this.viewport.drag().pinch().wheel().decelerate();
`

In this example the viewport starts at x: 50000, y: 500000 and suddenly fly's to near x: 0, y: 0. 

https://user-images.githubusercontent.com/10602138/168631427-a72df31e-bccb-44ee-b699-f01b49ea5fb8.mp4

**Comment by davidfig** [comment]
Ah. This looks like a bug, probably in the decelerate plugin.
