### ISSUE TITLE
Wheel dragging doesn't  respect drag properties

### ISSUE THREAD

**Issue by kurtwaldowski-echelon** [davidfig/pixi-viewport#385]
When using "wheel" to allow dragging / panning of the view, a trackpad can be used to pan around the view and this works beautifully. However, the issue is that this isn't treated as a drag as far as the viewport is concerned. 

For example:

1. Drag events are not fired when the viewport beings "dragging" view the touchpad 
2. When swiping the track pad, the view will decelerate and doesn't respect the friction value set by decelerate

**Comment by davidfig** [comment]
This doesn't use the decelerate plugin. The trackpad is decelerating when you scroll. The pixi-viewport's moved events should be triggered by this action.

**Comment by kurtwaldowski-echelon** [comment]
Thanks!
