### ISSUE TITLE
update pixi.js to work with v6.5

### ISSUE THREAD

**Issue by stevensnoeijen** [davidfig/pixi-viewport#391]
Atm there are breaking changes to the DisplayObject.
I want to create a PR to upgrade the pixi.js version and fix breaking changes in the code of pixi-viewport.

But first https://github.com/davidfig/pixi-viewport/pull/392 needs to be accepted to create this new pr.

**Comment by davidfig** [comment]
all merged. i'll publish the upgraded package today.

**Comment by stevensnoeijen** [comment]
Fixed in [4.35.0](https://github.com/davidfig/pixi-viewport/releases/tag/4.35.0) :)
