### ISSUE TITLE
Clicked event is sometimes emitted multiple times

### ISSUE THREAD

**Issue by rkgrep** [davidfig/pixi-viewport#40]
In some cases the event is fired twice or more per one click

```
viewport.on('clicked', ({ screen, world }) => {
  console.log(world)
});
```

![2018-01-29_17-15-39](https://user-images.githubusercontent.com/2423048/35505243-18c4125a-0518-11e8-8484-e10d025d1d25.png)

**Comment by davidfig** [comment]
I think I found the bug. Try npm v1.1.5 and let me know if you still see it. Thanks!
