### ISSUE TITLE
Memory leak in drag plugin

### ISSUE THREAD

**Issue by blnvdanil** [davidfig/pixi-viewport#402]
Hi! I have noticed memory leak in `drag()` plugin. [Here](https://github.com/davidfig/pixi-viewport/blob/8aa88ef330c4fc65a35d032f1f6a8759d8b42710/src/plugins/Drag.ts#L191) is the code that sets up event listeners for `keyToPress` flag, but there is no destroy method implemented in `drag()` plugin. As a result if I will change `keyToPress` flag many times (in a way i described below), there will be may event listeners on `window`.

I may be doing something wrong, but when I want to change `options` of the `drag()` plugin (or whatever), I should just run `viewport.drag(newOptions)`, am I right?

**Comment by davidfig** [comment]
Yes, you replace the plugins by rerunning the same plugin with different options. There is also a viewport.plugins.remove (or something like that) function where you can manually remove plugins.

Ugh. Yes, that's definitely an event listener leak. The event listener should be saved and then cleared when destroy is called. (Although it's probably worth adding keydown and keyup handlers to InputManager and passing it to all plugins so we don't have to manage so many event listeners.) 

I'm happy to review a PR for either approach.

**Comment by blnvdanil** [comment]
I can not find where is the place where `destroy` method is called? When I run `drag(newConfig)`, PluginManager just creates new instance of the drag plugin [here](https://github.com/davidfig/pixi-viewport/blob/8aa88ef330c4fc65a35d032f1f6a8759d8b42710/src/PluginManager.ts#L71). I think that this is the place for calling `destroy`.

**Comment by davidfig** [comment]
Yup, you're right. The destroy method should be called in PluginManager's add, remove, reset, and removeAll. Let me know if you don't have time for a PR and I can pull it together.

**Comment by blnvdanil** [comment]
Why should destroy method be called in reset method?

**Comment by davidfig** [comment]
You're right, it shouldn't.
