### ISSUE TITLE
pixi.js@7 support

### ISSUE THREAD

**Issue by oyed** [davidfig/pixi-viewport#404]
v7 of pixi is out (woo!) - any plans/timeline on supporting it? InteractionManager seems to be the only potential issue for this library, though from what I read, it's a drop-in replacement so might just be a case of allowing `^7.0.0` for peer dependencies?

**Comment by davidfig** [comment]
Definitely want to support it. I've not had time to look at it yet. It should be straightforward (hopefully).

**Comment by bigtimebuddy** [comment]
@davidfig do you need help with this? Happy to help.

**Comment by davidfig** [comment]
Sure. I'm hoping it's straightforward, but I haven't had much time to look at the changes yet.

**Comment by bigtimebuddy** [comment]
The transition from InteractionManager to FederatedEvents is going to be the stickiest bit for this plugin (and is a breaking change). Also, we are encouraging everyone to publish ES2017 (which is now the default for v7). I recently converted `@pixi/layers` if that helps for some context: https://github.com/pixijs/layers/pull/88

**Comment by asciidiego** [comment]
@bigtimebuddy as someone who is new to the pixijs ecosystem and wanted to use it for a production case, which one of these is the best approach given your domain knowledge?

- start writing features using pixi v6 and then migrate;
- or start from v7 altogether and develop the project with the help of the community and extensive reading of the documentation, code, and issues?

thanks for such an amazing work!

**Comment by bigtimebuddy** [comment]
@asciidiego good question!

If you need stability and broad plugin support right now stick with v6. If you're looking for a more modern approach and more up-to-date features, then v7. It also probably depends slightly on when you're launching your project. Much of the v7 issues and upgrading plugins will likely get sorted in a month or two.

My hope is that more folks starting new projects use v7 and help us improve. The community especially on Discord is very helpful and generous.

If you do choose v6, I'd strongly recommend the latest 6.5.x version and implement using both `@pixi/events` and `@pixi/assets` as that will make moving to v7 easier.

**Comment by cuire** [comment]
I'm working on it right now, will send PR in a few days.

**Comment by zaalbarxx** [comment]
Hi, I'd like to ask if this issue is going to be resolved any time soon since I'm just about to start a new project with pixi and was wondering if I should stick to v6 for now or maybe it would be possible to make it work with v7 :) From what I see the dragging is working on v7, but scrolling/zooming does not.

**Comment by oyed** [comment]
Hey @davidfig - how soon might we be able to get #421 landed and a new version released?

**Comment by Heilemann** [comment]
@davidfig love Pixi-viewport so much, any update on this? I saw there's a v5, but it's barely documented and I'm having a heck of a time getting it up and running.
