### ISSUE TITLE
Project Refactoring

### ISSUE THREAD

**Issue by cuire** [davidfig/pixi-viewport#408]
I'm working on migrating project to pixiv7 and want to refactor it a bit.

#### General
- [x] Add `dist` to gitignore
- [ ] Switch to `vitest`
- [ ] Add e2e tests with `playwright`
- [x] Don't send `src` to npm package.
- [x] #352 

#### Code styling
- [x] Lint all files. (#410)
- [x] Add [prettier](https://prettier.io/).
- [x] Add a `lint:fix` script.
- [x] Add [husky](https://github.com/typicode/husky) commit hook to lint:fix files.

#### Docs site
- [x] Remove legacy examples.
- [x] Switch to separate package that is in same directory. And use `Vite` as build tool.

If these changes sounds fine to you, give me green light and I can help making it.

**Comment by davidfig** [comment]
These looks great!

**Comment by cuire** [comment]
It be much easier to switch to pixiv7 with these. 🥳

**Comment by cuire** [comment]
@davidfig, I have a few questions:

- What docs are legacy and can be removed?  And what needs to be updated.
- Does it need both [jsdoc](https://davidfig.github.io/pixi-viewport/jsdoc/) and [modules](https://davidfig.github.io/pixi-viewport/modules)?

**Comment by davidfig** [comment]
@cuira 

> What docs are legacy and can be removed? And what needs to be updated.
Love your thoughts on the docs files. The two that I use when developing are the docs/index and docs/original. I prefer the original for debugging, but I think the docs/index might be easier for people to play with the options? 

> Does it need both [jsdoc](https://davidfig.github.io/pixi-viewport/jsdoc/) and [modules](https://davidfig.github.io/pixi-viewport/modules)?
I like the jsdoc better than the modules, but I don't think there's any harm in keeping both.

> Does it need Build Examples, since code for examples stays same and bundlers have their own docs.
No. I created it as I switched between bundlers often. I'm not sure it even works any more.
