### ISSUE TITLE
Api doc down?

### ISSUE THREAD

**Issue by ggomaeng** [davidfig/pixi-viewport#419]
https://davidfig.github.io/pixi-viewport/jsdoc/ is giving a 404 error 🥹

**Comment by ThiagoMaxPavao** [comment]
Same here

**Comment by cuire** [comment]
@davidfig. It looks like you deployed, `docs` instead of `docs/dist/`.

Use https://davidfig.github.io/pixi-viewport/public/modules for now.

**Comment by davidfig** [comment]
Thanks. I was a bit too trigger happy with pushing to master. I reverted (and switched to a new main branch) until we sort out the v7 build.

**Comment by ggomaeng** [comment]
I feel you 🙌🏻  happy hacking david!
