### ISSUE TITLE
Drag stops when finger cross browser search bar, bottom toolbar. 

### ISSUE THREAD

**Issue by alexeymolchan** [davidfig/pixi-viewport#42]
I have basic setup with pinch, drag, bounce, clampZoom and decelerate plugins.

Everything works fine, until the moment when i drag the stage and drag-end triggered on mobile browser search bar or bottom toolbar (need exactly release the finger) - stage just stuck. Drag completely stops, but pinch still works.

Tested this on IOS Safari / Chrome and Android Chrome browsers.

**Comment by davidfig** [comment]
I was seeing something similar on drag. I think I tracked down the bug. Try out 1.1.6 and let me know if you're still seeing it.

**Comment by alexeymolchan** [comment]
@davidfig fixed, everything works fine.
