### ISSUE TITLE
Master lagging (npm) release

### ISSUE THREAD

**Issue by JoepSchyns** [davidfig/pixi-viewport#426]
The master branch is more recent than the latest release. This may be confusing, as for example people depend on pixi7+ but get pixi6+ in the package.

**Comment by hmpthz** [comment]
Yes, hopefully the latest pixi7 build can be published soon!

**Comment by spassvogel** [comment]
Yes that would be very nince indeed..

**Comment by jasonsturges** [comment]
@davidfig Hi, somewhat critical need to move to Pixi v7 for new Assets packages - Pixi Viewport continues to pull Pixi v6 for dependencies.  Any chance Pixi Viewport might be updated soon?

**Comment by hmpthz** [comment]
> @davidfig Hi, somewhat critical need to move to Pixi v7 for new Assets packages - Pixi Viewport continues to pull Pixi v6 for dependencies. Any chance Pixi Viewport might be updated soon?

Try this repo at the moment. https://github.com/davidfig/pixi-viewport/pull/428

**Comment by jasonsturges** [comment]
Is this project no longer maintained?
