### ISSUE TITLE
clicking becomes impossible after dragging outside the screen

### ISSUE THREAD

**Issue by zach-m** [davidfig/pixi-viewport#43]
I'm activating the viewport with drag(), pinch(), bounce(), wheel() and decelerate().

I start to drag normally, but make the drop outside the browser area (tried on iPhone Safari, but the same happens on Chrome when simulating a device).

From that point on, the viewport is neither clickable nor draggable (but strangely remains pinch-able), and the page has to be refreshed by the user.

I'm using version `pixi-viewport@1.1.5`

**Comment by zach-m** [comment]
I'm using version pixi-viewport@1.1.5

**Comment by alexeymolchan** [comment]
https://github.com/davidfig/pixi-viewport/issues/42 fixed here
