### ISSUE TITLE
Viewport causes server-side builds to fail

### ISSUE THREAD

**Issue by RJWadley** [davidfig/pixi-viewport#432]
pixi-viewport uses window at the module level, which makes it crash any build that uses server side rendering, for example Next and Gatsby. These frameworks build the app on the server with node, which has no window object. The build will fail with any import from the pixi-viewport, even if no viewport is created.

luckily, this is a pretty straightforward fix though, just need to check the type of window before using it like so:
`typeof window === "undefined" ? 0 : window.innerWidth`

this person ran into the same issue, but closed it: #398

**Comment by davidfig** [comment]
If you submit a PR, I can add the code.

**Comment by RJWadley** [comment]
@davidfig not sure if you saw this, but there's a pull request open for this: #434

**Comment by ahmafi** [comment]
Can we have this? This is kinda necessary for projects with SSR!

**Comment by himrocks33** [comment]
I agree this is necessary! Please merge.

**Comment by pietrovismara** [comment]
Was this released on NPM? I'm on v5.0.2 and I still get errors from the `window` references.

**Comment by Arsenalist** [comment]
I'm getting these errors too in NextJS 14. Wrapping it around `if (typeof window !== "undefined))` has not impact.
