### ISSUE TITLE
Adding custom attributes

### ISSUE THREAD

**Issue by jeg924** [davidfig/pixi-viewport#433]
I'm writing Cypress tests and it would be nice if I could add custom attributes as recommended in the Cypress docs:

https://docs.cypress.io/guides/references/best-practices#Selecting-Elements

Is there any chance of adding support for custom attributes in the future?

**Comment by davidfig** [comment]
The canvas element is created through pixi.js, not viewport.

**Comment by jeg924** [comment]
Ok, thanks for the explanation!
