### ISSUE TITLE
has no exported member 'Viewport' in 5.0.1

### ISSUE THREAD

**Issue by imxood** [davidfig/pixi-viewport#439]
vscode editor 1.76.2
pixi-viewport: ^5.0.1

Module '"pixi-viewport"' has no exported member 'Viewport'.

run is ok, only code prompt in vscode is wrong.

hovever pixi-viewport 4.38.0 is ok.

![image](https://user-images.githubusercontent.com/14890680/227667816-2119547c-ce76-427e-a09a-7e9841cc78f8.png)

**Comment by imxood** [comment]
When tscofig.js is configured like this, it is ok~

![image](https://user-images.githubusercontent.com/14890680/227700117-ee38d1c6-ced0-4f09-a9d2-94d23d21aea8.png)

**Comment by khoakomlem** [comment]
I think only "moduleResolution" should change to "node", but how about not changing the moduleResolution? My project is using the imports feature in Node>16 and couldn't import this library types

**Comment by pietrovismara** [comment]
What if I can't change the `moduleResolution` to `node` since my app needs `NodeNext` to work?
