### ISSUE TITLE
Incompatibility with viewport.drag() in pixi.js v5.0.2

### ISSUE THREAD

**Issue by tzy502** [davidfig/pixi-viewport#458]
When using version 5.0.2, the code viewport.drag().pinch().wheel().decelerate() in the demo does not enable dragging functionality. I had to roll back to version 5.0.1 in order to make it work properly.

**Comment by blnvdanil** [comment]
Which version of a pixijs are you using?

**Comment by tzy502** [comment]
7.1.4

**Comment by blnvdanil** [comment]
It seems to be related to the changes which was made in pixijs 7.2, where `displayObject.interactive = true` was deprecated, and 5.2 version of this library is transfered from `displayObject.eventMode = "static"`, which means that if you are using pixijs < 7.2 and viewport 5.2 interaction wont work properly

**Comment by blnvdanil** [comment]
You can see those changes listed here

https://github.com/pixijs/pixijs/releases/tag/v7.2.0

**Comment by tzy502** [comment]
thank you
