### ISSUE TITLE
clampZoomPercent?

### ISSUE THREAD

**Issue by Shatterbrain** [davidfig/pixi-viewport#46]
Hi, I have a suggestion for what I would guess is a common use case. 

ClampZoom lets you clamp relative to the size of the viewport, but I'm interested in clamping relative to the container's scale so that the min and max zoom are always values that scale nicely, e.g. x0.5 to x2. Something along the lines of: `new Viewport({...}).pinch().clampZoom({min:  0.5, max: 2});`. Allowing the same with snapZoom would be nice as well.

Maybe there's already a straightforward way of doing this with the current API that I'm missing.

**Comment by davidfig** [comment]
Can't you just call it like this:
```js
var worldWidth = 100;
var worldHeight = 100;
new Viewport({ worldWidth, worldHeight })
   .clampZoom({ minWidth: worldWidth / 2, minHeight: worldHeight / 2, maxWidth: worldWidth * 2, maxHeight: worldHeight * 2 });
```
Or is your world size changing often that you prefer this is automated?

**Comment by Shatterbrain** [comment]
I think that would have worked, but I ended up settling on something that I thought was better for user experience. I'll share it here for anyone else interested in locking the user to certain scales:

```
const snapZoomDefault = () => {
    const snapPoints = [0.5, 1, 2, 3];
    const currentScale = this.viewport.scale.x;
    const snapScale = snapPoints.reduce((prev, curr) => 
        Math.abs(curr - currentScale) < Math.abs(prev - currentScale) ? curr : prev
    );
    this.viewport.snapZoom({
        width: this.viewport.screenWidth / snapScale,
        time: 500,
    });
};
this.viewport.on("pinch-end", () => {
    snapZoomDefault();
});
```

This lets the user resize freely, then snaps them to a nice-looking scale afterward. Has the secondary effect of a 'soft clamp', letting them temporarily zoom things in/out to get a look before it goes back to a more playable scale.

Thanks for your work on this excellent library.
