### ISSUE TITLE
How to moveCenter with easing?

### ISSUE THREAD

**Issue by rienheuver** [davidfig/pixi-viewport#464]
I'm using pixi-viewport and pixi-ease in my application and want to ease the camera movement when calling `viewport.toCenter()`. But how do I do this?

**Comment by blnvdanil** [comment]
There is `Animate` plugin, isn't it what you are looking for?

**Comment by rienheuver** [comment]
I've just been trying this, but can't get any difference to work. I also can't find much documentation on what `.animate` is or does. Could you perhaps help me along with this?

**Comment by blnvdanil** [comment]
I guess that you should just call animate instead of moveCenter()
There is a simple example which moves viewport on click https://codesandbox.io/s/laughing-sound-dqtk7f

**Comment by rienheuver** [comment]
Ah right, that works. Thanks! This should really be documented somewhere better in my opinion, but at least it works now
