### ISSUE TITLE
Restrict viewport to the world borders when follows object

### ISSUE THREAD

**Issue by CurlyBraceTT** [davidfig/pixi-viewport#47]
When using follow method - viewport shows areas beyond world box. I restrict viewport position by next lines inside the update method of the follow plugin:

```
this.parent.x = Math.min(this.parent.x, 0);
this.parent.y = Math.min(this.parent.y, 0);
this.parent.x = Math.max(this.parent.x, this.parent.screenWidth - this.parent.worldWidth);
this.parent.y = Math.max(this.parent.y, this.parent.screenHeight - this.parent.worldHeight);
```

Is there a better way to do this and maybe this should be done on a higher level?

**Comment by davidfig** [comment]
Did you try viewport.clamp()? That keeps the camera from moving beyond the borders and works with follow.

**Comment by CurlyBraceTT** [comment]
clamp solved it, thanks.
