### ISSUE TITLE
NPM Release Version Mismatch

### ISSUE THREAD

**Issue by robin-rpr** [davidfig/pixi-viewport#485]
Hello there,

First of all some praise for the fantastic package!
I have noticed a Version mismatch in the NPM Release of 5.1.0 and 5.0.2

Please see the `package.json` file in both releases.
https://www.npmjs.com/package/pixi-viewport/v/5.1.0?activeTab=code
https://www.npmjs.com/package/pixi-viewport/v/5.0.2?activeTab=code

What I expected was that the PIXI Version would remain at 7.x
What I am seeing is a PIXI Version downgrade back to 6.x

Was this downgrade intentional with this new minor release 3 days ago? =)

Best, Robin

**Comment by ivan-work** [comment]
does it even work for you? I have troubles with making it work for pixi.js@8.0.5, you just can't do `app.stage.addChild(viewport)`

**Comment by robin-rpr** [comment]
Yeah @ivan-work, pixi-viewpoint is only compatible up to pixi.js@7.0.0 sharp, anything above is not yet supported.

The following is the latest combination you can have as of today:
```
"@pixi-essentials/cull": "^2.0.0", /* Optional, if you want to use culling */
"pixi-viewport": "^5.0.2",
"pixi.js": "^7.0.0",
```

**Comment by ivan-work** [comment]
I'm sorry, what does "pixi-viewport suports pixi 8.0.4 thanks to @WillYuum" mean in https://github.com/davidfig/pixi-viewport/releases/tag/5.1.0 then?

**Comment by robin-rpr** [comment]
@ivan-work Please read this Issue description.

**Comment by nightgrey** [comment]
Basically, the version on NPM and on GitHub are out of sync... see #487.

**Comment by robin-rpr** [comment]
Closing this issue in favour of continuing discussion of this issue at #487
