### ISSUE TITLE
Is this project suitable for @pixi/react?

### ISSUE THREAD

**Issue by imMadsen** [davidfig/pixi-viewport#489]
I have seen a lot of issues tried a lot of "solutions" but had zero luck getting this library to work with @pixi/react
If anyone has had any luck would you mind sharing?

I could try to post my current solution but it's basically almost all combinations from #438, but no dice.,

**Comment by imMadsen** [comment]
I finally got it working I think. For anyone else with this issue I published a plain [example app](https://github.com/imMadsen/reactpixi-pixi-viewport-example-app) based off the Custom Components example from the Documentation

Best of luck

**Comment by rvion** [comment]
Hey @imMadsen , do you still have that app around ? the link 404; is the repo public ? Would really help
Thanks a lot

**Comment by artemonster** [comment]
can you please post your solution @imMadsen

**Comment by JustinShetty** [comment]
Also interested in seeing a basic working example @imMadsen

**Comment by ActomicIceBreaker** [comment]
@rvion @artemonster @JustinShetty 
https://github.com/shotnothing/reactpixi-pixi-viewport-example-app 
Prolly found a fork.
