### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by macropp** [davidfig/pixi-viewport#51]
Hi David,

First of all, great little library with a lot of handy features! well done!

I'm only missing a definitions file for Typescript projects, where I have to `import * as Viewport from "pixi-viewport";` and put a `// @ts-ignore` on top of it so that it doesn't complain about Viewport having `any` type.

I'm sure many others will find `@types/pixi-viewport` npm package useful. I don't have too much experience with publishing packages on npm, especially for types, but I'm willing to help.

Keep up the great work!
Gio

**Comment by davidfig** [comment]
I have limited experience with typescript, but I'm happy to add support for it in the library. Can you help create the types file? I can create the npm repository so it can be kept in sync with the main repository.

**Comment by macropp** [comment]
Hi David,

sorry I couldn't get in touch earlier. I can do it manually, but it'd need to be maintained all the time. I couldn't find any reliable solutions to generate types from jsdocs. I'll get back to you when I find some free time.

Gio

**Comment by davidfig** [comment]
Gio, if you can generate the initial one, I'll take on maintaining it. Thanks!

**Comment by macropp** [comment]
Hi David,

Sorry, it took me some time to find a bit of free time to contribute. I created a pull request #53. Let me know if there's something you want to change.

Gio

**Comment by davidfig** [comment]
Thanks for your help, Gio!
