### ISSUE TITLE
zoom() method should return Viewport

### ISSUE THREAD

**Issue by macropp** [davidfig/pixi-viewport#52]
According to the JSDocs, zoom should return `Viewport`, but it doesn't return anything.

Which one should be changed, docs or implementation?

https://github.com/davidfig/pixi-viewport/blob/fbf5982dce057790086f73dd637dd08049daaca6/src/viewport.js#L660

**Comment by davidfig** [comment]
zoom should return viewport

**Comment by davidfig** [comment]
fixed in v2.2.0
