### ISSUE TITLE
Zoom pointer position offset after resizing the canvas

### ISSUE THREAD

**Issue by jtpio** [davidfig/pixi-viewport#56]
Hi,

It seems that the zoom pointer position becomes off after auto resizing the canvas.

This happens when:
- setting `app.renderer.autoresize = true;`
- resizing the canvas (by opening the developer tools on the right side for example)

Here is what it looks like:
1. Before resizing the canvas, I aim at the green square and the pink one, which works fine
2. After resizing the canvas, aiming at the yellow square and the purple one becomes "off" (have to recenter the viewport)

![pixi_viewport](https://user-images.githubusercontent.com/591645/42110984-375748d0-7be3-11e8-9d19-2e80f0512572.gif)

Here is the code:

```javascript
var pixi_container = $('#pixi');
var w = pixi_container.innerWidth();
var h = $(document).innerHeight() - pixi_container.offset().top;

var [W, H] = [4 * 1024, 3 * 1024];

// create viewport
var viewport = new Viewport({
  screenWidth: w,
  screenHeight: h,
  worldWidth: W,
  worldHeight: H,
});

// add the viewport to the stage
var app = new PIXI.Application({
  width: width,
  height: height,
  antialias: true,
  transparent: false,
  resolution: 1,
  backgroundColor: 0x00aabb
});
app.renderer.autoResize = true;
app.stage.addChild(viewport);
container.appendChild(app.view);

// activate plugins
viewport
  .drag()
  .clamp()
  .pinch({ noDrag: true })
  .wheel()
  .clampZoom({ maxWidth: W, maxHeight: H, minWidth: w, minHeight: h })
  .decelerate();

viewport.fit().resize(w, h, W, H);
viewport.moveCenter(W / 2, H / 2);  // center viewport

// add a bunch of red boxes
for (let i = 0; i < 100; i++) {
  var sprite = viewport.addChild(new PIXI.Sprite(PIXI.Texture.WHITE));
  sprite.anchor.set(0.5);
  sprite.tint = 0xff0000 * Math.random();
  sprite.width = sprite.height = Math.random() * 200;
  sprite.position.set(Math.random() * W, Math.random() * H);
}
```

The reason for this might be related to the `autoResize` flag on the Pixi renderer being set as a CSS property, and the mouse coordinates not taking that into account.

What would be the simplest way to solve this?

Thanks for the help!

**Comment by davidfig** [comment]
You need to resize the viewport when the resize event fires. Here's what you need to add:

```js
window.addEventListener('resize', () => {
   viewport.resize(window.innerWidth, window.innerHeight);
});````

**Comment by jtpio** [comment]
Thanks for the reply, will investigate that :+1:
