### ISSUE TITLE
Cannot drag using laptop touch screen

### ISSUE THREAD

**Issue by qwertysam** [davidfig/pixi-viewport#58]
Tested on Chrome Version 69.0.3464.0 (Official Build) dev (64-bit)

Dragging still works on phone touchscreens.

**Comment by davidfig** [comment]
Hmm . . . is chrome changing something? I have the non-dev Version 67.0.3396.99 (Official Build) (64-bit) with a Surface 3 touchscreen and I don't see any issues. Can you try the non-dev chrome version to ensure it's not a computer problem.

**Comment by davidfig** [comment]
Hmm...can you test a generic pixi.js interactive object and see if that works with touch to check if it's a touchscreen problem or a pixi-viewport issue.

**Comment by davidfig** [comment]
Closing this. Feel free to reopen if you have further info that we can pursue.

**Comment by qwertysam** [comment]
Confirmed on Chrome Version 69.0.3497.21 (Official Build) dev (64-bit) to be working again
