### ISSUE TITLE
How to set mouse event offset?

### ISSUE THREAD

**Issue by Zentendo** [davidfig/pixi-viewport#60]
I encountered this issue with `pixi-scrollbox` and `yy-ui`. Whenever the WebGL Canvas element which contains PIXI does not start from `0,0` x/y in the browser window, the mouse events will not correctly offset. For example if I try to scroll down with the mouse wheel, then mouse events will trigger if my mouse is over `0,0`, which is not where the canvas is. Say the canvas is placed at `100,100` and is 300 in width and 300 in height. Well the mouse event will trigger at `0,0` where the canvas isn't even at, but it will not trigger at `400,400` where the canvas is, because it will be offset by it's browser window position. 

It seems to understand where the PIXI.JS container/display object is relative to the start of the browser window x/y position, but NOT where the canvas actually is, resulting in all mouse events triggering only outside of the actual canvas if the canvas does not start perfectly at `0,0` in the browser.

Why is the mouse position calculated by where the mouse at relative to the browser window and not relative to where the canvas is placed / inside the canvas, and how can I fix that / correctly offset it?

**Comment by kaflake** [comment]
I hav the same effect on zooming.
Cause handleWheel use clientX and clientY without the offset. handleWheel think its outside the viewport.
My solution is overriting the handleWheel method, here with typescript

`export class MyViewport extends Viewport {
  offsetX = 0;
  offsetY = 0;

  handleWheel(e: WheelEvent) {
    const newClientX = e.clientX - this.offsetX;
    const newClientY = e.clientY - this.offsetY;

    return super.handleWheel(<WheelEvent>{
      clientX: newClientX,
      clientY: newClientY,
      deltaX: e.deltaX,
      deltaY: e.deltaY,
      preventDefault: () => e.preventDefault()
    });
  }
}`

**Comment by davidfig** [comment]
handlewheel() is outside pixi.js since they don't support wheel events (for reasonably valid reasons). In your solution, where are you setting this.offsetX/Y?

**Comment by kaflake** [comment]
before I set the offset in a central positon. But now I have an application where the canvas is inside an Scroller so this solution set offset onetime do not work any more.
My new solution is to inject the canvas Element (view) and get the offset from there:

```typescript
  handleWheel(e: WheelEvent) {
    const clientRect = this.view.getBoundingClientRect();
    const offsetX = clientRect.left;
    const offsetY = clientRect.top;

    const newClientX = e.clientX - offsetX;
    const newClientY = e.clientY - offsetY;
...

**Comment by davidfig** [comment]
Try out v3.4.0. You need to set the PIXI.interaction in the Viewport options:

```js
new Viewport({ interaction: renderer.plugins.interaction })
```
where renderer = your instantiated PIXI.WebGLRenderer or PIXI.CanvasRenderer

Let me know if this helps.

**Comment by kaflake** [comment]
Hey,
this is working well.
Thank you!

**Comment by davidfig** [comment]
Closing this. I'll update the documentation to try to call out this option more clearly.

**Comment by TomerAtarScopio** [comment]
I had a similar issue, my library depended on pixi-viewport@5 as a peer, but had pixi-viewport@4 in the consuming project
(which caused the viewport to start without a reference to interactions as we now pass the events instead).

upgrading to pixi-viewport@5 in the consuming project fixed this of course
