### ISSUE TITLE
All kinds of moved should be separated

### ISSUE THREAD

**Issue by shijunti19** [davidfig/pixi-viewport#61]
All the moved  should not be mixed together
drag-end
drag-start
There should be one  ： drag-moved
The drag process should also have an independent event

**Comment by davidfig** [comment]
Hmm...the moved event is designed to be generic so you can do something any time the viewport is moved by one of the plugins. 

What I can add is a type parameter on the moved event telling you what triggered the move. Would that be helpful?

**Comment by shijunti19** [comment]
@davidfig  Thank you！It should be a parameter distinction, I think it is very important.

**Comment by davidfig** [comment]
Try out pixi-viewport@3.0.0 

The 'moved' event now has { viewport, type } where type is @property {string} type (drag, snap, pinch, follow, bounce-x, bounce-y, clamp-x, clamp-y, decelerate, mouse-edges, wheel)

Hopefully that helps!
