### ISSUE TITLE
Cannot find namespace 'PIXI'

### ISSUE THREAD

**Issue by gsknbabu** [davidfig/pixi-viewport#62]
Hi
I am getting 'Cannot find namespace 'PIXI'' error in index.d.ts file. Any workaround is available to this?

I am using it in Angular application.

versions:
"pixi-viewport": "^2.7.2",
"pixi.js": "^4.8.1",

**Comment by davidfig** [comment]
This may be related to #63. Make sure that pixi.js is imported before pixi-viewport as pixi-viewport only has a peer-requirement with pixi.js. I really need to get on the typescript and angular bandwagon. Sigh.

**Comment by macropp** [comment]
Hi @gsknbabu, were you able to resolve your issue?
Do you also have `@types/pixi.js` in your project dependencies? If not, I'd try adding that to get type definitions for pixi.

**Comment by davidfig** [comment]
Closing this since it's been inactive. Feel free to reopen if you still have this issue.

**Comment by heekah7** [comment]
The issue still persist, I resolve it by using 3.23.2
