### ISSUE TITLE
screen wagglling while two-finger touch to drag without set pinch

### ISSUE THREAD

**Issue by yinpeng633** [davidfig/pixi-viewport#65]

**Comment by davidfig** [comment]
I've seen this before and have been meaning to fix it. I'm working on replacing the drag() logic with the pinch() logic (minus the zoom).

**Comment by davidfig** [comment]
Try out npm v3.1.0. It should perform without waggling when two-finger dragging without pinch.

**Comment by davidfig** [comment]
Hopefully this fix worked for you.

**Comment by yinpeng633** [comment]
thanks David, this fix worked.
