### ISSUE TITLE
Remove the event listeners

### ISSUE THREAD

**Issue by michaeleekk** [davidfig/pixi-viewport#66]
There are two global event listeners that wouldn't be removed properly. One is the PIXI.ticker event in `viewport.js` and the other is a wheel event that would add to the wheel div or `document.body`.

Maybe it would be better to remove these two event listeners when the viewport is destroying ?

The use-case is when PIXI canvas is added to those web frameworks like Vue.js, the canvas and variables are removed when the component is destroyed, but the global variables or event listeners would be left behind.

I tried simply calling the following two functions would help releasing the event listeners,

```
this.ticker.remove(this.tickerFunction);
this.wheelListener.removeEventListener('wheel', this.wheelFunction);
```

**Comment by davidfig** [comment]
Good suggestion. I added a viewport.removeListeners() with your code to pixi-viewport@3.2.0. It'll still need to be called manually during cleanup.

**Comment by michaeleekk** [comment]
@davidfig Thanks for the super fast response !

One more question, I wonder when those PIXI.Container or PIXI Renderer trying to destroy the children components, will they trigger the children's destroy() ? In that case, if the removeListeners() is inside a destroy(), that could clean up the listeners automatically when destroying the renderer with,

```
renderer.destroy(true); // destroy the view also
```

Or if the viewport is inside another container called `stage`,

```
stage.destroy({ children: true, texture: true, baseTexture: true });
```

I wonder how does that sound ?

**Comment by michaeleekk** [comment]
And one question about [this line](https://github.com/davidfig/pixi-viewport/commit/1a01f029ba43a9d42ba5d835ee3c347a4cb05c22#diff-16a8e12ddbd67cb5873ec5be2fc9da48R205), should it be `removeListeners()` ?

**Comment by davidfig** [comment]
That makes sense. I added it to the destroy(), which triggers children to be destroyed if { children: true }. I don't think anything bad will happen if you end up removing the listeners twice. 

Also fixed the typescript file. 

@3.2.1 has these fixes.

**Comment by michaeleekk** [comment]
Thanks for the quick response again !

Although I didn't see 3.2.1 changes in Github, I got the update from npm !

Shall I close this issue ?

**Comment by davidfig** [comment]
Forgot to push the changes after publishing. I'll close it. Thanks for the feedback!
