### ISSUE TITLE
Culling

### ISSUE THREAD

**Issue by dmecke** [davidfig/pixi-viewport#70]
Does this library support culling? I move my camera object around on a very large map and would like all non-visible objects to be set to `visible = false` for performance reasons.

**Comment by davidfig** [comment]
It currently does not. I usually roll my own. If it would be helpful, I could add a simple version, but I worry that it's outside the scope of what people expect from a viewport.

**Comment by omegablitz** [comment]
Also would concur with the idea of keeping generalized culling as a separate plugin. In a lot of cases I think it makes the most sense to do culling manually, as the library can't be aware of semantics behind different elements (e.g. static, dynamic), and applying some sort of generic garbage collection algorithm could be relatively expensive.

**Comment by davidfig** [comment]
Cool beans. I'll add this to my list of fun projects ⛰

**Comment by davidfig** [comment]
I just published an early version of pixi-cull. Check it out: https://github.com/davidfig/pixi-cull

It has two culling algorithms: a simple cull and a spatial hash. There's still probably a bunch bugs since I only tested it on the demo page, but I'll be adding the spatial-hash to my current project over the next few days.

**Comment by 0xbkt** [comment]
@davidfig We need to use pixi-cull if we need culling right? So no built-in culling in pixi-viewport?

**Comment by davidfig** [comment]
Yup. It's a separate library. Culling is very project specific and I didn't feel it fit within what i was trying to accomplish with pixi-viewport. The pixi-cull library I released above does integrate nicely with pixi-viewport, though.
