### ISSUE TITLE
Incorrect behaviour when resolution = 2

### ISSUE THREAD

**Issue by korroktheslavemaster** [davidfig/pixi-viewport#74]
When I create a PIXI.Application with `resolution = 2`, the zoom behaviour of `pixi-viewport` is weird. Zooming doesn't happen centred on the mouse pointer but some point outside the viewport.

**Comment by korroktheslavemaster** [comment]
I managed to fix it by adding `interaction: app.renderer.plugins.interaction` to the `Viewport` constructor. I only got this by looking through the code of the Live Example.

**Comment by eranimo** [comment]
The above workaround worked for me as well

**Comment by eranimo** [comment]
Yes—that fixed the original bug but I'm having an issue where I can only zoom with the mousewheel in the top-left part of the screen.

**Comment by davidfig** [comment]
Ok. The fix was specific to the wheel() module, so glad it worked.

As to your other issue: are you using a full-screen viewport or only partial? Can you show me how to replicate the bug? It seems to work for me.

**Comment by korroktheslavemaster** [comment]
I'm not using full screen. It's pixi default size i think which is 800x600

**Comment by davidfig** [comment]
The wheel is only active when the mouse is hovering over the viewport (this allows the wheel to work across multiple viewports). Is your mouse over the viewport when you're using the wheel?

**Comment by korroktheslavemaster** [comment]
yes. i'll try to make a jsfiddle and then post it for better clarity

**Comment by davidfig** [comment]
Closing this since no response. Feel free to reopen.
