### ISSUE TITLE
Smooth zooming

### ISSUE THREAD

**Issue by omegablitz** [davidfig/pixi-viewport#75]
Is there an established way for scrollwheel zooming to be done smoothly?

**Comment by davidfig** [comment]
Have you tried changing the options.percent in the wheel() plugin? I don't have a good feel about scrollwheel zooming since I don't use scrollwheels. Any recommendations?

**Comment by omegablitz** [comment]
The current problem I'm having is that scrolling with my mousewheel looks jittery, as it's 'jumping' between different zoom levels. This is probably because my mousewheel has not-so granular ticks. Increasing `options.percent` makes the scrolling smoother, at the cost of zooming taking a lot longer (because more mousewheel rotation is required).

Ideally, there'd be a way to enable multiple frames being drawn for a single mousewheel 'event', perhaps the number of frames being directly proportional to the mousewheel delta to account for differences in mice.

Not sure if I explained this well... does this make sense?

**Comment by davidfig** [comment]
Yes, that makes sense. It's certainly possible, but I'm struggling with what options to provide.

I was thinking of putting a maxPercent/frame that subdivides the percent across frames. It still may lag behind your scrolling. Is that what you were thinking? Or do you have a better idea?

**Comment by omegablitz** [comment]
maxPercent/frame sounds like it'd work well; the lag shouldn't be that big of a problem considering that it's tunable :)

**Comment by davidfig** [comment]
The smooth option was added in 3.5.0. options.smooth = the number of frames to smooth the zoom. Use it like this:

```js
viewport.wheel({ smooth: 3 })
```
Try it out and let me know if it works for you.

**Comment by Poylar** [comment]
I think that it is also necessary to add the ability to smoothly zoom using the setZoom method and other similar ones. At the moment, I have not found anything about this functionality in the documentation.
