### ISSUE TITLE
The dirty attribute in render is true every time.

### ISSUE THREAD

**Issue by 1977474741** [davidfig/pixi-viewport#81]
The dirty attribute in render is true every time.
I initialized this way.
![image](https://user-images.githubusercontent.com/22722580/45292193-065e5e80-b527-11e8-9df5-44b7bd85c82a.png)

**Comment by davidfig** [comment]
Did you reset it to false after rendering? It doesn't reset itself every frame in case you are skip a frame of rendering.

**Comment by 1977474741** [comment]
I reset it to false, but I still can't do it.
![image](https://user-images.githubusercontent.com/22722580/45334475-7fa09480-b5ad-11e8-8035-07c2aad915a4.png)  
I do this now, keeping the location of last view to determine whether this position is the same.
But dirty has always been true.

**Comment by davidfig** [comment]
Weird. I just tried it on the demo and dirty stays false unless something changes in the viewport. Are you changing or moving the viewport anywhere else in your code? Any move (even to the same place) will trigger dirty = true. Are you using any other plugins besides clamp?

**Comment by 1977474741** [comment]
I checked it again and did not change the location of view. @davidfig

**Comment by davidfig** [comment]
Hmm...try it without clamp.

**Comment by 1977474741** [comment]
After removing the code, it is still not possible.
![image](https://user-images.githubusercontent.com/22722580/45335410-d6a86880-b5b1-11e8-8981-bc215eef1572.png)
Unless we delete this.
![image](https://user-images.githubusercontent.com/22722580/45335484-3a329600-b5b2-11e8-9f29-961f33667b43.png)
@davidfig

**Comment by davidfig** [comment]
Ah. Found the problem. follow() was not checking to see if it was already at the right spot. Let me fix that.

**Comment by 1977474741** [comment]
That's fine. Thank you! @davidfig

**Comment by davidfig** [comment]
Try out v3.6.3. follow() shouldn't trigger unless target changed position

**Comment by 1977474741** [comment]
Same as before, still not. @davidfig My code has not changed.

**Comment by davidfig** [comment]
Is there a conflict between clamp and follow? Try it with and without clamp and with and without follow.

**Comment by 1977474741** [comment]
Clamp is always fine, no matter whether there is follow or not. But as long as there is follow, dirty will always be true. The right to decide lies in follow.  @davidfig

**Comment by davidfig** [comment]
Ok. I'll need you to debug this since I can't replicate. Can you set a breakpoint in the viewport code here:

```js
var deltaX = toX - center.x;
var deltaY = toY - center.y;
breakpoint> if (deltaX || deltaY) {
```
After the initial call, deltaX and deltaY should be 0 which means that it doesn't call moveCenter (which is what sets dirty=true). This is what happens in my demo code.

Just to ensure you have the right file, the babelifed version of this function looks like this:

```js
    _createClass(Follow, [{
        key: 'update',
        value: function update() {
            if (this.paused) {
                return;
            }

            var center = this.parent.center;
            var toX = this.target.x,
                toY = this.target.y;
            if (this.radius) {
                var distance = Math.sqrt(Math.pow(this.target.y - center.y, 2) + Math.pow(this.target.x - center.x, 2));
                if (distance > this.radius) {
                    var angle = Math.atan2(this.target.y - center.y, this.target.x - center.x);
                    toX = this.target.x - Math.cos(angle) * this.radius;
                    toY = this.target.y - Math.sin(angle) * this.radius;
                } else {
                    return;
                }
            }
            var deltaX = toX - center.x;
            var deltaY = toY - center.y;
            if (deltaX || deltaY) {
                if (this.speed) {
                    var _angle = Math.atan2(toY - center.y, toX - center.x);
                    var changeX = Math.cos(_angle) * this.speed;
                    var changeY = Math.sin(_angle) * this.speed;
                    var x = Math.abs(changeX) > Math.abs(deltaX) ? toX : center.x + changeX;
                    var y = Math.abs(changeY) > Math.abs(deltaY) ? toY : center.y + changeY;
                    this.parent.moveCenter(x, y);
                    this.parent.emit('moved', { viewport: this.parent, type: 'follow' });
                } else {
                    this.parent.moveCenter(toX, toY);
                    this.parent.emit('moved', { viewport: this.parent, type: 'follow' });
                }
            }
        }
    }]);
```

**Comment by 1977474741** [comment]
![image](https://user-images.githubusercontent.com/22722580/45339829-cbac0300-b5c6-11e8-86c2-9644725976e7.png)
Every time I can get in, I look at the code, and it seems that if the object in the follower changes its position, it will get in.

Although the object has changed, the view has not changed, because the clamp is added, it should not be entered. The dirty property is whether the view needs to be changed, so is there any logic error?

**Comment by davidfig** [comment]
It's a conflict between the clamp() and follow() plugins. follow() moves the viewport, which causes viewport.dirty=true and then clamp returns the viewport to its original location so it appears like nothing has changed.

I ran into this issue with another plugin. The fix is to apply clamp in the follow() plugin before checking for a change. I'll see if I can quickly cut-and-paste that code.

**Comment by davidfig** [comment]
My original idea did not work. Way too complicated to apply clamp and then test. Instead I redid the dirty code so it only changes during the update() loop. I do the same test (plus scale check) as your workaround in the update loop. 

Try it out: v3.6.4

**Comment by 1977474741** [comment]
![gif](https://user-images.githubusercontent.com/22722580/45342390-62c98880-b5d0-11e8-82f1-27a186320cf6.gif)
OK, it's better than before. It's normal when you're near the boundary, but it's always true when you're not near the boundary, even if the view doesn't move.
@davidfig

**Comment by 1977474741** [comment]
It doesn't matter. I'm not in a hurry. It doesn't matter much to me. It's just a performance issue. If you want to optimize, you can optimize it slowly.
@davidfig

**Comment by davidfig** [comment]
No problem. I use the dirty flag for optimization as well. I do want to track down the issue, but it's working correctly on my end again 😺 Do you have any other code that's moving the viewport? It looks like you're using a physics engine. Is the car moving slowly at the end? The dirty code is now super simple:
```js
update()
{
            ...
            this._dirty = this._dirty || !this.lastViewport ||
                this.lastViewport.x !== this.x || this.lastViewport.y !== this.y ||
                this.lastViewport.scaleX !== this.scale.x || this.lastViewport.scaleY !== this.scale.y
            this.lastViewport = {
                x: this.x,
                y: this.y,
                scaleX: this.scale.x,
                scaleY: this.scale.y
            }
}
```
If you can check what's going on with lastViewport we can check why dirty is changed.

**Comment by 1977474741** [comment]
Is that why? If it is, it will be OK.
@davidfig

**Comment by davidfig** [comment]
That's my theory having worked with physics engines in the past.

**Comment by 1977474741** [comment]
Ha ha, OK, thank you. Happy cooperation. @davidfig

**Comment by davidfig** [comment]
Closing this. Feel free to reopen if it continues to be a problem.
