### ISSUE TITLE
pixi.js v5

### ISSUE THREAD

**Issue by davidfig** [davidfig/pixi-viewport#85]
I've done some initial testing on pixi.js v5, and except for a deprecation warning, everything seems to be working. I'll perform testing on the new builds as they get closer to release.

**Comment by peekxc** [comment]
I'm having the same issues as [138](https://github.com/davidfig/pixi-viewport/issues/138) in trying to use v5. Which version of 5 were you able to get working?

(btw, thank you for this great plugin :))

**Comment by davidfig** [comment]
Which version of pixi-viewport are you using? The newer released no longer use PIXI.extras because of incompatibility with v5.
