### ISSUE TITLE
Can't get click event to trigger..

### ISSUE THREAD

**Issue by MaZZly** [davidfig/pixi-viewport#87]
Hi,

I've finally gotten the viewport to follow my player as I want. Rendering works fine also (using lance-gg with P2.js for physics)

Now the click events from mouse doesn't seem to trigger.. mousemove events works perfectly.
Any idea what might be the problem? I've been pulling my hair with this one and can't figure it out.

```javascript
onDOMLoaded() {
    this.app = new PIXI.Application({
        width: window.innerWidth,
        height: window.innerHeight,
        backgroundColor: 0xf5f5f5,
        transparent: false,
        antialias: true,
    });
    document.body.appendChild(this.app.view);

    this.viewport = new Viewport({
        screenWidth: window.innerWidth,
        screenHeight: window.innerHeight,
        worldWidth: this.gameEngine.worldWidth,
        worldHeight: this.gameEngine.worldHeight,
        interaction: this.app.renderer.plugins.interaction
    });
    this.app.stage.addChild(this.viewport);

    this.viewport.on('clicked', (e) => console.log('clicked (' + e.world.x + ',' + e.world.y + ')'))

    this.viewport.on('mousemove', (e) => {
        this.clientEngine.sendInput('mousePos', this.viewport.toWorld(e.data.global));
    })

    let box = new PIXI.Graphics();
    this.viewport.addChild(box);
    box.lineStyle(5, 0x000000)
        .moveTo(0, 0)
        .lineTo(0, this.gameEngine.worldHeight)
        .lineTo(this.gameEngine.worldWidth, this.gameEngine.worldHeight)
        .lineTo(this.gameEngine.worldWidth, 0)
        .lineTo(0, 0)

    this.viewport.setTransform(0, this.gameEngine.worldHeight, 1, -1, 0, 0, 0, 0, 0);
}
```

**Comment by davidfig** [comment]
Your setTransform() call results in the click registering as out of bounds for the viewport. If you take it out it works. What's the purpose of this call?

**Comment by MaZZly** [comment]
Yep that's it...

The reason for that transform is that P2.js has the Y-axis inverted (0 = bottom of world).
Without it, everything will render upside down.

Is there any way to disable the out of bounds check? (since the mousemove seems to find the correct position relative to the world I guess the click should also be correct?).

Or am I doing the "flipping/mirroring" of the Y-axis the wrong way?

Thanks again for the help!

**Comment by MaZZly** [comment]
Well, I'm translating it with the setTransform =)

I tried also just calculating `render.y = worldheight - y`, but that messes up the mousemove coords..

I tested to wrap it inside its own Container but that got me back to my initial problems where it renders completely wrong place of the viewport.

**Comment by davidfig** [comment]
Hmm...are the mousemove coordinates just inverted? Can you translate them instead?

**Comment by MaZZly** [comment]
Now I have it working without using the setTransform.

I'm not really sure I like the solution tho.. I have to invert all y-coordinates to `worldheight - y`, and also invert angles `angle * -1`

Mouse handling:
```javascript
this.viewport.on('mousedown', (e) => {
    let pos = this.viewport.toWorld(e.data.global);
    this.clientEngine.sendInput('mouseClick', { x: pos.x, y: this.gameEngine.worldHeight - pos.y });
})
this.viewport.on('mousemove', (e) => {
    let pos = this.viewport.toWorld(e.data.global);
    this.clientEngine.sendInput('mousePos', { x: pos.x, y: this.gameEngine.worldHeight - pos.y });
})
```

Sprite rendering:
```javascript
sprite.rotation = -obj.angle;
sprite.x = obj.position.x;
sprite.y = this.gameEngine.worldHeight - obj.position.y;
```

With the code from original Issue description, everything except click triggering worked out-of-the-box, 
 * No manual inversion of positions, angles, mouse-position
 * mousemove translation came correct from pixi-viewport (I'm quite sure same would've applied for click)

The only thing was the problem with the click events not triggering.

**Could pixi-viewport be made to also handle inverted Y-axis / setTransform, so that "out of bounds" would not trigger for this?**

**Comment by davidfig** [comment]
This is similar to how Phaser handles p2.js. They apply a translation to go from p2 world coordinates to Phaser coordinates, which includes the inverting the y-axis and scaling from meters to pixels. 

The out-of-bounds is not coming from pixi-viewport but from pixi.js (viewport just uses pixi's interaction code). The likely reason why clicked is not working is because of the viewport.hitArea setting. My guess (and I haven't debugged it to see what's going on) is that it gets confused because everything is inverted.

I have plans to allow for the viewport to work with arbitrary transforms on its parent elements, but I haven't had a need for it yet to justify the additional work.

If you don't like the working solution, you can probably get the p2 container as a child of viewport working. You'll have to set the position of your p2 container to properly line it up with the viewport. You'll still need to use the translation in the mouse events--but that's probably true for most schemes since you're moving between coordinate systems.

**Comment by MaZZly** [comment]
hmm I guess I could try the container method. How to get the p2-container properly lined up within the viewport (I think this was actually the problem I faced before).
Mouse translation is probably fine as it's only 2 places.

**Comment by davidfig** [comment]
Hopping up on a soapbox for a sec: You're underestimating the speed of javascript. I used to hyper-optimize my code. I would definitely have worried about your sprite rendering code above and desperately searched for a better solution. Then I spent time looking through pixi.js's code and realized how often they perform complicated transformations. Even with tens of thousands of sprites and all those transformations happening every frame, the code still ran blazing fast on mobile phones. 

With that said, the best way to line up the p2 container is to experiment with it and figure out why it's not working properly. It likely needs a position correction to account for the scaling.

**Comment by MaZZly** [comment]
yeah I'm not worried about performance, mostly trying to keep the code simple and offload most of the transformations elsewhere =)

For the position correction: Is there some special things to tweak, or simple playing around with something like container.position.y-values?

**Comment by davidfig** [comment]
I'm guessing here since I'm not sure what's happening. I would play around with the position values and see what happens.

**Comment by davidfig** [comment]
Closing this. Feel free to reopen if this is still an issue.
