### ISSUE TITLE
have any fn to monitor scroll end event？

### ISSUE THREAD

**Issue by bestlbw** [davidfig/pixi-viewport#88]
only see 'moved' event ,what events should i listener if i want to know when to scroll end ? 
thanks for any suggest

**Comment by davidfig** [comment]
v3.8.0 has two new events: 'moved-end' and 'zoomed-end'. Hopefully moved-end will be helpful. It fires when the viewport stops moving after previously moving.

**Comment by bestlbw** [comment]
Great !
