### ISSUE TITLE
Can I use multiple views at one time?

### ISSUE THREAD

**Issue by skeddles** [davidfig/pixi-viewport#92]
From the same scene, I was hoping to make a split screen. But it seems you have to add the contents of what you're drawing to the viewport to render them.

**Comment by davidfig** [comment]
How were you planning to render the split screen? You could create two viewports, and then swap the children before rendering each independently. That may work (although I've not experimented with it).

**Comment by skeddles** [comment]
I'm not sure, is it possible to change where the view is rendered on screen? It seems to just fill the renderer.

**Comment by davidfig** [comment]
The easiest way is to duplicate your world in two masked pixi-viewports (see https://github.com/davidfig/pixi-scrollbox for an example of mulitple masked pixi-viewports).

You'll have to update both worlds as they change, but that's usually not expensive.

**Comment by davidfig** [comment]
Closing this. Feel free to reopen if this is still an issue.
