### ISSUE TITLE
Zooming issues on FF mobile

### ISSUE THREAD

**Issue by uahic** [davidfig/pixi-viewport#93]
Hello,

I am just assembling an Angular 6 library to wrap some parts of pixi along with pixi-viewport. The library consists of some  components (viewport,...) and services (that creates the viewport and pixi.application objects and makes them available via dependency injection to all components/directives).

The viewport component has two HTML-div objects:  one 'container' that uses flexbox to grow as much as possible to fill out the available space inside its parent and one div as a child of this container which is the canvas-container for pixi.  

Now, I created also an test application that simply creates a blue circle via pixi.graphics. 
I activated viewport.drag {clampwheel:true}, pinch, decelerate, and wheel {smooth: 3}.

While testing on my mobile phone I noticed that it works fine in in Chrome (zooming, panning,... all works well) but in Firefox it seems to work the first few moments and then suddenly gesture-based zooming is not reacting at all (while 'dragging'/panning often still works, but not always). I was thinking that maybe just the focus is lost but I think its maybe a deeper problem in the viewport library? 

Does somebody ran into the same problem? 

Repository: https://github.com/uahic/ng-pixi
Note: you can build the contained library with simply executing 'npm install --save' once and then 'ng build --prod ng-pixi-lib' and afterwars starting the app via 'npm start'. It might happen that I modified some of the viewport or pixi-typings (I think pixi.Ticker instead of pixi.ticker.ticker... somewhere, youll see)

**Comment by uahic** [comment]
Ok seems I've solved the problem kindof ... by adding
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
to the index.html. Means that in FF indeed there was scrolling on the page itself while using gestures on the canvas area and that chrome handles this differently than FF

**Comment by uahic** [comment]
Update: nah seems there are still issues just on FF as described above

**Comment by davidfig** [comment]
Hmm....have you tried running the demo (https://davidfig.github.io/pixi-viewport/) in FF mobile? See if that has problems.

**Comment by uahic** [comment]
Hmh doesnt seem to occur there so your library is fine I guess :)

**Comment by davidfig** [comment]
It still may be the library, but my guess is it has something to do with the way your divs are set up.

**Comment by uahic** [comment]
https://github.com/uahic/ng-pixi/tree/master/projects/ng-pixi-lib/src/lib/ng-pixi-viewport 
This is the direct link to the component and this the injected service: 
https://github.com/uahic/ng-pixi/blob/master/projects/ng-pixi-lib/src/lib/ng-pixi-viewport.service.ts

I hope your'e not right here since I was quite happy to get the resizing (which happens on window:resize events) to work that easy ;)

**Comment by uahic** [comment]
My code has now been restructured and for resizing Iam using now the the document.body boundingBox width and height. It seems to work now on Firefox too, eventhough I cant tell what exactly was wrong in the first place. I close this issue for now :)
