### ISSUE TITLE
snapZoom interrupt decelerate 

### ISSUE THREAD

**Issue by florentbolo** [davidfig/pixi-viewport#94]
Hi, 

Il want to make a light scale when the user drag de viewport but snapZoom interrupt decelerate.
Do you have any fix for this ?

```
viewport.on('drag-start', () => {
  viewport.snapZoom({width:window.innerWidth+50, time:300, interrupt:false });
  viewport.decelerate({ friction: 0.78 });
});
viewport.on('drag-end', () => {
  viewport.snapZoom({width:window.innerWidth, time:700  });
});
```
Thanks

**Comment by davidfig** [comment]
Did you try adding snapZoom({ ..., noMove: true })?

**Comment by florentbolo** [comment]
Yes it's works ! ( noMove is not in the doc )
Thanks for your reply and for your work.

**Comment by davidfig** [comment]
Thanks for the feedback. The snapZoom docs now have noMove.
