### ISSUE TITLE
Viewport freezes

### ISSUE THREAD

**Issue by feskechurch** [davidfig/pixi-viewport#95]
Question! My viewport freezes randomly time from time, and im not sure if it's the viewport that is the cause or consecuence of the problem. 
I have multiple stages next to each other in the same pixi app and viewport. Its hard to recreate the freezing because so far its been randomly and i havent figured out what triggeres it.
Any tips of how to go by to find the root of the problem?

**Comment by davidfig** [comment]
Hmm...I've not seen the viewport freeze even running with lots of elements. Can you provide more details about your setup? 

Best way to track the issue down is to start commenting out your code until the freezing stops. This is more difficult if it's intermittent :)

**Comment by davidfig** [comment]
Closing this. Feel free to reopen if this is still an issue.
