### ISSUE TITLE
Follow is not centering?

### ISSUE THREAD

**Issue by hassanshaikley** [davidfig/pixi-viewport#97]
Hey,

For some reason follow is not centering (it is too far to the left)?
<img width="949" alt="screen shot 2018-11-13 at 10 44 13 pm" src="https://user-images.githubusercontent.com/6746840/48462509-accc1780-e795-11e8-8d2c-37e34a3b2d54.png">

It is following the lil fly ):

```

    this.app = new PIXI.Application({width: window.innerWidth, height: window.innerHeight});
    this.viewport = new Viewport({
      screenWidth: 600,
      screenHeight: 300,
      worldWidth: 3000,
      worldHeight: 1000,
    });

  this.viewport
    .wheel()
    .clamp({
      left: 0,
      right: 3000,
      bottom: 100,
      top: -300
    })
    .zoomPercent(.5)
    .decelerate();

    this.viewport.follow(player, {speed: 4})

```

I am not sure why it's not centering! I have tried messing with a bunch of different variables to no avail.

When super zoomed in this is what it looks like (too far to the right):
<img width="1440" alt="screen shot 2018-11-13 at 11 11 25 pm" src="https://user-images.githubusercontent.com/6746840/48463533-9c1da080-e799-11e8-94fc-0a8f624e6c77.png">

**Comment by davidfig** [comment]
The code looks correct. Is it getting caught in the clamp?

**Comment by hassanshaikley** [comment]
I tried disabling the clamp! It didn't fix it.

I just set the anchor x & y to .5 for animated sprite and that seems to have fixed it!

**Comment by davidfig** [comment]
Yup. Good catch. I use 0.5 anchor for most of animations. I updated the documentation so people can learn from your pain :)

**Comment by nazywamsiepawel** [comment]
A PIXI.Container doesn't seem to have an anchor position, pivot only. Is there any way to center around a moving container instead of a single sprite?

**Comment by davidfig** [comment]
You have to use pivot and do a bit more calculation than anchor.

**Comment by nazywamsiepawel** [comment]
Thanks for probably the quickest reply in Github issues history @davidfig!

By bit more calculation, do you mean finding the center point programmatically? I'd be fine to do it but it seems that the follow plugin doesn't have a functionality to work with a left/top offset - this would be really handy in this case but possibly a workaround for the given problem.

**Comment by davidfig** [comment]
Why do you need to follow to the top-left corner? Can't you just add the width / 2 and height / 2 to move the pivot to the center? Ideally, I want to avoid taking .width and .height, since for containers that's sometimes an expensive operation.

**Comment by nazywamsiepawel** [comment]
@davidfig you're right - my initial problem was that I confused the values that go into anchor vs pivot. Just done it as you suggested and works perfectly, thanks!
