### ISSUE TITLE
[Feature Request] Adding custom Plugins

### ISSUE THREAD

**Issue by uahic** [davidfig/pixi-viewport#98]
Hello David,

I would like to suggest a simple method to add custom plugins to the viewport;  My current goal is to create two axis with tick markers and labels; not sure yet if its better to implement that as a plugin or a parent container which wraps the viewport (probably the latter) but anyways it would be nice to have such a method at hand (typescript user here)

Cheers
Martin

**Comment by davidfig** [comment]
Check out v3.11.0. It contains a new function called userPlugin(). You can create the plugin by extending the Plugin from plugin.js. I updated the typescript definition as well. Let me know if you have any problems.

**Comment by davidfig** [comment]
Closing this since no response. Feel free to reopen.
